name: "deb-package"
description: "Package DEB Centreon"
inputs:
  module_name:
    description: "The distribution to call to package the application"
    required: true
  distrib:
    description: "The distribution to call to package the application"
    required: true
  image_version:
    description: "image_version"
    required: true
  params:
    description: "params for script"
    required: false
runs:
  using: "composite"
  steps:
    - env:
        MODULE_NAME: ${{ inputs.module_name }}
        DISTRIB: ${{ inputs.distrib }}
        IMAGE_VERSION: ${{ inputs.image_version }}
        PARAMS: ${{ inputs.params }}
      run: docker run -i --entrypoint "/src/.github/scripts/$MODULE_NAME/debian/$MODULE_NAME-packaging.sh" -v "$PWD:/src" "docker.centreon.com/centreon/$MODULE_NAME-package-$DISTRIB:$IMAGE_VERSION" $PARAMS
      shell: bash
