<?php

/*
 * Copyright 2005 - 2025 Centreon (https://www.centreon.com/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * For more information : contact@centreon.com
 *
 */

$help = [];

/**
 * Centreon Gorgone Settings
 */
$help['tip_gorgone_cmd_timeout'] = dgettext(
    'help',
    'Timeout value in seconds. Used to make actions calls timeout.'
);
$help['tip_enable_broker_stats'] = dgettext(
    'help',
    'Enable Centreon Broker statistics collection into the central server in order to reduce the network load '
    . 'generated by Centcore. Be carefull: broker statistics will not be available into Home > Broker statistics.'
);
