name: "publish-cypress-report"
description: "Publish Cypress report"
inputs:
  path:
    description: "Path to the report files"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 24

    - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      with:
        version: 10

    - name: Publish Cypress report
      env:
        REPORT_PATH: ${{ inputs.path }}
      run: |
        node ./.github/actions/publish-cypress-report/formatCypressReportToMarkdown.mjs "$REPORT_PATH" > cypress-report.md
        cat cypress-report.md >> $GITHUB_STEP_SUMMARY
      shell: bash
