name: Detect components and collect commit lists
description: Detect changed components and generate per-component commit lists

inputs:
  base_sha:
    description: ref for the base (latest stable release bundle tag)
    required: true
  head_sha:
    description: ref for current release or hotfix branch
    required: true

outputs:
  changed_components:
    description: changedccomponent list
    value: ${{ steps.detect.outputs.changed_components }}

runs:
  using: composite
  steps:
    - name: Fetch all references
      shell: bash
      run: |
        git fetch --all --tags --prune

    - name: Detect changed components
      id: detect-changed-components
      shell: bash
      run: |
        .github/scripts/release-detect-changed-components.sh "${{ inputs.base_sha }}" "${{ inputs.head_sha }}"
        echo "changed_components=$(tr '\n' ' ' < artifacts/changed-components.txt)" >> "$GITHUB_OUTPUT"

    - name: Build commit list of the release
      shell: bash
      run: |
        .github/scripts/release-generate-commit-lists.sh "${{ inputs.base_sha }}" "${{ inputs.head_sha }}"

    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: component-commit-lists
        path: artifacts