#!/bin/sh
#
# License:      GNU General Public License (GPL) 
# Support:      qgarnier@centreon.com
#
#	This script init cbd-central-broker
#
#	usage: $0 {start|stop|status|monitor|validate-all|meta-data}
#
#	The "start" start cbd-central-broker.
#
#	The "stop" stop cbd-central-broker
#
# OCF instance parameters:
#   OCF_RESKEY_binary
#   OCF_RESKEY_config
#   OCF_RESKEY_pid
#   OCF_RESKEY_masterdb_attr
#   OCF_RESKEY_masterdb_info
#   OCF_RESKEY_umask
#
#######################################################################
# Initialization:

: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
. /etc/centreon-failover/resources/functions-centreon

USAGE="usage: $0 {start|stop|status|monitor|validate-all|meta-data}";

OCF_RESKEY_binary_default="/usr/sbin/cbd"
OCF_RESKEY_config_default="/etc/centreon-broker/central-broker.json"
OCF_RESKEY_pid_default="/var/run/cbd-central-broker.pid"
OCF_RESKEY_user_default="centreon-broker"
OCF_RESKEY_masterdb_attr_default=""
OCF_RESKEY_masterdb_info_default=""
OCF_RESKEY_umask_default="0022"

: ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
: ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
: ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
: ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
: ${OCF_RESKEY_masterdb_attr=${OCF_RESKEY_masterdb_attr_default}}
: ${OCF_RESKEY_masterdb_info=${OCF_RESKEY_masterdb_info_default}}
: ${OCF_RESKEY_umask=${OCF_RESKEY_umask_default}}

#######################################################################

meta_data() {
        cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="cbd-central-broker">
<version>1.0</version>
<longdesc lang="en">
This script starts cbd-central-broker
</longdesc>
<shortdesc lang="en">Start cbd-central-broker daemon</shortdesc>

<parameters>

<parameter name="binary" unique="0" required="0">
<longdesc lang="en">
Location of the cbd-central-broker server binary
</longdesc>
<shortdesc lang="en">cbd-central-broker server binary</shortdesc>
<content type="string" default="${OCF_RESKEY_binary_default}" />
</parameter>

<parameter name="config" unique="0" required="0">
<longdesc lang="en">
Configuration file
</longdesc>
<shortdesc lang="en">cbd-central-broker config</shortdesc>
<content type="string" default="${OCF_RESKEY_config_default}" />
</parameter>

<parameter name="user" unique="0" required="0">
<longdesc lang="en">
User running cbd-central-broker daemon
</longdesc>
<shortdesc lang="en">cbd-central-broker user</shortdesc>
<content type="string" default="${OCF_RESKEY_user_default}" />
</parameter>

<parameter name="pid" unique="0" required="0">
<longdesc lang="en">
The pidfile to be used for cbd-central-broker.
</longdesc>
<shortdesc lang="en">cbd-central-broker pid file</shortdesc>
<content type="string" default="${OCF_RESKEY_pid_default}"/>
</parameter>

<parameter name="masterdb_attr" unique="0" required="0">
<longdesc lang="en">
The crm attribute to be used for master db access.
</longdesc>
<shortdesc lang="en">db master hostname crm attr</shortdesc>
<content type="string" default=""/>
</parameter>

<parameter name="masterdb_info" unique="0" required="0">
<longdesc lang="en">
Informations to put master db hostname:
/etc/centreon-failover/resources/central-broker-template.xml,__DBMASTER__
</longdesc>
<shortdesc lang="en">db master hostname info</shortdesc>
<content type="string" default=""/>
</parameter>

<parameter name="umask" unique="0" required="0">
<longdesc lang="en">
Umask settings value to be applied.
</longdesc>
<shortdesc lang="en">umask settings</shortdesc>
<content type="string" default="${OCF_RESKEY_umask_default}"/>
</parameter>

</parameters>

<actions>
<action name="start"   timeout="90s" />
<action name="stop"    timeout="90s" />
<action name="monitor" depth="0"  timeout="20s" interval="5s" />
<action name="validate-all"  timeout="20s" />
<action name="meta-data"  timeout="5s" />
</actions>
</resource-agent>
END
    exit $OCF_SUCCESS
}

cbdcentralborker_hup () {
    pidofproc_centreon "${OCF_RESKEY_binary}" "${OCF_RESKEY_config}"
    if [ "$PID_VALUES" ]; then
        if kill -s HUP $PID_VALUES; then
            ocf_log info "seng SIGHUP signal to reload cbd-central-broker process $PID_VALUES!"
        else
            ocf_log err "could not send SIGHUP to process $pid!"
            exit $OCF_ERR_GENERIC
        fi
    else
        ocf_log err "cbd-central-broker process not found!"
        exit $OCF_ERR_GENERIC
    fi
}

cbdcentralbroker_validate_all()
{
	check_binary $OCF_RESKEY_binary

	if [ ! -f $OCF_RESKEY_config ]; then
		ocf_log err "Config $OCF_RESKEY_config doesn't exist";
		return $OCF_ERR_INSTALLED
	fi

	if [ -n "${OCF_RESKEY_masterdb_attr}" ] ; then
		if [ -z "${OCF_RESKEY_masterdb_info}" ] ; then
			ocf_log err "Need to specify 'masterdb_info' param with 'masterdb_attr'";
			return $OCF_ERR_INSTALLED
		fi

		value1=$(echo ${OCF_RESKEY_masterdb_info} | cut -d , -f 1)
		value2=$(echo ${OCF_RESKEY_masterdb_info} | cut -d , -f 2)
		if [ -z "$value1" ] || [ -z "$value2" ] ; then
			ocf_log err "Param 'masterdb_info' not well formatted";
			return $OCF_ERR_INSTALLED
		fi
	fi

	return $OCF_SUCCESS
}

cbdcentralbroker_start()
{
	status_centreon -a "${OCF_RESKEY_config}" "${OCF_RESKEY_binary}"
	retval=$?
	if [ "$retval" -eq 0 ] ; then
		ocf_log err "cannot start cbd: already running.."
		exit $OCF_ERR_GENERIC
	fi

	# Move configuration file
	if [ -n "${OCF_RESKEY_masterdb_attr}" ] ; then
		master_db_hostname=$(${HA_SBIN_DIR}/crm_attribute --type crm_config --name "${OCF_RESKEY_masterdb_attr}" -q  2> /dev/null | cut -d '|' -f 1)
		config_template_name=$(echo "${OCF_RESKEY_masterdb_info}" | cut -d , -f 1)
		sedexpr=$(echo "${OCF_RESKEY_masterdb_info}" | cut -d , -f 2)
		cp -f "${config_template_name}" "${OCF_RESKEY_config}"
		sed -i "s/${sedexpr}/${master_db_hostname}/" "${OCF_RESKEY_config}"
	fi

	timeout=60
	if [ "$(id -u -n)" = "${OCF_RESKEY_user}" ] ; then
		daemon_centreon --check=${OCF_RESKEY_binary} ''${OCF_RESKEY_binary}' "'${OCF_RESKEY_config}'" > /dev/null 2>&1 &'
	else
		daemon_centreon --check=${OCF_RESKEY_binary} --user ${OCF_RESKEY_user} ''${OCF_RESKEY_binary}' "'${OCF_RESKEY_config}'" > /dev/null 2>&1 &'
	fi
	i=0
	while : ; do
		if [ "$i" -gt $timeout ] ; then
			ocf_log err "cbd not launched."
			return $OCF_ERR_GENERIC
		fi
		pidofproc_centreon "${OCF_RESKEY_binary}" "${OCF_RESKEY_config}"
		if [ -n "$PID_VALUES" ] ; then
			break
		fi
		sleep 1
		i=$(($i + 1))
	done
	echo $PID_VALUES > ${OCF_RESKEY_pid}
	ocf_log info "service cbd launched."
	return $OCF_SUCCESS
}


cbdcentralbroker_stop()
{
	timeout=60
	ocf_log info "stop cbd."
	if [ ! -e "${OCF_RESKEY_pid}" ] || [ -z "$(cat ${OCF_RESKEY_pid})" ] ; then
		killproc_centreon -d $timeout -a "${OCF_RESKEY_config}" "${OCF_RESKEY_binary}"
	else
		killproc_centreon -p "${OCF_RESKEY_pid}" -d $timeout -a "${OCF_RESKEY_config}" "${OCF_RESKEY_binary}"
	fi
	retval=$?
	ocf_log info "stop cbd $retval."
	if [ ${retval} -eq 0 ]; then
		return $OCF_SUCCESS
	fi
	return $OCF_ERR_GENERIC
}

cbdcentralbroker_status()
{
	status_centreon -a "${OCF_RESKEY_config}" "${OCF_RESKEY_binary}"
	retval=$?
	if [ ${retval} -eq 0 ]; then
		return $OCF_SUCCESS
	fi
	if [ "$retval" -eq 1 ] ; then
		ocf_log $1 "removing old PID file"
 		rm -f $OCF_RESKEY_pid
	fi
	return $OCF_NOT_RUNNING
}

cbdcentralbroker_monitor()
{
	local rc
	local status_loglevel="err"

	# Set loglevel to info during probe
	if ocf_is_probe; then
		status_loglevel="info"
	fi

	cbdcentralbroker_status $status_loglevel

	rc=$?
	return $rc
}

usage() {
    echo $USAGE >&2
    return $1
}

umask ${OCF_RESKEY_umask}

case $1 in
    meta-data)		meta_data;;
    start)		cbdcentralbroker_start;;
    stop)		cbdcentralbroker_stop;;
    status)		cbdcentralbroker_status err;;
    reload)		cbdcentralbroker_hup;;
    monitor)		cbdcentralbroker_monitor;; 
    validate-all)	cbdcentralbroker_validate_all;;
    usage)		usage $OCF_SUCCESS;;
    *)			usage $OCF_ERR_UNIMPLEMENTED;;
esac

exit $?
