/*
** Pipeline code.
*/

stage('Dependencies containers creation') {
    parallel 'debian 11 dependencies': {
        node {
            dir('centreon-widget-graph-monitoring-debian11') {
                checkout scm
                dir ('ci/docker') {
                    sh 'docker build --no-cache . -f Dockerfile.widget-debian11-dependencies -t registry.centreon.com/centreon-widget-debian11-dependencies:22.10'
                }
            }
        }
    }
}
