name: "release-sources"
description: "Release sources on download.centreon.com"
inputs:
  bucket_directory:
    description: The bucket directory
    required: true
  module_directory:
    description: The module directory
    required: true
  module_name:
    description: The module name
    required: true
  frontend_index_cache_key:
    description: The index.html cache key
  frontend_index_file:
    description: The index.html file path
  frontend_static_cache_key:
    description: The static directory cache key
  frontend_static_directory:
    description: The static directory
  backend_vendor_cache_key:
    description: The vendor directory cache key
  backend_vendor_directory:
    description: The vendor directory
  translation_cache_key:
    description: The translation directory cache key
  translation_directory:
    description: The translation directory
  major_version:
    description: The major version
    required: true
  minor_version:
    description: The minor version
    required: true
  token_download_centreon_com:
    description: The token to call download.centreon.com api
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup awscli
      run: |
        if ! command -v aws >/dev/null 2>&1; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip -q awscliv2.zip
          sudo ./aws/install
        fi
      shell: bash

    - name: Restore index file cache
      if: "${{ inputs.frontend_index_file != '' && inputs.frontend_index_cache_key != '' }}"
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ inputs.frontend_index_file }}
        key: ${{ inputs.frontend_index_cache_key }}
        fail-on-cache-miss: true

    - name: Restore static directory cache
      if: "${{ inputs.frontend_static_directory != '' && inputs.frontend_static_cache_key != '' }}"
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ inputs.frontend_static_directory }}
        key: ${{ inputs.frontend_static_cache_key }}
        fail-on-cache-miss: true

    - name: Restore vendor directory cache
      if: "${{ inputs.backend_vendor_directory != '' && inputs.backend_vendor_cache_key != '' }}"
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ inputs.backend_vendor_directory }}
        key: ${{ inputs.backend_vendor_cache_key }}
        fail-on-cache-miss: true

    - name: Restore translation directory cache
      if: "${{ inputs.translation_directory != '' && inputs.translation_cache_key != '' }}"
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ inputs.translation_directory }}
        key: ${{ inputs.translation_cache_key }}
        fail-on-cache-miss: true

    - env:
        MAJOR_VERSION: ${{ inputs.major_version }}
        MINOR_VERSION: ${{ inputs.minor_version }}
        MODULE_NAME: ${{ inputs.module_name }}
        MODULE_DIRECTORY: ${{ inputs.module_directory }}
        BUCKET_DIRECTORY: ${{ inputs.bucket_directory }}
        TOKEN_DOWNLOAD_CENTREON_COM: ${{ inputs.token_download_centreon_com }}
      run: |
        VERSION="$MAJOR_VERSION.$MINOR_VERSION"
        SRC_FILE="$MODULE_NAME-$VERSION.tar.gz"

        mv "$MODULE_DIRECTORY" "$MODULE_NAME-$VERSION"
        tar czf "$SRC_FILE" "$MODULE_NAME-$VERSION"

        SRC_HASH=$(md5sum "$SRC_FILE" | cut -d ' ' -f 1)
        SRC_SIZE=$(stat -c '%s' "$SRC_FILE")

        aws s3 cp --acl public-read "$SRC_FILE" "s3://centreon-download/public/$BUCKET_DIRECTORY/$SRC_FILE"
        curl --fail --get "https://download.centreon.com/api/" \
          --data-urlencode "token=$TOKEN_DOWNLOAD_CENTREON_COM" \
          --data-urlencode "product=$MODULE_NAME" \
          --data-urlencode "release=$MAJOR_VERSION" \
          --data-urlencode "version=$VERSION" \
          --data-urlencode "extension=tar.gz" \
          --data-urlencode "md5=$SRC_HASH" \
          --data-urlencode "size=$SRC_SIZE" \
          --data-urlencode "ddos=0" \
          --data-urlencode "dryrun=0"
      shell: bash
