#!/bin/bash
#
# Boot test for the centreon-centreontrapd / centreon-snmptrapd product Docker
# images. Starts the image standalone with default (out-of-the-box) settings
# and checks that the container boots cleanly, runs as the expected non-root
# user, and does not crash.
set -e

IMAGE="${IMAGE:?ERROR: IMAGE env var must be set to the image reference to test}"
COMPONENT="${COMPONENT:?ERROR: COMPONENT env var must be set (centreon-snmptrapd or centreon-centreontrapd)}"
PLATFORM="${PLATFORM:-}"
CONTAINER_NAME="${COMPONENT}-runtime-test-$$"
READY_TIMEOUT="${READY_TIMEOUT:-60}"
EXPECTED_UID=900 # centreon user, same on both images
SDB_FIXTURE_SQL=".github/docker/centreon-trapd/fixtures/centreontrapd-sdb.sql"
SDB_TMP=""

platform_args=()
if [ -n "$PLATFORM" ]; then
  platform_args=(--platform "$PLATFORM")
fi

run_args=()
if [ "$COMPONENT" = "centreon-snmptrapd" ]; then
  # snmptrapd binds UDP/162 as the non-root "centreon" (uid 900) user and
  # needs CAP_NET_BIND_SERVICE at runtime to do so (see the Dockerfile).
  run_args=(--cap-add=NET_BIND_SERVICE)
elif [ "$COMPONENT" = "centreon-centreontrapd" ]; then
  # Even in mode=1 (poller/SQLite), centreontrapd queries centreontrapd.sdb
  # for cfg_nagios.command_file on startup and crash-loops without at least
  # that table populated. In production this file is generated by
  # centreon/bin/generateSqlLite from the real MySQL config - seed a minimal
  # equivalent here.
  SDB_TMP=$(mktemp /tmp/centreontrapd-boot-test-XXXXXX.sdb)
  sqlite3 "$SDB_TMP" < "$SDB_FIXTURE_SQL"
  run_args=(-v "${SDB_TMP}:/etc/snmp/centreon_traps/centreontrapd.sdb")
fi

cleanup() {
  docker logs "$CONTAINER_NAME" > /tmp/centreon-trapd-boot-test.log 2>&1 || true
  docker rm -f "$CONTAINER_NAME" > /dev/null 2>&1 || true
  [ -n "$SDB_TMP" ] && rm -f "$SDB_TMP" || true
}
trap cleanup EXIT

# /tmp/docker.ready is touched by container.d/99-logs.sh, the last entrypoint
# script, right before the real daemon is exec'd.
wait_ready() {
  local container="$1" timeout="${2:-$READY_TIMEOUT}"
  for _ in $(seq 1 "$timeout"); do
    if docker exec "$container" test -f /tmp/docker.ready 2>/dev/null; then
      return 0
    fi
    sleep 1
  done
  echo "::error::$container did not report readiness (/tmp/docker.ready) within ${timeout}s"
  docker logs "$container" || true
  return 1
}

echo "=== [boot] Starting $IMAGE ${PLATFORM:+(platform: $PLATFORM)} ==="
docker run -d --name "$CONTAINER_NAME" "${platform_args[@]}" "${run_args[@]}" "$IMAGE"

echo "=== [boot] Waiting for /tmp/docker.ready (timeout: ${READY_TIMEOUT}s) ==="
wait_ready "$CONTAINER_NAME" || exit 1
echo "Container is ready."

echo "=== [boot] Checking container is still running ==="
running=$(docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME")
if [ "$running" != "true" ]; then
  echo "::error::$COMPONENT container is not running after startup"
  docker logs "$CONTAINER_NAME" || true
  exit 1
fi

echo "=== [boot] Checking non-root user (expected uid $EXPECTED_UID, centreon) ==="
uid=$(docker exec "$CONTAINER_NAME" id -u)
if [ "$uid" != "$EXPECTED_UID" ]; then
  echo "::error::$COMPONENT process runs as uid $uid, expected $EXPECTED_UID (centreon)"
  exit 1
fi

echo "=== [boot] Scanning logs for unambiguous crash signatures ==="
if docker logs "$CONTAINER_NAME" 2>&1 | grep -Ei "Compilation failed|Can't locate|Segmentation fault|Out of memory"; then
  echo "::error::$COMPONENT logs contain a crash signature, see above"
  exit 1
fi

echo "=== [boot] Stopping container (validates entrypoint cleanup) ==="
if ! docker stop "$CONTAINER_NAME" > /dev/null; then
  echo "::error::$COMPONENT container did not stop cleanly within the default timeout"
  exit 1
fi

echo "=== [boot] PASSED for $IMAGE ${PLATFORM:+(platform: $PLATFORM)} ==="
