#
# Section added by Centreon Install Setup
# Disabled by default. Will be enabled by the post-install script
# if gorgone was configured manually by the user to listen websocket connection on port 8086

ServerTokens Prod
Listen 8086
<VirtualHost *:8086>

    <IfModule mod_proxy_wstunnel.c>
        ProxyPass "/gorgone/pullwss/websocket"  "ws://127.0.0.1:8087/"
        ProxyPassReverse "/gorgone/pullwss/websocket"  "ws://127.0.0.1:8087/"
    </IfModule>
</VirtualHost>
