#
# Section added by Centreon Install Setup
# Disabled by default. Can be enabled by administrator if they already had activated pullwss in previous Centreon version
# if gorgone was configured manually by the user to listen websocket connection on port 8086

ServerTokens Prod
Listen 8086
<VirtualHost *:8086>

    <IfModule mod_proxy_wstunnel.c>
        ProxyPass "/gorgone/pullwss/websocket"  "ws://127.0.0.1:8087/"
        ProxyPassReverse "/gorgone/pullwss/websocket"  "ws://127.0.0.1:8087/"
        ProxyPass "/"  "ws://127.0.0.1:8087/"
        ProxyPassReverse "/"  "ws://127.0.0.1:8087/"
    </IfModule>
</VirtualHost>
