FROM debian:bullseye

# fix locale
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

RUN apt-get update && apt-get install -y \
dh-make \
dh-make-perl \
libtest-simple-perl \
libmodule-install-perl \
libnet-ldap-perl \
libauthen-simple-passwd-perl \
libmojolicious-perl \
aptitude \
lintian \
pbuilder \
quilt \
git-buildpackage \
debmake \
devscripts \
fakeroot \
curl \
python3
