FROM debian:trixie AS web_dependencies

ARG MAJOR_VERSION
ARG PHP_VERSION=8.4
ARG STABILITY
ARG IS_CLOUD

ENV DEBIAN_FRONTEND=noninteractive

RUN bash -e <<EOF

######################################
# additional configuration for apt   #
######################################

echo '
Acquire::Retries "10";
Acquire::https::Timeout "300";
Acquire::http::Timeout "300";
APT::Install-Recommends "false";
APT::Install-Suggests "false";
' > /etc/apt/apt.conf.d/99custom

######################################
# install and configure repositories #
######################################

apt-get update

apt-get install -y wget gnupg2 ca-certificates

VERSION_CODENAME=\$(
  . /etc/os-release
  echo \$VERSION_CODENAME
)

if [[ "${PHP_VERSION}" != "8.4" ]]; then
  echo "deb https://packages.sury.org/php/ \$VERSION_CODENAME main" | tee /etc/apt/sources.list.d/sury-php.list
  wget -O- https://packages.sury.org/php/apt.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/php.gpg  > /dev/null 2>&1
fi

if [[ "${IS_CLOUD}" == "true" ]]; then
  echo "deb https://packages.centreon.com/apt-standard-internal/ \$VERSION_CODENAME-${MAJOR_VERSION}-unstable main" | tee -a /etc/apt/sources.list.d/centreon-unstable.list
else
  echo "deb https://packages.centreon.com/apt-standard/ \$VERSION_CODENAME-${MAJOR_VERSION}-stable main" | tee -a /etc/apt/sources.list.d/centreon-stable.list
  echo "deb https://packages.centreon.com/apt-standard/ \$VERSION_CODENAME-${MAJOR_VERSION}-testing-hotfix main" | tee -a /etc/apt/sources.list.d/centreon-testing.list
  echo "deb https://packages.centreon.com/apt-standard/ \$VERSION_CODENAME-${MAJOR_VERSION}-testing-release main" | tee -a /etc/apt/sources.list.d/centreon-testing.list
  echo "deb https://packages.centreon.com/apt-standard/ \$VERSION_CODENAME-${MAJOR_VERSION}-unstable main" | tee -a /etc/apt/sources.list.d/centreon-unstable.list
fi
echo "deb https://packages.centreon.com/apt-plugins-stable/ \$VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-plugins-stable.list
echo "deb https://packages.centreon.com/apt-plugins-testing/ \$VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-plugins-testing.list
echo "deb https://packages.centreon.com/apt-plugins-unstable/ \$VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-plugins-unstable.list
wget -O- https://apt-key.centreon.com/ | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1

if [[ "$STABILITY" == "testing" ]]; then
  for i in \$( ls /etc/apt/sources.list.d/centreon*unstable* ); do mv \$i \$i.disabled; done
elif [[ "$STABILITY" == "stable" ]]; then
  for i in \$( ls /etc/apt/sources.list.d/centreon*{unstable,testing}* ); do mv \$i \$i.disabled; done
fi

apt-get update

#############################
# install base dependencies #
#############################

apt-get install -y \
  apache2 \
  apt-transport-https \
  curl \
  jq \
  python3 \
  sed \
  snmpd \
  cron \
  systemd \
  systemd-sysv \
  sudo

#############################
# install perl dependencies #
#############################

apt-get install -y \
  libdbi-perl \
  libnet-curl-perl \
  libnet-http-perl \
  libwww-perl \
  libxml-libxml-perl \
  perl-base

#############################
# install test dependencies #
#############################

apt-get install -y faketime

############################
# install php dependencies #
############################

apt-get install -y \
  php${PHP_VERSION}-common \
  php${PHP_VERSION}-cli \
  php${PHP_VERSION}-pdo \
  php${PHP_VERSION}-mysqlnd \
  php${PHP_VERSION}-gd \
  php${PHP_VERSION}-xml \
  php${PHP_VERSION}-mbstring \
  php${PHP_VERSION}-ldap \
  php${PHP_VERSION}-snmp \
  php${PHP_VERSION}-intl \
  php${PHP_VERSION}-fpm \
  php${PHP_VERSION}-curl \
  php${PHP_VERSION}-zip

###################
# install plugins #
###################

apt-get install -y centreon-plugin-operatingsystems-linux-snmp

######################
# SNMP configuration #
######################

sed -i '/^agentaddress/d' /etc/snmp/snmpd.conf
echo 'agentaddress  127.0.0.1' >> /etc/snmp/snmpd.conf
sed -i 's/^rocommunity[[:space:]]*public.*/rocommunity  public default -V centreon/' /etc/snmp/snmpd.conf

apt-get clean

EOF

ENV PHP_VERSION=${PHP_VERSION}

COPY --chmod=755 ./.github/docker/centreon-web/init/systemctl /usr/bin/systemctl
COPY --chmod=755 ./.github/docker/centreon-web/init/journalctl /usr/bin/journalctl

COPY --chmod=755 ./.github/docker/centreon-web/init/* /etc/init.d/

FROM web_dependencies AS web_dependencies_collect

ARG COLLECT_MINOR_VERSION
ARG COMMON_MINOR_VERSION
ARG GORGONE_MINOR_VERSION
ARG MAJOR_VERSION
ARG STABILITY

RUN bash -e <<EOF

apt-get update

if [[ "$STABILITY" == "stable" ]]; then
  apt-get install -y \
    centreon-common=${MAJOR_VERSION}.${COMMON_MINOR_VERSION}-*+deb13u1 \
    centreon-gorgone-centreon-config-${MAJOR_VERSION}.${GORGONE_MINOR_VERSION}-*+deb13u1 \
    centreon-gorgone=${MAJOR_VERSION}.${GORGONE_MINOR_VERSION}-*+deb13u1 \
    centreon-clib=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-engine=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-engine-daemon=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-engine-opentelemetry=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-broker=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-broker-core=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-broker-cbd=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-broker-graphite=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-broker-influxdb=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-connector-perl=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-connector-ssh=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1 \
    centreon-connector=${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}-*+deb13u1
else
  apt-get install -y \
    centreon-common \
    centreon-gorgone-centreon-config \
    centreon-gorgone \
    centreon-engine \
    centreon-broker-cbd \
    centreon-broker-graphite \
    centreon-broker-influxdb \
    centreon-connector
fi

apt-get clean

EOF
