gorgoned                        usr/bin
contrib/*                       usr/sbin
packaging/config.yaml           etc/centreon-gorgone
debian/extra/gorgoned.service   lib/systemd/system
debian/extra/gorgoned           etc/default
gorgone/class/*                 usr/share/perl5/gorgone/class
gorgone/modules/*               usr/share/perl5/gorgone/modules
gorgone/standard/*              usr/share/perl5/gorgone/standard
