name: "package-delivery"
description: "Deliver rpm and deb packages to pulp"
inputs:
  module_name:
    description: "The package module name"
    required: true
  distrib:
    description: "The distribution used for packaging"
    required: true
  version:
    description: "Centreon packaged major version"
    required: true
  cache_key:
    description: "The cached package key"
    required: true
  stability:
    description: "The package stability (stable, testing, unstable)"
    required: true
  release_type:
    description: "Type of release (hotfix, release)"
    required: false
    default: ""
  is_cloud:
    description: "Release context (cloud or not cloud)"
    required: true
  delivery_type:
    description: "Delivery to feature or standard repository"
    required: false
    default: "standard"
  pulp_url:
    description: "The pulp server api url"
    required: false
    default: "https://pulp.dev.centreon.io"
  pulp_content_url:
    description: "The pulp server content url"
    required: false
    default: "https://pulp.dev.centreon.io/pulp/content"
  pulp_username:
    description: "The pulp server username"
    required: true
  pulp_password:
    description: "The pulp server password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse distrib name
      id: parse-distrib
      uses: ./.github/actions/parse-distrib
      with:
        distrib: ${{ inputs.distrib }}

    - name: Compute pulp repository properties
      id: pulp-properties
      shell: bash
      env:
        MODULE_NAME: ${{ inputs.module_name }}
        DISTRIB: ${{ inputs.distrib }}
        DISTRIB_FAMILY: ${{ steps.parse-distrib.outputs.distrib_family }}
        VERSION: ${{ inputs.version }}
        STABILITY: ${{ inputs.stability }}
        RELEASE_TYPE: ${{ inputs.release_type }}
        IS_CLOUD: ${{ inputs.is_cloud }}
        DELIVERY_TYPE: ${{ inputs.delivery_type }}
        GH_HEAD_REF: ${{ github.head_ref || github.ref_name }}
      run: ${{ github.action_path }}/compute-properties.sh

    - name: Restore packages from cache
      if: steps.pulp-properties.outputs.skip_delivery == 'false'
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ./*.${{ steps.parse-distrib.outputs.package_extension }}
        key: ${{ inputs.cache_key }}
        fail-on-cache-miss: true

    - name: Setup pulp-cli
      if: steps.pulp-properties.outputs.skip_delivery == 'false'
      uses: ./.github/actions/setup-pulp-cli
      with:
        pulp_url: ${{ inputs.pulp_url }}
        pulp_username: ${{ inputs.pulp_username }}
        pulp_password: ${{ inputs.pulp_password }}

    - name: Deliver RPM packages
      if: steps.parse-distrib.outputs.package_extension == 'rpm' && steps.pulp-properties.outputs.skip_delivery == 'false'
      shell: bash
      env:
        REPOSITORY_PREFIX: ${{ steps.pulp-properties.outputs.repository_prefix }}
        BASE_PATH_PREFIX: ${{ steps.pulp-properties.outputs.base_path_prefix }}
        TRACKING_REPOSITORY_NAME: ${{ steps.pulp-properties.outputs.tracking_repository_name }}
        PULP_CONTENT_URL: ${{ inputs.pulp_content_url }}
      run: ${{ github.action_path }}/deliver-rpm.sh

    - name: Deliver DEB packages
      if: steps.parse-distrib.outputs.package_extension == 'deb' && steps.pulp-properties.outputs.skip_delivery == 'false'
      shell: bash
      env:
        REPOSITORY_NAME: ${{ steps.pulp-properties.outputs.repository_name }}
        BASE_PATH: ${{ steps.pulp-properties.outputs.base_path }}
        SUITE: ${{ steps.pulp-properties.outputs.suite }}
        TRACKING_REPOSITORY_NAME: ${{ steps.pulp-properties.outputs.tracking_repository_name }}
        PULP_CONTENT_URL: ${{ inputs.pulp_content_url }}
      run: ${{ github.action_path }}/deliver-deb.sh
