name: "promote testing to stable"
description: "Promote testing packages to stable."
inputs:
  artifactory_token:
    description: "Artifactory token"
    required: true
  module_name:
    description: "Module name"
    required: true
  distrib:
    description: "The distribution used for packaging"
    required: true
  major_version:
    description: "Centreon packaged major version"
    required: true
  minor_version:
    description: "Centreon package minor version"
    required: true
  stability:
    description: "The package stability (stable, testing, unstable)"
    required: true
  github_ref_name:
    description: "Release base ref name for push event"
    required: true
  release_type:
    description: "Type of release (hotfix, release)"
    required: true
  is_cloud:
    description: "Release context (cloud or not cloud)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        RELEASE_TYPE: ${{ inputs.release_type }}
      with:
        script: |
          if (! ['release', 'hotfix'].includes(process.env.RELEASE_TYPE)) {
            throw new Error('release_type input must be defined (release or hotfix)');
          }

    - uses: jfrog/setup-jfrog-cli@1641575d87647fb969c0545f0b6a76873e328b7c # v5.0.0
      env:
        JF_URL: https://packages.centreon.com
        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}

    - name: Parse distrib name
      id: parse-distrib
      uses: ./.github/actions/parse-distrib
      with:
        distrib: ${{ inputs.distrib }}

    - name: Promote RPM packages to stable
      if: ${{ steps.parse-distrib.outputs.package_extension == 'rpm' }}
      env:
        MAJOR_VERSION: ${{ inputs.major_version }}
        MINOR_VERSION: ${{ inputs.minor_version }}
        DISTRIB: ${{ inputs.distrib }}
        IS_CLOUD: ${{ inputs.is_cloud }}
        RELEASE_TYPE: ${{ inputs.release_type }}
        STABILITY: ${{ inputs.stability }}
        MODULE_NAME: ${{ inputs.module_name }}
        ARTIFACTORY_TOKEN: ${{ inputs.artifactory_token }}
      run: |
        set -eux

        # DEBUG
        echo "[DEBUG] - Major version: $MAJOR_VERSION"
        echo "[DEBUG] - Minor version: $MINOR_VERSION"
        echo "[DEBUG] - Distrib: $DISTRIB"
        echo "[DEBUG] - is_cloud: $IS_CLOUD"
        echo "[DEBUG] - release_type: $RELEASE_TYPE"
        echo "[DEBUG] - stability: $STABILITY"

        # Cloud specific promote
        # delivery by default to onprem, override to internal if is_cloud is true
        if [[ "$IS_CLOUD" == "true" ]]; then
          ROOT_REPO_PATH="rpm-standard-internal"
        else
          ROOT_REPO_PATH="rpm-standard"
        fi

        # Search for testing packages candidate for promote
        for ARCH in "noarch" "x86_64"; do
          SEARCH_REPO_PATH="$MAJOR_VERSION/$DISTRIB/testing-$RELEASE_TYPE/$ARCH/$MODULE_NAME"

          echo "[DEBUG] - Get path of $ARCH testing artifacts to promote to stable."
          SRC_PATHS=$(jf rt search --include-dirs "$ROOT_REPO_PATH/$SEARCH_REPO_PATH/*.rpm" | jq -r '.[].path')

          if [[ ${SRC_PATHS[@]} ]]; then
            for SRC_PATH in ${SRC_PATHS[@]}; do
              echo "[DEBUG] - Source path found: $SRC_PATH"
            done
          else
            echo "[DEBUG] - No source path found."
            continue
          fi

          # Build target path based on ARCH
          echo "[DEBUG] - Build $ARCH target path."
          TARGET_PATH="$ROOT_REPO_PATH/$MAJOR_VERSION/$DISTRIB/stable/$ARCH/RPMS/$MODULE_NAME/"
          echo "[DEBUG] - Target path: $TARGET_PATH"

          # Download candidates for promote
          echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
          for ARTIFACT in ${SRC_PATHS[@]}; do
            echo "[DEBUG] - Downloading $ARTIFACT from TESTING."
            jf rt download "$ARTIFACT" --flat
          done

          DRY_RUN_FLAG="--dry-run"
          if [ "$STABILITY" == "stable" ]; then
            DRY_RUN_FLAG=""
          fi

          # Upload previously downloaded candidates to TARGET_PATH
          for ARTIFACT_DL in $(find . -maxdepth 1 -type f -name '*.rpm' -printf '%f\n'); do
            echo "[DEBUG] - Promoting (upload) $ARTIFACT_DL to stable $TARGET_PATH."
            jf rt upload "$ARTIFACT_DL" "$TARGET_PATH" --flat $DRY_RUN_FLAG
          done

          if [ "$STABILITY" == "stable" ]; then
            curl -H "Authorization: Bearer $ARTIFACTORY_TOKEN" -X POST "https://centreon.jfrog.io/artifactory/api/yum/$ROOT_REPO_PATH?path=/$MAJOR_VERSION/$DISTRIB/stable/$ARCH&async=1"
          fi

          # Cleanup before next round of candidates
          rm -f *.rpm
        done

      shell: bash

    - name: Promote DEB packages to stable
      if: ${{ steps.parse-distrib.outputs.package_extension == 'deb' && inputs.is_cloud == 'false' }}
      env:
        MAJOR_VERSION: ${{ inputs.major_version }}
        MINOR_VERSION: ${{ inputs.minor_version }}
        DISTRIB: ${{ inputs.distrib }}
        IS_CLOUD: ${{ inputs.is_cloud }}
        RELEASE_TYPE: ${{ inputs.release_type }}
        STABILITY: ${{ inputs.stability }}
        MODULE_NAME: ${{ inputs.module_name }}
        ARTIFACTORY_TOKEN: ${{ inputs.artifactory_token }}
        DISTRIB_FAMILY: ${{ steps.parse-distrib.outputs.distrib_family }}
        PACKAGE_DISTRIB_NAME: ${{ steps.parse-distrib.outputs.package_distrib_name }}
      run: |
        set -eux

        echo "[DEBUG] - Major version: $MAJOR_VERSION"
        echo "[DEBUG] - Minor version: $MINOR_VERSION"
        echo "[DEBUG] - Distrib: $DISTRIB"

        # Define ROOT_REPO_PATH for debian
        # There is no cloud ROOT_REPO_PATH for debian, only onprem
        # Should there be a need to deploy debian to cloud repositories, please use the same condition as RPM promotion
        ROOT_REPO_PATH_PREFIX=""
        if [[ "$DISTRIB_FAMILY" == "debian" ]]; then
          ROOT_REPO_PATH_PREFIX="apt-"
        elif [[ "$DISTRIB_FAMILY" == "ubuntu" ]]; then
          ROOT_REPO_PATH_PREFIX="ubuntu-"
        else
          echo "::error::Unsupported distribution family: $DISTRIB_FAMILY"
          exit 1
        fi

        SOURCE_ROOT_REPO_PATH_SUFFIX=""
        TARGET_ROOT_REPO_PATH_SUFFIX=""
        if [[ "$IS_CLOUD" == "true" ]]; then
          SOURCE_ROOT_REPO_PATH_SUFFIX="-internal"
          TARGET_ROOT_REPO_PATH_SUFFIX="-internal"
        elif [[ "$MAJOR_VERSION" < "25.05" ]]; then
          TARGET_ROOT_REPO_PATH_SUFFIX="-$MAJOR_VERSION-stable"
        fi

        SOURCE_ROOT_REPO_PATH="${ROOT_REPO_PATH_PREFIX}standard${SOURCE_ROOT_REPO_PATH_SUFFIX}"
        TARGET_ROOT_REPO_PATH="${ROOT_REPO_PATH_PREFIX}standard${TARGET_ROOT_REPO_PATH_SUFFIX}"

        echo "[DEBUG] - Get path of testing DEB packages to promote to stable."

        case "$MAJOR_VERSION" in
          "22.10"|"23.10")
            SEARCH_PATTERN="*.deb"
            ;;
          *)
            SEARCH_PATTERN="*${PACKAGE_DISTRIB_NAME}*.deb"
            ;;
        esac

        SRC_PATHS=$(jf rt search --include-dirs "$SOURCE_ROOT_REPO_PATH/pool/$MAJOR_VERSION/testing/$RELEASE_TYPE/$MODULE_NAME/${SEARCH_PATTERN}" | jq -r '.[].path')

        if [[ ${SRC_PATHS[@]} ]]; then
          for SRC_PATH in ${SRC_PATHS[@]}; do
            echo "[DEBUG] - Source path found: $SRC_PATH"
          done
        else
          echo "::error::Nothing to promote."
          exit 1
        fi

        echo "[DEBUG] - Promoting DEB testing artifacts to stable."
        for ARTIFACT in ${SRC_PATHS[@]}; do
          echo "[DEBUG] - Downloading $ARTIFACT from TESTING."
          jf rt download "$ARTIFACT" --flat
        done

        DRY_RUN_FLAG="--dry-run"
        if [ "$STABILITY" == "stable" ]; then
          DRY_RUN_FLAG=""
        fi

        for ARTIFACT_DL in $(find . -maxdepth 1 -type f -name '*.deb' -printf '%f\n'); do
          ARCH=$(echo "$ARTIFACT_DL" | cut -d '_' -f3 | cut -d '.' -f1)
          if [[ "$MAJOR_VERSION" < "25.05" ]]; then
            POOL_SUBPATH="$MODULE_NAME"
            DEB_PROP="$DISTRIB/main/$ARCH"
          else
            POOL_SUBPATH="$MAJOR_VERSION/$STABILITY/$MODULE_NAME"
            DEB_PROP="$DISTRIB-$MAJOR_VERSION-$STABILITY/main/$ARCH"
          fi
          TARGET_PATH="$TARGET_ROOT_REPO_PATH/pool/${POOL_SUBPATH}/"

          echo "[DEBUG] - Promoting (upload) $ARTIFACT_DL to stable $TARGET_PATH."
          jf rt upload "$ARTIFACT_DL" "$TARGET_PATH" --deb "${DEB_PROP}" --detailed-summary --flat $DRY_RUN_FLAG
        done

        if [ "$STABILITY" == "stable" ]; then
          curl -H "Authorization: Bearer $ARTIFACTORY_TOKEN" -X POST "https://centreon.jfrog.io/artifactory/api/deb/reindex/$TARGET_ROOT_REPO_PATH?async=1"
        fi

        rm -f *.deb
      shell: bash
