name: "promote testing to stable"
description: "Promote testing packages to stable."
inputs:
  module_name:
    description: "Module name"
    required: true
  distrib:
    description: "The distribution used for packaging"
    required: true
  major_version:
    description: "Centreon packaged major version"
    required: true
  stability:
    description: "The package stability (stable, testing, unstable)"
    required: true
  release_type:
    description: "Type of release (hotfix, release)"
    required: true
  is_cloud:
    description: "Release context (cloud or not cloud)"
    required: true
  pulp_url:
    description: "The pulp server api url"
    required: false
    default: "https://pulp.dev.centreon.io"
  pulp_content_url:
    description: "The pulp server content url"
    required: false
    default: "https://pulp.dev.centreon.io/pulp/content"
  pulp_username:
    description: "The pulp server username"
    required: true
  pulp_password:
    description: "The pulp server password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      env:
        RELEASE_TYPE: ${{ inputs.release_type }}
      run: |
        set -euo pipefail

        if [[ "$RELEASE_TYPE" != "release" && "$RELEASE_TYPE" != "hotfix" ]]; then
          echo "::error::release_type input must be defined (release or hotfix)"
          exit 1
        fi

    - name: Parse distrib name
      id: parse-distrib
      uses: ./.github/actions/parse-distrib
      with:
        distrib: ${{ inputs.distrib }}

    - name: Setup pulp-cli
      uses: ./.github/actions/setup-pulp-cli
      with:
        pulp_url: ${{ inputs.pulp_url }}
        pulp_username: ${{ inputs.pulp_username }}
        pulp_password: ${{ inputs.pulp_password }}

    - name: Compute pulp repository properties
      id: pulp-properties
      shell: bash
      env:
        MODULE_NAME: ${{ inputs.module_name }}
        DISTRIB: ${{ inputs.distrib }}
        DISTRIB_FAMILY: ${{ steps.parse-distrib.outputs.distrib_family }}
        MAJOR_VERSION: ${{ inputs.major_version }}
        RELEASE_TYPE: ${{ inputs.release_type }}
        IS_CLOUD: ${{ inputs.is_cloud }}
      run: ${{ github.action_path }}/compute-properties.sh

    - name: Promote RPM packages to stable
      if: steps.parse-distrib.outputs.package_extension == 'rpm'
      shell: bash
      env:
        TRACKING_REPOSITORY_NAME: ${{ steps.pulp-properties.outputs.tracking_repository_name }}
        STABLE_REPOSITORY_PREFIX: ${{ steps.pulp-properties.outputs.stable_repository_prefix }}
        STABLE_BASE_PATH_PREFIX: ${{ steps.pulp-properties.outputs.stable_base_path_prefix }}
        STABILITY: ${{ inputs.stability }}
        PULP_CONTENT_URL: ${{ inputs.pulp_content_url }}
      run: ${{ github.action_path }}/promote-rpm.sh

    - name: Promote DEB packages to stable
      if: steps.parse-distrib.outputs.package_extension == 'deb'
      shell: bash
      env:
        TRACKING_REPOSITORY_NAME: ${{ steps.pulp-properties.outputs.tracking_repository_name }}
        REPOSITORY_NAME: ${{ steps.pulp-properties.outputs.repository_name }}
        BASE_PATH: ${{ steps.pulp-properties.outputs.base_path }}
        STABLE_SUITE: ${{ steps.pulp-properties.outputs.stable_suite }}
        STABILITY: ${{ inputs.stability }}
        PULP_CONTENT_URL: ${{ inputs.pulp_content_url }}
      run: ${{ github.action_path }}/promote-deb.sh
