FROM registry-docker.centreon.com/docker-global/debian:bullseye

RUN <<EOF

apt-get update
apt-get install -y locales
rm -rf /var/lib/apt/lists/*
localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
apt-get clean

EOF

ENV LANG en_US.utf8

RUN <<EOF

apt-get update
apt-get install -y \
  dh-make \
  dh-make-perl \
  libtest-simple-perl \
  libmodule-install-perl \
  aptitude \
  lintian \
  pbuilder \
  quilt \
  git-buildpackage \
  debmake \
  devscripts \
  fakeroot \
  curl \
  python3 \
  python3-pip \
  lsb-release \
  ca-certificates \
  apt-transport-https \
  software-properties-common \
  wget

echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/sury-php.list
wget -qO /etc/apt/trusted.gpg.d/sury-php.gpg https://packages.sury.org/php/apt.gpg

apt-get update
apt-get -y install php8.1 php8.1-intl php8.1-xml php8.1-curl php8.1-mbstring php8.1-zip php8.1-cli php8.1-common php8.1-fpm php8.1-mysql php8.1-ldap

apt-get clean

EOF

WORKDIR /src
