FROM centos:7

ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum -y update
RUN yum install -y libselinux-utils
RUN curl -o centreon-release.rpm "https://yum.centreon.com/standard/22.10/el8/stable/noarch/RPMS/centreon-release-22.10-1.el8.noarch.rpm"

COPY *.rpm /tmp/
COPY ./ci/scripts/install.sh /tmp/install.sh
COPY /ci/scripts/autoinstall.php /usr/share/centreon/autoinstall.php
COPY /ci/scripts/configuration/* /usr/share/centreon/www/install/tmp/
RUN yum install /tmp/*.rpm
VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
