FROM docker-proxy.registry.apps.centreon.com/centos:7

# ENV container docker

# RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
# rm -f /lib/systemd/system/multi-user.target.wants/*;\
# rm -f /etc/systemd/system/*.wants/*;\
# rm -f /lib/systemd/system/local-fs.target.wants/*; \
# rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
# rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
# rm -f /lib/systemd/system/basic.target.wants/*;\
# rm -f /lib/systemd/system/anaconda.target.wants/*;

# RUN curl -o centreon-release.rpm "https://yum.centreon.com/standard/22.10/el7/stable/noarch/RPMS/centreon-release-22.10-1.el7.centos.noarch.rpm"
# RUN yum -y update && yum install -y libselinux-utils --nogpgcheck centreon-release.rpm yum-utils centos-release-scl-rh \
#     https://rpms.remirepo.net/enterprise/remi-release-7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm httpd24-httpd
# RUN yum-config-manager --enable 'centreon-testing*' && yum-config-manager --enable 'centreon-unstable*' --enable remi-php80

COPY *.rpm /tmp/
COPY ./ci/scripts/run-centreon-open-source-centos7/ /tmp/fresh

# Install Centreon software.
RUN yum clean all && \
    yum install -y /tmp/rpms/centreon-*.rpm centreon-broker-cbd centreon-broker-influxdb libfaketime && \
    cp /tmp/fresh/centengine.sh /etc/init.d/centengine && \
    cp /tmp/fresh/cbd.sh /etc/init.d/cbd && \
    chmod +x /etc/init.d/centengine /etc/init.d/cbd && \
    cp /tmp/fresh/autoinstall.php /usr/share/centreon/autoinstall.php && \
    cp /tmp/fresh/configuration/* /usr/share/centreon/www/install/tmp/ && \
    chown -R apache.apache /usr/share/centreon/www/install/tmp && \
    chmod +x /tmp/fresh/install.sh && \
    touch /var/log/php-fpm/centreon-error.log && \
    chown apache:apache /var/log/php-fpm/centreon-error.log && \
    cp -r /tmp/fresh/run /usr/share/centreon/container.d && \
    /tmp/fresh/install.sh && \
    cp /tmp/fresh/run.sh /usr/share/centreon/container.sh && \
    chmod +x /usr/share/centreon/container.sh && \
    yum clean all && \
    rm -rf /tmp/fresh

# COPY ./ci/scripts/centengine.sh /tmp/centengine.sh
# COPY ./ci/scripts/cbd.sh /tmp/cbd.sh
# COPY ./ci/scripts/install.sh /tmp/install.sh
# COPY ./ci/scripts/autoinstall.php /tmp/autoinstall.php
# COPY ./ci/scripts/configuration/ /tmp/configuration/
# COPY ./ci/scripts/run/ /tmp/run/
# COPY ./ci/scripts/run.sh /tmp/run.sh

# RUN chmod +x /tmp/install.sh

# COPY ./ci/scripts/sql/standard.sql /tmp/standard.sql
# COPY ./ci/scripts/sql/media.sql /tmp/media.sql
# COPY ./ci/scripts/sql/openldap.sql /tmp/openldap.sql
# COPY ./ci/scripts/insert-standard-fixtures.sh /tmp/insert-standard-fixtures.sh
RUN chmod +x /tmp/insert-standard-fixtures.sh

ENV CENTREON_IMP_SERVER HELLOWORLD:http://ci.int.centreon.com:3000
COPY web/22.10/php-fpm/centreon-license-manager.conf /etc/php-fpm.d/centreon-license-manager.conf

ENTRYPOINT ["/usr/share/centreon/container.sh"]

# VOLUME [ "/sys/fs/cgroup" ]

# CMD ["/usr/sbin/init"]
