FROM docker-proxy.registry.apps.centreon.com/debian:bullseye
RUN apt-get -y update && \
    apt-get -y install cmake \ 
    curl \
    gcc \
    g++ \
    pkg-config \
    ninja-build \
    libmariadb3 \
    librrd-dev \
    libgnutls28-dev \
    ninja-build \
    liblua5.3-dev \
    python3 \
    python3-pip \
    libperl-dev \
    libgcrypt20-dev \
    dh-make \
    aptitude \
    lintian \
    pbuilder \
    quilt \
    git-buildpackage \
    debmake \
    git \
    wget \
    curl \
    gettext \
    php \
    php-cli \
    php-dom \
    php-mbstring \
    php-intl \
    php-pdo \
    php-curl \
    tar \
    devscripts \
    fakeroot \
    locales && \
    rm -rf /var/lib/apt/lists/* && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 
RUN RUN curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash - && \
    apt-get -y update && \
    apt-get -y install nodejs
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    chmod +x /usr/local/bin/composer
WORKDIR /src