FROM registry-docker.centreon.com/docker-global/centos:7

RUN <<EOF

curl -o centreon-devel.rpm "https://yum.centreon.com/standard/22.10/el7/stable/noarch/RPMS/centreon-devel-2-2.el7.centos.noarch.rpm"
yum install -y --nogpgcheck -y centreon-devel.rpm

yum install -y rpm-build git composer wget gettext yum-utils  https://rpms.remirepo.net/enterprise/remi-release-7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

yum-config-manager --enable remi-php81
yum install -y php81
ln -s /usr/bin/php81 /usr/bin/php

yum install -y dos2unix php-cli php-dom php-mbstring php-intl php-pdo

yum clean all

EOF

WORKDIR /src
