FROM docker-proxy.registry.apps.centreon.com/centos:7

RUN mkdir /tmp/rpms-centreon
COPY *.rpm /tmp/rpms-centreon/

#RUN <<EOF

RUN yum install -y centos-release-scl

RUN curl -o remi-release-7.rpm https://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum install -y remi-release-7.rpm
RUN rm -f remi-release-7.rpm
RUN yum-config-manager --enable remi-php81

RUN curl -o /tmp/mariadb_repo_setup -JO https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
RUN bash /tmp/mariadb_repo_setup
RUN sed -ri 's/10\../10.5/' /etc/yum.repos.d/mariadb.repo
RUN rm -f /tmp/mariadb_repo_setup
RUN yum install -y MariaDB-server MariaDB-client

RUN curl -o centreon-release.rpm "https://yum.centreon.com/standard/22.10/el7/stable/noarch/RPMS/centreon-release-22.10-1.el7.centos.noarch.rpm"
RUN yum install -y centreon-release.rpm
RUN rm -f centreonrelease-.rpm
RUN yum-config-manager --enable 'centreon-testing*'
RUN yum-config-manager --enable 'centreon-unstable*'

RUN rm -f /tmp/rpms-centreon/centreon-22.10*.rpm /tmp/rpms-centreon/centreon-central-22.10*.rpm
RUN yum install -y /tmp/rpms-centreon/centreon-*.rpm centreon-broker-cbd centreon-broker-influxdb libfaketime

RUN touch /var/log/php-fpm/centreon-error.log
RUN chown apache:apache /var/log/php-fpm/centreon-error.log

RUN yum clean all

#EOF

COPY --chmod=+x ./ci/scripts/init/* /etc/init.d/
COPY --chmod=+x ./ci/scripts/autoinstall.php /usr/share/centreon/
COPY --chown=apache:apache ./ci/scripts/configuration /usr/share/centreon/www/install/tmp/

#RUN <<EOF

RUN chmod +x /etc/init.d/*
RUN <<EOF
/etc/init.d/mysql start
mysql -e "GRANT ALL ON *.* to 'root'@'localhost' IDENTIFIED BY 'centreon' WITH GRANT OPTION"
cd /usr/share/centreon/www/install/steps/process
su apache -s /bin/bash -c "php configFileSetup.php"
su apache -s /bin/bash -c "php installConfigurationDb.php"
su apache -s /bin/bash -c "php installStorageDb.php"
su apache -s /bin/bash -c "php createDbUser.php"
su apache -s /bin/bash -c "SERVER_ADDR='127.0.0.1' php insertBaseConf.php"
su apache -s /bin/bash -c "php partitionTables.php"
su apache -s /bin/bash -c "php generationCache.php"
rm -rf /usr/share/centreon/www/install
mysql -pcentreon -e "GRANT ALL ON *.* to 'root'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION"
mysql -e "GRANT ALL ON *.* to 'root'@'%' IDENTIFIED BY 'centreon' WITH GRANT OPTION"
centreon -d -u admin -p Centreon\!2021 -a POLLERGENERATE -v 1
centreon -d -u admin -p Centreon\!2021 -a CFGMOVE -v 1
service mysql stop

EOF

COPY ./ci/scripts/sql /tmp/

RUN <<EOF

service mysql start
mysql centreon < /tmp/sql/standard.sql
mysql centreon < /tmp/sql/media.sql
mysql centreon < /tmp/sql/openldap.sql
centreon -u admin -p Centreon\!2021 -a APPLYCFG -v 1
service mysql stop

EOF

COPY --chmod=+x ./ci/scripts/entrypoint/* /user/share/centreon/

ENTRYPOINT ["/usr/share/centreon/container.sh"]
