FROM centos:7

RUN curl -o remi-release-7.rpm https://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum -y update && yum -y install remi-release-7.rpm
RUN yum-config-manager --enable remi-php80
RUN curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -
RUN yum install -y nodejs php-cli php-dom php-mbstring php-intl php-pdo git
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer
WORKDIR /src