FROM docker.registry.apps.centreon.com/@WEB_FRESH_IMAGE@

COPY ./ci/scripts/sql /tmp/sql

RUN <<EOF

service mysql start
mysql centreon < /tmp/sql/standard.sql
mysql centreon < /tmp/sql/media.sql
mysql centreon < /tmp/sql/openldap.sql
centreon -u admin -p Centreon\!2021 -a APPLYCFG -v 1
service mysql stop

EOF
