FROM docker-proxy.registry.apps.centreon.com/debian:bullseye

RUN apt-get -y update && apt-get -y dist-upgrade \
  && apt-get install -y ca-certificates curl gnupg lsb-release wget zip pigz \
  && mkdir -p /etc/apt/keyrings \
  && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
  && apt-get update -y \
  && apt-get install -y docker-ce docker-ce-cli containerd.io libsodium-dev \
  && curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose && docker-compose --version \
  && wget -O- https://packages.sury.org/php/apt.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/php.gpg  > /dev/null 2>&1 \
  && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/sury-php.list \
  && apt-get update -y && apt-get install -y php8.0-fpm php8.0-cli php8.0-xml php8.0-simplexml php8.0-curl php8.0-dom php8.0-zip  \
  && wget https://raw.githubusercontent.com/composer/getcomposer.org/d366ce4e77501dd11a28baace02e702dd9f1c203/web/installer -O - -q | php -- --quiet && mv composer.phar /usr/local/bin/composer && composer -v