#!/usr/bin/perl
# 
# Copyright 2019 Centreon (http://www.centreon.com/)
#
# Centreon is a full-fledged industry-strength solution that meets
# the needs in IT infrastructure and application monitoring for
# service performance.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin";
use gorgone::class::core;

gorgone::class::core->new()->run();

__END__

=head1 NAME

gorgoned - a daemon to handle so many things.

=head1 SYNOPSIS

gorgoned [options]

=head1 OPTIONS

=over 8

=item B<--config>

Specify the path to the yaml configuration file (default: '').

=item B<--help>

Print a brief help message and exits.

=item B<--version>

Print version message and exits.

=back

=head1 DESCRIPTION

B<gorgoned> will survive

=cut
