export const labelComment = 'Comment';
export const labelBy = 'By';
export const labelFrom = 'From';
export const labelTo = 'To';
export const labelAcknowledgement = 'Acknowledgement';
export const labelDowntime = 'Downtime';
export const labelMin = 'Min';
export const labelMax = 'Max';
export const labelAvg = 'Avg';
export const labelWarningTooManyGraphs =
  (limit: number): string => `Too many elements to be displayed (>${limit})`;
