### login
POST {{uri}}/authentication/providers/configurations/local
Content-Type: application/json

{
  "login": "{{user}}",
  "password": "{{password}}"
}

> {% client.global.set("cookie", response.headers['cookie']); %}