### add dashboard
POST {{uri}}/configuration/dashboards
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

{"name":"test one","description":"test description"}

### get all dashboards
GET {{uri}}/configuration/dashboards
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

### get dashboard
GET {{uri}}/configuration/dashboards/10
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

### update dashboard
PUT {{uri}}/configuration/dashboards/10
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

{"name":"test one","description":"test description - UPDATED"}

### delete dashboard
DELETE {{uri}}/configuration/dashboards/9
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}


