<?php

declare(strict_types=1);

namespace Tests\App\Monitoring\Infrastructure\ApiPlatform\State;

use App\Monitoring\Domain\Aggregate\Notification\NotificationId;
use App\Monitoring\Domain\Repository\NotificationRepository;
use App\Monitoring\Infrastructure\ApiPlatform\Resource\Notification\NotificationResource;
use App\Monitoring\Infrastructure\Dbal\DbalNotificationRepository;
use PHPUnit\Framework\Attributes\Group;
use Symfony\Component\HttpFoundation\Request;
use Tests\App\Shared\ApiTestCase;

/**
 * Post OK => 201
 * Post timeperiod not exist
 * Post wrong timeperiod name
 * Post user not enought rights
 * Post user not connected
  */
final class CreateNotificationProcessorTest extends ApiTestCase {

    private NotificationRepository $repository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        /** @var NotificationRepository $repository */
        $repository = self::getContainer()->get(NotificationRepository::class);
        $this->repository = $repository;
    }

    #[Group('wip')]
    public function testCreateNotification(): void
    {
        $this->login();
        $response = $this->request(
            Request::METHOD_POST,
            '/api/latest/configuration/notifications',
            [
                'json' => [
                    'name' => 'new notif',
                    'is_activated' => true,
                    'timeperiod_id' => 1,
                ]
            ],
        );
        self::assertResponseIsSuccessful();
        self::assertMatchesResourceItemJsonSchema(NotificationResource::class);
        self::assertJsonContains(
            [
                'name' => 'new notif',
                'is_activated' => true,
                'timeperiod' => [
                    'id' => 1,
                ],
            ]
        );
        $id = new NotificationId($response->toArray()['id']);
        $this->repository->get($id);
    }
}
