name: "publish-lint-report"
description: "Publish ESLint report"
inputs:
  check_name:
    description: "Name of the check and comment"
    default: "${{ github.workflow }}-${{ github.job }}-report"
  path:
    description: "Path to the report files"
    required: true
runs:
  using: "composite"
  steps:
    - env:
        REPORT_PATH: ${{ inputs.path }}
      run: |
        node ./.github/actions/publish-lint-report/formatJsonToMarkdown.js "$REPORT_PATH" "$GITHUB_WORKSPACE"
        cat eslint-report.md >> $GITHUB_STEP_SUMMARY
      shell: bash
