FROM debian:bookworm

RUN bash -e <<EOF

apt-get update
apt-get install -y git locales php-cli gettext zstd sudo
apt-get clean

locale-gen en_US.UTF-8
locale-gen fr_FR.UTF-8
locale-gen de_DE.UTF-8
locale-gen es_ES.UTF-8
locale-gen pt_PT.UTF-8
locale-gen pt_BR.UTF-8

EOF

ENV LANG=en_US.utf8

USER 1001:1001
