FROM alpine:3.22

RUN sh -e <<EOF

apk add --no-cache --update \
  bash \
  coreutils \
  gettext \
  git \
  musl \
  musl-utils \
  musl-locales \
  php82-cli \
  tzdata \
  zstd

ln -s /usr/bin/php82 /usr/bin/php

# echo "en_US.UTF-8 UTF-8" | tee -a /etc/locale.gen
# echo "fr_FR.UTF-8 UTF-8" | tee -a /etc/locale.gen
# echo "es_ES.UTF-8 UTF-8" | tee -a /etc/locale.gen
# echo "pt_BR.UTF-8 UTF-8" | tee -a /etc/locale.gen
# echo "pt_PT.UTF-8 UTF-8" | tee -a /etc/locale.gen
# echo "de_DE.UTF-8 UTF-8" | tee -a /etc/locale.gen
# locale-gen

EOF

ENV LANG=en_US.utf8
