FROM almalinux:8

RUN bash -e <<EOF

dnf module reset -y ruby
dnf module enable -y ruby:3.0
dnf install -y ruby

dnf install -y make rpm-build rpm-sign zstd perl-devel selinux-policy-devel
dnf clean all

EOF

WORKDIR /src
