FROM almalinux:9 AS web_fresh

RUN bash -e <<EOF

######################################
# install and configure repositories #
######################################

dnf install -y dnf-plugins-core

dnf config-manager --set-enabled crb

dnf install -y epel-release

dnf config-manager --add-repo https://packages.centreon.com/rpm-standard/23.04/el9/centreon-23.04.repo
dnf config-manager --set-enabled 'centreon*'

#############################
# install base dependencies #
#############################

dnf install -y \
  bc \
  brotli \
  coreutils \
  cronie \
  httpd \
  initscripts \
  net-snmp \
  net-snmp-perl \
  net-snmp-utils \
  openssl \
  perl-DBD-MySQL \
  perl-DBD-SQLite \
  perl-DBI \
  perl-HTML-Parser \
  rrdtool \
  rrdtool-perl \
  rsync \
  sed \
  sudo

#############################
# install test dependencies #
#############################

dnf install -y libfaketime

############################
# install php dependencies #
############################

dnf module enable -y php:8.1
dnf install -y \
  php-common \
  php-cli \
  php-pdo \
  php-mysqlnd \
  php-gd \
  php-xml \
  php-mbstring \
  php-ldap \
  php-snmp \
  php-intl \
  php-fpm \
  php-curl \
  php-zip \
  php-pear \
  php-json

#################################
# install and configure mariadb #
#################################

curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup \
  | bash -s -- --os-type=rhel --skip-check-installed --os-version=9 --mariadb-server-version="mariadb-10.5"
dnf install -y mariadb-server mariadb

echo "[server]
log_output=FILE
general_log_file        = /var/lib/mysql/queries.log
general_log             = 0
slow_query_log_file     = /var/lib/mysql/slow_queries.log
slow_query_log          = 1
innodb_file_per_table   = 1
innodb_flush_method     = O_DIRECT
innodb_fast_shutdown    = 0
innodb_log_file_size    = 16M
skip-name-resolve       = 1
key_buffer_size         = 16M
read_buffer_size        = 60K
sort_buffer_size        = 1M
innodb_buffer_pool_size = 64M
tmp_table_size          = 8M
max_allowed_packet      = 16M
thread_stack            = 192K
thread_cache_size       = 8
table_open_cache        = 2000
table_definition_cache  = 1400
performance_schema      = ON
open_files_limit        = 32000
" > /etc/my.cnf.d/container.cnf

dnf clean all --enablerepo=*

EOF

COPY --chmod=+x ./.github/docker/init/* /etc/init.d/
