FROM alpine:3.22

RUN sh -e <<EOF

apk add --no-cache --update \
  bash \
  coreutils \
  curl \
  findutils \
  gettext \
  git \
  musl \
  musl-utils \
  musl-locales \
  php82-cli \
  tar \
  tzdata \
  zstd

ln -s /usr/bin/php82 /usr/bin/php

EOF

ENV LANG=en_US.utf8
