FROM debian:bullseye

ENV DEBIAN_FRONTEND noninteractive

RUN bash -e <<EOF

#echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list

apt update

apt install -y debmake pbuilder dh-exec aptitude zstd

apt clean

EOF

WORKDIR /src
