FROM almalinux:9

ARG NFPM_VERSION=2.45.0

RUN bash -e <<EOF

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

dnf install -y zstd nfpm-${NFPM_VERSION} selinux-policy-devel

rm -f /etc/yum.repos.d/goreleaser.repo

dnf clean all

EOF
