FROM almalinux:8 AS web_fresh

RUN bash -e <<EOF

######################################
# install and configure repositories #
######################################

dnf install -y dnf-plugins-core

dnf config-manager --set-enabled powertools

dnf install -y epel-release

dnf config-manager --add-repo https://packages.centreon.com/rpm-standard/22.10/el8/centreon-22.10.repo
dnf config-manager --set-enabled 'centreon*'

#############################
# install base dependencies #
#############################

dnf install -y \
  bc \
  brotli \
  bzip2 \
  cronie \
  httpd \
  initscripts \
  libsodium \
  libunwind \
  lua \
  openpgm \
  net-snmp \
  net-snmp-perl \
  net-snmp-utils \
  openssl \
  rrdtool \
  rrdtool-perl \
  rsync \
  sed \
  sudo \
  zeromq

#############################
# install perl dependencies #
#############################

dnf install -y \
  perl \
  perl-DBD-MySQL \
  perl-DBD-SQLite \
  perl-DBI \
  perl-EV \
  perl-HTML-Parser \
  perl-NetAddr-IP \
  perl-Net-Curl \
  perl-Net-DNS \
  perl-Net-HTTP \
  perl-Net-Ping \
  perl-Pod-Parser \
  perl-Specio \
  perl-Test-Simple \
  perl-Unicode-Collate \
  perl-XML-LibXML \
  perl-XML-SAX \
  perl-XML-Twig \
  perl-UUID \
  perltidy

#############################
# install test dependencies #
#############################

dnf install -y libfaketime

############################
# install php dependencies #
############################

dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
dnf module reset -y php
dnf module install -y php:remi-8.1

dnf install -y \
  php-common \
  php-cli \
  php-pdo \
  php-mysqlnd \
  php-gd \
  php-xml \
  php-mbstring \
  php-ldap \
  php-snmp \
  php-intl \
  php-fpm \
  php-curl \
  php-zip \
  php-pear \
  php-json

#################################
# install and configure mariadb #
#################################

curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup \
  | bash -s -- --os-type=rhel --skip-check-installed --os-version=8 --mariadb-server-version="mariadb-10.5" --skip-maxscale
dnf install -y mariadb-server mariadb

echo "[server]
log_output=FILE
general_log_file        = /var/lib/mysql/queries.log
general_log             = 0
slow_query_log_file     = /var/lib/mysql/slow_queries.log
slow_query_log          = 1
innodb_file_per_table   = 1
innodb_flush_method     = O_DIRECT
innodb_fast_shutdown    = 0
innodb_log_file_size    = 16M
skip-name-resolve       = 1
key_buffer_size         = 16M
read_buffer_size        = 60K
sort_buffer_size        = 1M
innodb_buffer_pool_size = 64M
tmp_table_size          = 8M
max_allowed_packet      = 16M
thread_stack            = 192K
thread_cache_size       = 8
table_open_cache        = 2000
table_definition_cache  = 1400
performance_schema      = ON
open_files_limit        = 32000
" > /etc/my.cnf.d/container.cnf

################################
# install collect dependencies #
################################

dnf install -y \
  centreon-engine \
  centreon-plugin-Applications-Databases-Mysql \
  centreon-plugin-Applications-Monitoring-Centreon-Central \
  centreon-plugin-Applications-Monitoring-Centreon-Database \
  centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx \
  centreon-plugin-Applications-Monitoring-Centreon-Poller \
  centreon-plugin-Applications-Protocol-Dns \
  centreon-plugin-Applications-Protocol-Ftp \
  centreon-plugin-Applications-Protocol-Http \
  centreon-plugin-Applications-Protocol-Ldap \
  centreon-plugin-Hardware-Printers-Generic-Snmp \
  centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp \
  centreon-plugin-Network-Cisco-Standard-Snmp \
  centreon-plugin-Operatingsystems-Linux-Snmp \
  centreon-plugin-Operatingsystems-Windows-Snmp \
  nagios-plugins \
  nagios-plugins-dhcp \
  nagios-plugins-icmp

dnf clean all --enablerepo=*

EOF

COPY --chmod=755 ./.github/scripts/init/* /etc/init.d/