FROM debian:bullseye AS web_fresh

ENV DEBIAN_FRONTEND noninteractive

RUN <<EOF

apt update

apt install -y ca-certificates apt-transport-https software-properties-common wget gnupg2 curl sudo

. /etc/os-release
echo "deb https://packages.sury.org/php/ $VERSION_CODENAME main" | tee /etc/apt/sources.list.d/sury-php.list
wget -O- https://packages.sury.org/php/apt.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/php.gpg  > /dev/null 2>&1
apt update

curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash -s -- --os-type=debian --os-version=11 --mariadb-server-version="mariadb-10.5"

#echo "deb https://centreon.jfrog.io/artifactory/apt-23.04-stable/ $VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-stable.list
#echo "deb https://centreon.jfrog.io/artifactory/apt-23.04-testing/ $VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-testing.list
echo "deb https://centreon.jfrog.io/artifactory/apt-23.04-unstable/ $VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-unstable.list
echo "deb https://centreon.jfrog.io/artifactory/apt-plugins-unstable/ $VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-plugins-unstable.list
wget -O- https://centreon.jfrog.io/artifactory/api/security/keypair/Debian/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1
apt update

apt install -y mariadb-server mariadb-client

echo "[server]
skip-grant-tables
log_output=FILE
general_log_file=/var/lib/mysql/queries.log
general_log=0
slow_query_log_file=/var/lib/mysql/slow_queries.log
slow_query_log=1
innodb_file_per_table
innodb_flush_method=O_DIRECT
innodb_log_file_size=4M
innodb_fast_shutdown=0
" > /etc/mysql/conf.d/container.cnf

apt clean

mkdir /tmp/debs-centreon

EOF

COPY *.deb /tmp/debs-centreon/

RUN <<EOF

apt update

rm -f /tmp/debs-centreon/centreon-23.04*.deb /tmp/debs-centreon/centreon-central-23.04*.deb
apt install -y /tmp/debs-centreon/centreon-*.deb

rm -f /usr/share/centreon/.env.local.php
echo "APP_DEBUG=true" >> /usr/share/centreon/.env
echo "DEBUG_LEVEL=100" >> /usr/share/centreon/.env

touch /var/log/php8.1-fpm-centreon-error.log
chown www-data:www-data /var/log/php8.1-fpm-centreon-error.log

apt clean

EOF

COPY --chmod=+x ./.github/docker/centreon-web-bullseye/entrypoint/container.sh /usr/share/centreon/container.sh
COPY ./.github/docker/centreon-web-bullseye/entrypoint/container.d /usr/share/centreon/container.d
COPY ./.github/docker/init/* /etc/init.d/
COPY --chmod=+x ./.github/docker/centreon-web-bullseye/scripts/autoinstall.php /usr/share/centreon/
COPY --chown=www-data:www-data ./.github/docker/centreon-web-bullseye/configuration /usr/share/centreon/www/install/tmp/

RUN <<EOF

sed -i 's#^datadir_set=#datadir_set=1#' /etc/init.d/mysql

chmod +x /usr/share/centreon/container.d/*
chmod +x /etc/init.d/*
service mysql start
mysql -e "GRANT ALL ON *.* to 'root'@'localhost' IDENTIFIED BY 'centreon' WITH GRANT OPTION"
cd /usr/share/centreon/www/install/steps/process
su www-data -s /bin/bash -c "php configFileSetup.php"
su www-data -s /bin/bash -c "php installConfigurationDb.php"
su www-data -s /bin/bash -c "php installStorageDb.php"
su www-data -s /bin/bash -c "php createDbUser.php"
su www-data -s /bin/bash -c "SERVER_ADDR='127.0.0.1' php insertBaseConf.php"
su www-data -s /bin/bash -c "php partitionTables.php"
su www-data -s /bin/bash -c "php generationCache.php"
rm -rf /usr/share/centreon/www/install
mysql -pcentreon -e "GRANT ALL ON *.* to 'root'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION"
mysql -e "GRANT ALL ON *.* to 'root'@'%' IDENTIFIED BY 'centreon' WITH GRANT OPTION"
centreon -d -u admin -p Centreon\!2021 -a POLLERGENERATE -v 1
service mysql stop
sed -i "5s/.*/    id: 1/" /etc/centreon-gorgone/config.d/40-gorgoned.yaml

EOF

EXPOSE 80 3306

ENTRYPOINT ["/usr/share/centreon/container.sh"]

FROM web_fresh AS web_standard

COPY ./.github/docker/sql /tmp/sql

RUN <<EOF

service mysql start
mysql centreon < /tmp/sql/standard.sql
mysql centreon < /tmp/sql/media.sql
mysql centreon < /tmp/sql/openldap.sql
centreon -d -u admin -p Centreon\!2021 -a POLLERGENERATE -v 1
service mysql stop

EOF
