# syntax=docker/dockerfile:1.3-labs

FROM docker.centreon.com/proxy/almalinux:8 AS web_fresh

ARG centreon_version=22.10.0-14

RUN <<EOF

dnf install -y dnf-plugins-core
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
dnf config-manager --set-enabled 'powertools'

dnf module -y reset php
dnf module -y install php:remi-8.1

curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s -- --os-type=rhel --skip-check-installed --os-version=8 --mariadb-server-version="mariadb-10.5"

dnf config-manager --add-repo https://yum.centreon.com/standard/22.10/el8/stable/noarch
dnf config-manager --add-repo https://yum.centreon.com/standard/22.10/el8/stable/x86_64

dnf install --nogpgcheck -y https://yum.centreon.com/standard/22.10/el8/stable/noarch/RPMS/centreon-web-${centreon_version}.el8.noarch.rpm

echo "date.timezone = Europe/Paris" > /etc/php.d/centreon.ini

rm -f /usr/share/centreon/.env.local.php
echo "APP_DEBUG=true" >> /usr/share/centreon/.env
echo "DEBUG_LEVEL=100" >> /usr/share/centreon/.env

touch /var/log/php-fpm/centreon-error.log
chown apache:apache /var/log/php-fpm/centreon-error.log

EOF

COPY --chmod=+x ./.github/docker/centreon-web-alma8/entrypoint/container.sh /usr/share/centreon/container.sh
COPY ./.github/docker/centreon-web-alma8/entrypoint/container.d /usr/share/centreon/container.d
COPY ./.github/docker/init/* /etc/init.d/
COPY --chmod=+x ./.github/docker/centreon-web-alma8/scripts/autoinstall.php /usr/share/centreon/
COPY --chown=apache:apache ./.github/docker/centreon-web-alma8/configuration /usr/share/centreon/www/install/tmp/

RUN <<EOF

chmod +x /usr/share/centreon/container.d/*
chmod +x /etc/init.d/*
chmod +x /usr/share/centreon/container.sh
service mysql start
mysql -e "GRANT ALL ON *.* to 'root'@'localhost' IDENTIFIED BY 'centreon' WITH GRANT OPTION"
cd /usr/share/centreon/www/install/steps/process
su apache -s /bin/bash -c "php configFileSetup.php"
su apache -s /bin/bash -c "php installConfigurationDb.php"
su apache -s /bin/bash -c "php installStorageDb.php"
su apache -s /bin/bash -c "php createDbUser.php"
su apache -s /bin/bash -c "SERVER_ADDR='127.0.0.1' php insertBaseConf.php"
su apache -s /bin/bash -c "php partitionTables.php"
su apache -s /bin/bash -c "php generationCache.php"
rm -rf /usr/share/centreon/www/install
mysql -pcentreon -e "GRANT ALL ON *.* to 'root'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION"
mysql -e "GRANT ALL ON *.* to 'root'@'%' IDENTIFIED BY 'centreon' WITH GRANT OPTION"
centreon -d -u admin -p Centreon\!2021 -a POLLERGENERATE -v 1
service mysql stop
sed -i "5s/.*/    id: 1/" /etc/centreon-gorgone/config.d/40-gorgoned.yaml

EOF

EXPOSE 80 3306

ENTRYPOINT ["/usr/share/centreon/container.sh"]
