FROM almalinux:10-minimal

RUN bash -e <<EOF

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

dnf install -y make zstd nfpm-2.45.0 selinux-policy-devel

dnf clean all

EOF
