#!/bin/bash
#----
## @Synopsis	Installation variables needed for Centreon Gorgone module
## @Copyright	Copyright 2008, Guillaume Watteeux
## @Copyright	Copyright 2008-2020, Centreon
## @License	GPL : http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
#----
## Centreon is developed with GPL Licence 2.0
## Developed by : Julien Mathis - Romain Le Merlus
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
##    For information : infos@centreon.com
#

#----
## install_vars
#----

# sources and log paths
LOG_DIR="$BASE_DIR/log"
LOG_FILE="$LOG_DIR/gorgone_install.log"

# deployment paths
DEFAULT_GORGONE_LOG="/var/log/centreon-gorgone"
DEFAULT_GORGONE_VARLIB="/var/lib/centreon-gorgone"
DEFAULT_GORGONE_ETC="/etc/centreon-gorgone"
DEFAULT_GORGONE_CONF_FILE="/config.yaml"
DEFAULT_GORGONE_BINDIR="/usr/bin/"

# perl related paths
DEFAULT_PERL_BIN="/usr/bin/perl"
DEFAULT_GORGONE_PERL=`eval "\`perl -V:installvendorlib\`"; echo $installvendorlib`

# system tools paths
DEFAULT_INIT_D="/etc/init.d"
DEFAULT_CRON_D="/etc/cron.d"
DEFAULT_LOGROTATE_D="/etc/logrotate.d"
DEFAULT_SYSTEM_D="/etc/systemd/system"
DEFAULT_SYSCONFIG="/etc/sysconfig"

# user and group
DEFAULT_GORGONE_USER="centreon-gorgone"
DEFAULT_GORGONE_GROUP="centreon-gorgone"
