export const label1Day = '1 day';
export const label7Days = '7 days';
export const label31Days = '31 days';
export const labelLastDay = 'Last day';
export const labelLast7Days = 'Last 7 days';
export const labelLast31Days = 'Last 31 days';
export const labelFrom = 'From';
export const labelTo = 'To';
export const labelCompactTimePeriod = 'Compact time period';
