UpdateServiceGroup:
  methods: PUT
  path: /configuration/services/groups/{serviceGroupId}
  requirements:
    serviceGroupId: '\d+'
  controller: 'Core\ServiceGroup\Infrastructure\API\UpdateServiceGroup\UpdateServiceGroupController'
  condition: "request.attributes.get('version') >= '25.10'"
