#!/usr/bin/dh-exec

debian/extra/centreon-trap/centreontrapd.service    lib/systemd/system
debian/extra/centreon-trap/centreontrapd            etc/default
bin/centreontrapd                                   usr/share/centreon/bin
bin/centreontrapdforward                            usr/share/centreon/bin

tmpl/install/systemd/centreontrapd.systemd => lib/systemd/system/centreontrapd.service
tmpl/install/systemd/centreontrapd.sysconfig => etc/default/centreontrapd
