#!/bin/sh

set -e

case "$1" in
    remove)
        systemctl --no-reload disable --now centreon.service || : &>/dev/null || :
    ;;
    purge)
        deluser centreon || true
        delgroup centreon || true
        deluser centreon centreon-broker || :
        deluser centreon-broker centreon || :
        deluser centreon centreon-engine || :
        deluser centreon-engine centreon || :
    ;;
esac

exit 0
