-- Minimal centreontrapd.sdb fixture for e2e runtime tests.
--
-- In production this SQLite file is generated by centreon/bin/generateSqlLite
-- from the real MySQL config (poller mode=1). centreontrapd queries it even
-- for basic startup (e.g. cfg_nagios.command_file) and crash-loops without
-- at least that table populated. Schema mirrors generateSqlLite verbatim;
-- only cfg_nagios has a seeded row since no other tables are needed to boot.

CREATE TABLE IF NOT EXISTS `nagios_server` (
    `id` int(11) UNIQUE NOT NULL,
    `ns_ip_address` varchar(200) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `cfg_nagios` (
    `command_file` varchar(255) DEFAULT NULL,
    `nagios_activate` int(11) DEFAULT '1'
);

CREATE TABLE IF NOT EXISTS `ns_host_relation` (
    `host_host_id` int(11) DEFAULT NULL,
    `nagios_server_id` int(11) DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_nhr_host_host_id ON ns_host_relation (host_host_id);

CREATE TABLE IF NOT EXISTS `host` (
    `host_id` int(11) UNIQUE NOT NULL,
    `host_name` varchar(200) DEFAULT NULL,
    `host_address` varchar(255) DEFAULT NULL,
    `host_snmp_community` varchar(255) DEFAULT NULL,
    `host_snmp_version` varchar(255) DEFAULT NULL,
    `host_activate` int(11) DEFAULT '1'
);

CREATE INDEX IF NOT EXISTS idx_host_host_id ON host (host_id);

CREATE TABLE IF NOT EXISTS `service` (
    `service_id` int(11) UNIQUE NOT NULL,
    `service_description` varchar(200) DEFAULT NULL,
    `service_template_model_stm_id` int(11) DEFAULT NULL,
    `service_activate` int(11) DEFAULT '1'
    );

CREATE INDEX IF NOT EXISTS idx_service_service_id ON service (service_id);

CREATE TABLE IF NOT EXISTS `extended_service_information` (
    `service_service_id` int(11) UNIQUE NOT NULL,
    `esi_notes` text DEFAULT NULL
    );

CREATE INDEX IF NOT EXISTS idx_esi_service_service_id ON extended_service_information (service_service_id);

CREATE TABLE IF NOT EXISTS `hostgroup_relation` (
    `host_host_id` int(11) DEFAULT NULL,
    `hostgroup_hg_id` int(11) DEFAULT NULL
    );

CREATE INDEX IF NOT EXISTS idx_hr_host_host_id ON hostgroup_relation (host_host_id);

CREATE TABLE IF NOT EXISTS `host_template_relation` (
    `host_host_id` int(11) DEFAULT NULL,
    `host_tpl_id` int(11) DEFAULT NULL,
    `order` int(11) DEFAULT NULL
    );

CREATE INDEX IF NOT EXISTS idx_htr_host_host_id ON host_template_relation (host_host_id);

CREATE TABLE IF NOT EXISTS `on_demand_macro_host` (
    `host_macro_name` varchar(255) NOT NULL,
    `host_macro_value` varchar(255) NOT NULL,
    `host_host_id` int(11) DEFAULT NULL
    );

CREATE INDEX IF NOT EXISTS idx_odmh_host_host_id ON on_demand_macro_host (host_host_id);

CREATE TABLE IF NOT EXISTS `host_service_relation` (
    `service_service_id` int(11) DEFAULT NULL,
    `host_host_id` int(11) DEFAULT NULL,
    `hostgroup_hg_id` int(11) DEFAULT NULL
    );

CREATE INDEX IF NOT EXISTS idx_hsr_host_host_id ON host_service_relation (host_host_id);

CREATE TABLE IF NOT EXISTS `traps_service_relation` (
        `traps_id` int(11) DEFAULT NULL,
        `service_id` int(11) DEFAULT NULL
        );

CREATE INDEX IF NOT EXISTS idx_tsr_mult_ids ON traps_service_relation (service_id, traps_id);

CREATE TABLE IF NOT EXISTS `traps` (
        `traps_id` int(11) UNIQUE NOT NULL,
        `traps_name` varchar(255) DEFAULT NULL,
        `traps_mode` int(11) DEFAULT 0,
        `traps_oid` varchar(255) DEFAULT NULL,
        `traps_args` varchar(255) DEFAULT NULL,
        `traps_status` int(11) DEFAULT NULL,
        `severity_id` int(11) DEFAULT NULL,
        `manufacturer_id` int(11) DEFAULT NULL,
        `traps_reschedule_svc_enable` int(11) DEFAULT '0',
        `traps_execution_command` text DEFAULT NULL,
        `traps_execution_command_enable` int(11) DEFAULT '0',
        `traps_submit_result_enable` int(11) DEFAULT '0',
        `traps_advanced_treatment` int(11) DEFAULT '0',
        `traps_advanced_treatment_default` int(11) DEFAULT '0',
        `traps_timeout` int(11) DEFAULT NULL,
        `traps_exec_interval` int(11) DEFAULT NULL,
        `traps_exec_interval_type` int(11) DEFAULT '0',
        `traps_downtime` int(11) DEFAULT '0',
        `traps_log` int(11) DEFAULT '0',
        `traps_routing_mode` int(11) DEFAULT '0',
        `traps_routing_value` varchar(255) DEFAULT NULL,
        `traps_routing_filter_services` varchar(255) DEFAULT NULL,
        `traps_output_transform` varchar(255) DEFAULT NULL,
        `traps_exec_method` int(11) DEFAULT '0',
        `traps_customcode` text DEFAULT NULL
        );

CREATE INDEX IF NOT EXISTS idx_t_traps_oid ON traps (traps_oid);

CREATE TABLE IF NOT EXISTS `traps_matching_properties` (
        `tmo_id` int(11) DEFAULT NULL,
        `trap_id` int(11) DEFAULT NULL,
        `tmo_order` int(11) DEFAULT NULL,
        `tmo_regexp` varchar(255) DEFAULT NULL,
        `tmo_string` varchar(255) DEFAULT NULL,
        `tmo_status` int(11) DEFAULT NULL,
        `severity_id` int(11) DEFAULT NULL
        );

CREATE INDEX IF NOT EXISTS idx_tmp_trap_id ON traps_matching_properties (trap_id);

CREATE TABLE IF NOT EXISTS `traps_preexec` (
        `trap_id` int(11) DEFAULT NULL,
        `tpe_order` int(11) DEFAULT NULL,
        `tpe_string` varchar(512) DEFAULT NULL
        );

CREATE INDEX IF NOT EXISTS idx_tprexec_trap_id ON traps_preexec (trap_id);

CREATE TABLE IF NOT EXISTS `traps_group_relation` (
        `traps_group_id` int(11) DEFAULT NULL,
        `traps_id` int(11) DEFAULT NULL
        );

CREATE INDEX IF NOT EXISTS idx_tg_traps_id ON traps_group_relation (traps_id);
CREATE INDEX IF NOT EXISTS idx_tg_traps_group_id ON traps_group_relation (traps_group_id);

CREATE TABLE IF NOT EXISTS `traps_vendor` (
    `id` int(11) DEFAULT NULL,
    `name` int(11) DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_tv_id ON traps_vendor (`id`);

CREATE TABLE IF NOT EXISTS `service_categories` (
    `sc_id` int(11) DEFAULT NULL,
    `sc_name` varchar(255) DEFAULT NULL,
    `level` int(11) DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_sc_sc_id ON service_categories (`sc_id`);

INSERT INTO cfg_nagios (command_file, nagios_activate)
VALUES ('/var/lib/centreon-engine/rw/centengine.cmd', '1');
