ARG MAJOR_VERSION

FROM almalinux:8 AS web_dependencies

ARG MAJOR_VERSION
ARG IS_CLOUD
ARG STABILITY

RUN --mount=type=secret,id=ARTIFACTORY_INTERNAL_REPO_USERNAME \
    --mount=type=secret,id=ARTIFACTORY_INTERNAL_REPO_PASSWORD \
    bash -e <<EOF

######################################
# install and configure repositories #
######################################

echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf

dnf install -y dnf-plugins-core

dnf config-manager --set-enabled powertools

dnf install -y epel-release

if [[ "${IS_CLOUD}" == "true" ]]; then
  dnf config-manager --add-repo https://$(cat /run/secrets/ARTIFACTORY_INTERNAL_REPO_USERNAME):$(cat /run/secrets/ARTIFACTORY_INTERNAL_REPO_PASSWORD)@packages.centreon.com/rpm-standard-internal/${MAJOR_VERSION}/el8/centreon-${MAJOR_VERSION}-internal.repo
  sed -i "s#packages.centreon.com/rpm-standard-internal#$(cat /run/secrets/ARTIFACTORY_INTERNAL_REPO_USERNAME):$(cat /run/secrets/ARTIFACTORY_INTERNAL_REPO_PASSWORD)@packages.centreon.com/rpm-standard-internal#" /etc/yum.repos.d/centreon-${MAJOR_VERSION}-internal.repo
else
  dnf config-manager --add-repo https://packages.centreon.com/rpm-standard/${MAJOR_VERSION}/el8/centreon-${MAJOR_VERSION}.repo
fi

dnf config-manager --set-enabled 'centreon*'

if [[ "$STABILITY" == "testing" ]]; then
  dnf config-manager --set-disabled 'centreon*unstable*'
elif [[ "$STABILITY" == "stable" ]]; then
  dnf config-manager --set-disabled 'centreon*unstable*' --set-disabled 'centreon*testing*'
fi

#############################
# install base dependencies #
#############################

dnf install -y \
  bc \
  brotli \
  bzip2 \
  cronie \
  httpd \
  initscripts \
  jq \
  libsodium \
  libunwind \
  lua \
  openpgm \
  net-snmp \
  net-snmp-utils \
  openssl \
  python3 \
  rrdtool \
  rrdtool-perl \
  rsync \
  sed \
  sudo \
  zeromq

#############################
# install perl dependencies #
#############################

dnf install -y \
  perl-interpreter \
  perl-DBD-MySQL \
  perl-DBD-SQLite \
  perl-DBI \
  perl-HTML-Parser \
  perl-Net-Curl \
  perl-Env

#############################
# install test dependencies #
#############################

dnf install -y libfaketime

############################
# install php dependencies #
############################

dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
dnf module reset -y php
dnf module install -y php:remi-8.2

dnf install -y \
  php-common \
  php-cli \
  php-pdo \
  php-mysqlnd \
  php-gd \
  php-xml \
  php-mbstring \
  php-ldap \
  php-snmp \
  php-intl \
  php-fpm \
  php-curl \
  php-zip \
  php-pear \
  php-json

sed -i "s#apache,nginx#apache#g" /etc/php-fpm.d/www.conf

dnf clean all --enablerepo=*

EOF

COPY --chmod=755 ./.github/docker/centreon-web/init/systemctl /bin/systemctl

COPY --chmod=755 ./.github/docker/centreon-web/init/* /etc/init.d/

FROM web_dependencies AS web_dependencies_collect

ARG COLLECT_MINOR_VERSION
ARG COMMON_MINOR_VERSION
ARG GORGONE_MINOR_VERSION
ARG MAJOR_VERSION
ARG STABILITY

RUN bash -e <<EOF

if [[ "$STABILITY" == "stable" ]]; then
  dnf install -y \
    centreon-common-${MAJOR_VERSION}.${COMMON_MINOR_VERSION} \
    centreon-gorgone-${MAJOR_VERSION}.${GORGONE_MINOR_VERSION} \
    centreon-engine-${MAJOR_VERSION}.${COLLECT_MINOR_VERSION} \
    centreon-broker-cbmod-${MAJOR_VERSION}.${COLLECT_MINOR_VERSION} \
    centreon-broker-cbd-${MAJOR_VERSION}.${COLLECT_MINOR_VERSION} \
    centreon-connector-${MAJOR_VERSION}.${COLLECT_MINOR_VERSION}
else
  dnf install -y \
    centreon-common \
    centreon-gorgone \
    centreon-engine \
    centreon-broker-cbmod \
    centreon-broker-cbd \
    centreon-connector
fi

dnf clean all --enablerepo=*

EOF
