#!/usr/bin/env bash
set -euo pipefail

LIMIT="${LIMIT:-1}"

if ! [[ "$LIMIT" =~ ^[0-9]+$ ]]; then
  echo "ERROR: LIMIT must be an integer"
  exit 1
fi
missing_env_vars=()
if [[ -z "${PROJECT_KEY:-}" ]]; then
  missing_env_vars+=("PROJECT_KEY")
fi
if [[ -z "${SUMMARY:-}" ]]; then
  missing_env_vars+=("SUMMARY")
fi
if [[ -z "${ISSUE_TYPE:-}" ]]; then
  missing_env_vars+=("ISSUE_TYPE")
fi
if ((${#missing_env_vars[@]} > 0)); then
  echo "ERROR: required environment variable(s) ${missing_env_vars[*]} is/are empty"
  exit 1
fi

DESCRIPTION="${SUMMARY} generated by GitHub Action in ${GITHUB_REPOSITORY}#${GITHUB_REF_NAME} (${GITHUB_SHA})"
LABELS='["github-action", "automated-tests"]'
PRIORITY='High'

GRAPHQL_VARS=$(jq -n -c \
  --arg projectKey "$PROJECT_KEY" \
  --arg summary "$SUMMARY" \
  --arg description "$DESCRIPTION" \
  --argjson limit "$LIMIT" \
  --argjson labels "$LABELS" \
  --arg priority "$PRIORITY" \
  --arg issueType "$ISSUE_TYPE" \
  '{ projectKey: $projectKey, summary: $summary, description: $description, limit: $limit, labels: $labels, priority: $priority, issueType: $issueType }')

echo "graphql_vars=$GRAPHQL_VARS" >> "$GITHUB_OUTPUT"

echo "Prepared GraphQL variables:"
echo "$GRAPHQL_VARS"
