centreon:
    resource: "./Centreon/**/*.yaml"
    prefix: "{base_uri}api/{version}"
    defaults:
        version: "latest"
    requirements:
        base_uri: ".*"
        version: '%api.version.pattern%'
centreon_authentication_bare_api:
    resource: "./Centreon/authentication.yaml"
    prefix: "{base_uri}api"
    name_prefix: "bare_api_"
    requirements:
        base_uri: ".*"
security:
    resource: "./Security/**/*.yaml"
    prefix: "{base_uri}authentication"
    requirements:
        base_uri: ".*"
core:
    resource: "./../../src/Core/**/Infrastructure/**/*Route.yaml"
    prefix: "{base_uri}api/{version}"
    defaults:
        version: "latest"
    requirements:
        base_uri: ".*"
        version: '%api.version.pattern%'
core_attribute:
    resource: "./../../src/Core/**/Infrastructure/**/*Controller.php"
    type: attribute
    prefix: "{base_uri}api/{version}"
    defaults:
      version: "latest"
    requirements:
        base_uri: ".*"
        version: '%api.version.pattern%'
