# Copyright 2025 - present Centreon Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function _checkDockerPrerequisites() {
  local ret=0

  if ! type docker >/dev/null 2>&1; then
    consoleError "docker is not installed or not in PATH."
    logError "docker is not installed or not in PATH."
    ret=1
  fi

  if ! docker compose version >/dev/null 2>&1; then
    consoleError "docker compose (v2 plugin) is not available. Run 'docker compose version' to verify."
    logError "docker compose plugin is not available."
    ret=1
  fi

  return ${ret}
}

function runDockerInstall() {
  echo ""
  consoleMainTitle "Generating Docker Compose files for Centreon poller"

  consoleTitle "Checking prerequisites:"
  _checkDockerPrerequisites || exit 1
  consoleInfo "docker and docker compose are available"
  echo ""

  _generateDotEnv "."
  _generateDockerCompose "."

  echo ""
  consoleTitle "Files generated:"
  consoleInfo "  docker-compose.yaml"
  consoleInfo "  .env"
  echo ""
  consoleTitle "Services included:"
  consoleInfo "  centengine, gorgone (always)"
  if [ "${WITH_VMWARE}" = "1" ]; then
    consoleInfo "  centreon-vmware (--with-vmware)"
  fi
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    consoleInfo "  snmptrapd, centreontrapd (--with-snmptrap)"
  fi
  echo ""
  if [ "${START_STACK}" = "1" ]; then
    echo ""
    consoleTitle "Starting stack:"
    docker compose up -d
    echo ""
  else
    consoleTitle "Next steps:"
    echo "  1. Start the stack:"
    echo "       docker compose up -d"
    echo "  (optional) Copy TLS certificates for Centreon Monitoring Agent:"
    echo "       mkdir -p certs && cp poller.crt certs/ && cp poller.key certs/"
    echo ""
  fi
}

function _generateDotEnv() {
  local dir=$1
  logInfo "Generating .env in ${dir}"

  cat > "${dir}/.env" <<EOF
# Generated by install-poller $(date -u +%Y-%m-%dT%H:%M:%SZ)

TAG=${major}
# Per-service tag overrides (leave empty to use TAG for all)
ENGINE_TAG=
GORGONE_TAG=
SNMPTRAPD_TAG=
CENTREONTRAPD_TAG=
VMWARE_TAG=

TZ=${TZ:-UTC}
DEBUG=${DEBUG:-false}

NAME=${POLLER_NAME}
GORGONE_UID=${GORGONE_UID}
CENTRAL_HOST=${CENTRAL_HOST}
CENTRAL_PORT=${CENTRAL_PORT:-443}
GORGONE_TOKEN=${GORGONE_TOKEN}
GORGONE_SSL=${GORGONE_SSL:-true}

APP_SECRET=${APP_SECRET}
SALT=${SALT}
EOF

  if [ $? -ne 0 ]; then
    consoleError "Cannot write .env file."
    logError "Cannot write .env file."
    exit 1
  fi

  consoleInfo ".env written"
  logInfo ".env written"
}

function _generateDockerCompose() {
  local dir=$1
  local out="${dir}/docker-compose.yaml"
  logInfo "Generating docker-compose.yaml in ${dir} (vmware=${WITH_VMWARE}, snmptrap=${WITH_SNMPTRAP})"

  # centengine (always)
  cat > "${out}" <<'EOF'
services:
  centengine:
    image: "docker.centreon.com/centreon/centreon-engine-trixie:${ENGINE_TAG:-${TAG}}"
    container_name: "${NAME}-centengine"
    hostname: centengine
    restart: unless-stopped
    environment:
      NAME: "${NAME}"
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
      APP_SECRET: "${APP_SECRET}"
      SALT: "${SALT}"
    volumes:
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-centlog:/var/log/centreon-engine
      - ./certs/poller.crt:/etc/pki/poller.crt
      - ./certs/poller.key:/etc/pki/poller.key
    ports:
      - 4317:4317
    healthcheck:
      test: ["CMD-SHELL", "grep -q ':1625 01' /proc/net/tcp 2>/dev/null"]
      interval: 30s
      timeout: 5s
      start_period: 5m
      retries: 3
    depends_on:
      gorgone:
        condition: service_healthy
EOF

  # gorgone base volumes (always)
  cat >> "${out}" <<'EOF'
  gorgone:
    image: "docker.centreon.com/centreon/centreon-gorgone-trixie:${GORGONE_TAG:-${TAG}}"
    container_name: "${NAME}-gorgone"
    hostname: gorgone
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
      TYPE: poller
      GORGONE_UID: "${GORGONE_UID}"
      NAME: "${NAME}"
      GORGONE_TOKEN: "${GORGONE_TOKEN}"
      CENTRAL_HOST: "${CENTRAL_HOST}"
      CENTRAL_PORT: "${CENTRAL_PORT}"
      GORGONE__GORGONE__MODULES__PULLWSS__SSL: "${GORGONE_SSL}"
      APP_SECRET: "${APP_SECRET}"
      SALT: "${SALT}"
    volumes:
      - poller-etc:/etc/centreon/
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-gorgone-data:/var/lib/centreon-gorgone/
EOF

  # gorgone extra volume for snmptrap
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
      - poller-snmp-traps:/etc/snmp/centreon_traps
EOF
  fi

  # gorgone healthcheck (always, after volumes)
  cat >> "${out}" <<'EOF'
    healthcheck:
      test: ["CMD-SHELL", "grep -q \":$$(printf '%04X' $${CENTRAL_PORT:-443}) 01\" /proc/net/tcp /proc/net/tcp6 2>/dev/null"]
      interval: 30s
      timeout: 5s
      start_period: 30m
      retries: 3
EOF

  printf '\n' >> "${out}"

  # centreon-vmware (optional)
  if [ "${WITH_VMWARE}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  centreon-vmware:
    image: "connector-vmware:${VMWARE_TAG:-local}"
    container_name: "${NAME}-vmware"
    hostname: centreon-vmware
    restart: unless-stopped
    pull_policy: never
    environment:
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
      APP_SECRET: "${APP_SECRET}"
      SALT: "${SALT}"
    volumes:
      - poller-etc:/etc/centreon/
    depends_on:
      gorgone:
        condition: service_healthy

EOF
  fi

  # snmptrapd + centreontrapd (optional, always together)
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  snmptrapd:
    image: "docker.centreon.com/centreon/centreon-snmptrapd-trixie:${SNMPTRAPD_TAG:-${TAG}}"
    container_name: "${NAME}-snmptrap"
    hostname: snmptrapd
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
    volumes:
      - poller-snmp-spool:/var/spool/centreontrapd
    ports:
      - "162:162/udp"
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD-SHELL", "grep -q ':00A2' /proc/net/udp /proc/net/udp6 2>/dev/null"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

  centreontrapd:
    image: "docker.centreon.com/centreon/centreon-centreontrapd-trixie:${CENTREONTRAPD_TAG:-${TAG}}"
    container_name: "${NAME}-centreontrap"
    hostname: centreontrapd
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
    volumes:
      - poller-snmp-spool:/var/spool/centreontrapd
      - poller-snmp-traps:/etc/snmp/centreon_traps:ro
      - poller-centcmd:/var/lib/centreon-engine/rw
    depends_on:
      snmptrapd:
        condition: service_healthy
      gorgone:
        condition: service_healthy

EOF
  fi

  # Base volumes (always)
  cat >> "${out}" <<'EOF'
volumes:
  poller-etc:
  poller-engine:
  poller-broker:
  poller-centcmd:
  poller-centlog:
  poller-gorgone-data:
EOF

  # Volumes pour snmptrap
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  poller-snmp-spool:
  poller-snmp-traps:
EOF
  fi

  if [ $? -ne 0 ]; then
    consoleError "Cannot write docker-compose.yaml file."
    logError "Cannot write docker-compose.yaml file."
    exit 1
  fi

  consoleInfo "docker-compose.yaml written"
  logInfo "docker-compose.yaml written"
}
