# Copyright 2025 - present Centreon Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function _checkDockerPrerequisites() {
  local ret=0

  if ! type docker >/dev/null 2>&1; then
    consoleError "docker is not installed or not in PATH."
    logError "docker is not installed or not in PATH."
    ret=1
  fi

  if ! docker compose version >/dev/null 2>&1; then
    consoleError "docker compose (v2 plugin) is not available. Run 'docker compose version' to verify."
    logError "docker compose plugin is not available."
    ret=1
  fi

  return ${ret}
}

function runDockerInstall() {
  echo ""
  consoleMainTitle "Generating Docker Compose files for Centreon poller"

  consoleTitle "Checking prerequisites:"
  _checkDockerPrerequisites || exit 1
  consoleInfo "docker and docker compose are available"
  echo ""

  _generateDotEnv "."
  _generateDockerCompose "."

  echo ""
  consoleTitle "Files generated:"
  consoleInfo "  docker-compose.yaml"
  consoleInfo "  .env"
  echo ""
  consoleTitle "Services included:"
  consoleInfo "  centengine, gorgone (always)"
  if [ "${WITH_VMWARE}" = "1" ]; then
    consoleInfo "  centreon-vmware (--with-vmware)"
  fi
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    consoleInfo "  snmptrapd, centreontrapd (--with-snmptrap)"
  fi
  echo ""
  consoleTitle "Next steps:"
  echo "  1. mkdir -p certs"
  echo "  2. Copy or generate TLS certificates into certs/:"
  echo "       certs/poller.crt"
  echo "       certs/poller.key"
  echo "  3. Start the stack:"
  echo "       docker compose up -d"
  echo ""
}

function _generateDotEnv() {
  local dir=$1
  logInfo "Generating .env in ${dir}"

  cat > "${dir}/.env" <<EOF
# Generated by install-poller $(date -u +%Y-%m-%dT%H:%M:%SZ)

TAG=${major}

TZ=UTC
DEBUG=false

NAME=${POLLER_NAME}
UID=${POLLER_UID}
CENTRAL_URL=${CENTRAL_URL}
POLLER_TOKEN=${POLLER_TOKEN}

APP_SECRET=${APP_SECRET}
SALT=${SALT}
EOF

  if [ $? -ne 0 ]; then
    consoleError "Cannot write .env file."
    logError "Cannot write .env file."
    exit 1
  fi

  consoleInfo ".env written"
  logInfo ".env written"
}

function _generateDockerCompose() {
  local dir=$1
  local out="${dir}/docker-compose.yaml"
  logInfo "Generating docker-compose.yaml in ${dir} (vmware=${WITH_VMWARE}, snmptrap=${WITH_SNMPTRAP})"

  # centengine (always)
  cat > "${out}" <<'EOF'
services:
  centengine:
    image: "docker.centreon.com/centreon/centreon-engine-bookworm:${TAG}"
    container_name: "${NAME}-centengine"
    hostname: centengine
    restart: unless-stopped
    environment:
      TZ: "${TZ:-UTC}"
      DEBUG: "${DEBUG:-false}"
      UID: "${UID}"
      NAME: "${POLLER_TOKEN}"
      APP_SECRET: "${APP_SECRET}"
      SALT: "${SALT}"
    volumes:
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-centlog:/var/log/centreon-engine
      - ./certs/poller.crt:/etc/pki/poller.crt
      - ./certs/poller.key:/etc/pki/poller.key
    ports:
      - 4317:4317

EOF

  # gorgone base (always)
  cat >> "${out}" <<'EOF'
  gorgone:
    image: "docker.centreon.com/centreon/centreon-gorgone-bookworm:${TAG}"
    container_name: "${NAME}-gorgone"
    hostname: gorgone
    restart: unless-stopped
    environment:
      TZ: "${TZ:-UTC}"
      DEBUG: "${DEBUG:-false}"
      TYPE: poller
      UID: "${UID}"
      NAME: "${NAME}"
      POLLER_TOKEN: "${POLLER_TOKEN}"
      CENTRAL_URL: "${CENTRAL_URL}"
      APP_SECRET: "${APP_SECRET}"
      SALT: "${SALT}"
    volumes:
      - poller-etc:/etc/centreon/
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-centcache:/var/cache/centreon/
      - poller-gorgone-data:/var/lib/centreon-gorgone/
EOF

  # gorgone extra volume for snmptrap
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
      - poller-snmp-traps:/etc/snmp/centreon_traps
EOF
  fi

  printf '\n' >> "${out}"

  # centreon-vmware (optional)
  if [ "${WITH_VMWARE}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  centreon-vmware:
    image: "docker.centreon.com/centreon/centreon-vmware-bookworm:${TAG}"
    container_name: "${NAME}-vmware"
    hostname: centreon-vmware
    restart: unless-stopped
    environment:
      TZ: "${TZ:-UTC}"
      DEBUG: "${DEBUG:-false}"
    volumes:
      - poller-etc:/etc/centreon/
      - poller-engine:/etc/centreon-engine:ro

EOF
  fi

  # snmptrapd + centreontrapd (optional, always together)
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  snmptrapd:
    image: "docker.centreon.com/centreon/centreon-snmptrapd-bookworm:${TAG}"
    container_name: "${NAME}-snmptrap"
    hostname: snmptrapd
    restart: unless-stopped
    environment:
      TZ: "${TZ:-UTC}"
      DEBUG: "${DEBUG:-false}"
    volumes:
      - poller-snmp-spool:/var/spool/centreontrapd
    ports:
      - "162:162/udp"
    cap_add:
      - NET_BIND_SERVICE

  centreontrapd:
    image: "docker.centreon.com/centreon/centreon-centreontrapd-bookworm:${TAG}"
    container_name: "${NAME}-centreontrap"
    hostname: centreontrapd
    restart: unless-stopped
    environment:
      TZ: "${TZ:-UTC}"
      DEBUG: "${DEBUG:-false}"
      TRAP_SDB_PATH: /etc/snmp/centreon_traps/centreontrapd.sdb
    volumes:
      - poller-snmp-spool:/var/spool/centreontrapd
      - poller-snmp-traps:/etc/snmp/centreon_traps
      - poller-centcmd:/var/lib/centreon-engine/rw
    depends_on:
      - snmptrapd

EOF
  fi

  # Base volumes (always)
  cat >> "${out}" <<'EOF'
volumes:
  poller-etc:
  poller-engine:
  poller-broker:
  poller-centcmd:
  poller-centlog:
  poller-centcache:
  poller-gorgone-data:
EOF

  # Volumes pour snmptrap
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  poller-snmp-spool:
  poller-snmp-traps:
EOF
  fi

  if [ $? -ne 0 ]; then
    consoleError "Cannot write docker-compose.yaml file."
    logError "Cannot write docker-compose.yaml file."
    exit 1
  fi

  consoleInfo "docker-compose.yaml written"
  logInfo "docker-compose.yaml written"
}
