# Copyright 2025 - present Centreon Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function _checkDockerPrerequisites() {
  local ret=0

  if ! type docker >/dev/null 2>&1; then
    consoleError "docker is not installed or not in PATH."
    logError "docker is not installed or not in PATH."
    ret=1
  fi

  if ! docker compose version >/dev/null 2>&1; then
    consoleError "docker compose (v2 plugin) is not available. Run 'docker compose version' to verify."
    logError "docker compose plugin is not available."
    ret=1
  fi

  return ${ret}
}

function runDockerInstall() {
  echo ""
  consoleMainTitle "Generating Docker Compose files for Centreon poller"

  consoleTitle "Checking prerequisites:"
  _checkDockerPrerequisites || exit 1
  consoleInfo "docker and docker compose are available"
  echo ""

  _generateDotEnv "."
  _generateDockerCompose "."

  echo ""
  consoleTitle "Files generated:"
  consoleInfo "  docker-compose.yaml"
  consoleInfo "  .env"
  echo ""
  consoleTitle "Services included:"
  consoleInfo "  centengine, gorgone (always)"
  if [ "${WITH_VMWARE}" = "1" ]; then
    consoleInfo "  centreon-vmware (--with-vmware)"
  fi
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    consoleInfo "  snmptrapd, centreontrapd (--with-snmptrap)"
  fi
  if [ "${WITH_CMA}" = "1" ]; then
    consoleInfo "  Centreon Monitoring Agent support (--with-cma): TLS certs + port 4317"
  fi
  echo ""
  if [ "${STABILITY}" = "testing" ]; then
    consoleInfo "Stability 'testing': not starting the stack automatically."
    consoleTitle "Next steps:"
    echo "  1. Edit .env: set ENGINE_TAG/GORGONE_TAG/SNMPTRAPD_TAG/CENTREONTRAPD_TAG to the branch/tag you are testing."
    echo "  2. Start the stack:"
    echo "       docker compose up -d"
    echo "  (optional) Copy TLS certificates for Centreon Monitoring Agent:"
    echo "       mkdir -p certs && cp poller.crt certs/ && cp poller.key certs/"
    echo ""
  elif [ "${START_STACK}" = "1" ]; then
    echo ""
    consoleTitle "Starting stack:"
    docker compose up -d || { consoleError "Failed to start stack."; logError "docker compose up -d failed (exit $?)"; exit 1; }
    echo ""
  else
    consoleTitle "Next steps:"
    echo "  1. Start the stack:"
    echo "       docker compose up -d"
    echo "  (optional) Copy TLS certificates for Centreon Monitoring Agent:"
    echo "       mkdir -p certs && cp poller.crt certs/ && cp poller.key certs/"
    echo ""
  fi
}

function _generateDotEnv() {
  local dir=$1
  local effective_stability="${FORCE_STABILITY:-${STABILITY}}"
  logInfo "Generating .env in ${dir} (stability: ${effective_stability})"

  # Registry/repo selection (ghcr.io for stable, Harbor otherwise) happens in
  # _pollerImageRepo, used by _generateDockerCompose. Only the tag is decided
  # here (MON-207531 verified these tag conventions end-to-end).
  local image_tag
  if [ -n "${FORCE_TAG}" ]; then
    # Hidden --tag override: use verbatim, regardless of STABILITY/FORCE_REGISTRY/FORCE_STABILITY.
    image_tag="${FORCE_TAG}"
  elif [ "${FORCE_REGISTRY}" = "harbor" ]; then
    # Default candidate once --registry harbor is used without --tag: the
    # release-<major>-next branch tag. centreon-collect has its own patch
    # versioning (independent of centreon-web's), so the exact validated
    # semver retag (e.g. 26.10.3) isn't derivable here — override with
    # --tag <major>.<minor>.<patch> once you know it (after promote-docker-tag
    # has run for that patch).
    image_tag="release-$(_pollerImageMajor)-next"
  else
    case "${effective_stability}" in
    stable)
      image_tag="$(_pollerImageMajor)"
      ;;
    unstable)
      image_tag="develop"
      ;;
    testing)
      image_tag="SET_ME_PER_COMPONENT"
      consoleInfo "Stability 'testing' has no single shared image tag (testing builds are tagged per-component/per-branch)."
      consoleInfo "Edit ENGINE_TAG/GORGONE_TAG/SNMPTRAPD_TAG/CENTREONTRAPD_TAG in .env to the branch/tag you are validating before starting the stack."
      ;;
    esac
  fi

  cat > "${dir}/.env" <<EOF
# Generated by install-poller $(date -u +%Y-%m-%dT%H:%M:%SZ)

TAG=${image_tag}
# Per-service tag overrides (leave empty to use TAG for all)
ENGINE_TAG=
GORGONE_TAG=
SNMPTRAPD_TAG=
CENTREONTRAPD_TAG=
VMWARE_TAG=

TZ=${TZ:-UTC}
DEBUG=${DEBUG:-false}

NAME=${POLLER_NAME}
GORGONE_UID=${GORGONE_UID}
CENTRAL_HOST=${GORGONE_ADDRESS}
CENTRAL_PORT=${CENTRAL_PORT}
ENGINE_PORT=${ENGINE_PORT}
GORGONE_TOKEN=${GORGONE_TOKEN}
GORGONE_SSL=${GORGONE_SSL}
GORGONE__GORGONE__MODULES__PULLWSS__CENTRAL_URI=${GORGONE_PULLWSS_CENTRAL_URI}

APP_SECRET=${APP_SECRET}
SALT=${SALT}
EOF

  if [ $? -ne 0 ]; then
    consoleError "Cannot write .env file."
    logError "Cannot write .env file."
    exit 1
  fi

  consoleInfo ".env written"
  logInfo ".env written"
}

# Whether a Centreon major version (e.g. 26.10) is an on-prem release.
# On-prem majors always end in .10; anything else is a cloud release. Same
# heuristic as get-environment.yml's cloud/on-prem detection and
# uses_internal_repo() in centreon/unattended.sh (mirrored in
# _usesInternalRepo, src/vm/packages.sh) — shared here so both the Docker and
# VM install paths classify a major the same way.
function _isOnPremMajor() {
  [[ "${1}" == *.10 ]]
}

# The on-prem major this release's containerized pollers come from. On-prem
# majors are used as-is. A cloud major pulls the nearest not-later on-prem
# major, floored at 26.10 (MON-192897: no containerized poller exists before
# that release). MON-208333.
#
# Unlike _usesInternalRepo (VM/RPM path), this doesn't just switch the
# registry at the same major: RPM/DEB packages ARE published for cloud majors
# (to an internal repo, per .github/actions/promote-to-stable), but poller
# container images are only ever published for on-prem majors — so a cloud
# major has to resolve to a *different*, older major here.
function _pollerImageMajor() {
  if _isOnPremMajor "${major}"; then
    echo "${major}"
    return
  fi
  local year=$((10#${major%%.*}))
  local month=$((10#${major##*.}))
  local onprem_year=${year}
  [ "${month}" -lt 10 ] && onprem_year=$((year - 1))
  [ "${onprem_year}" -lt 26 ] && onprem_year=26
  printf "%02d.10" "${onprem_year}"
}

# Registry + repo (no tag) for one of the 5 poller component images, per
# stability. Only 'stable' is published to ghcr.io (MON-207531); testing and
# unstable stay on Harbor, as neither ever gets a validated stable-equivalent
# tag there. FORCE_REGISTRY (hidden --registry flag) overrides STABILITY here
# to let QA pull a release-candidate image from Harbor before ghcr promotion;
# FORCE_STABILITY (hidden --stability flag) is the fallback under it.
function _pollerImageRepo() {
  local component=$1
  if [ "${FORCE_REGISTRY:-${FORCE_STABILITY:-${STABILITY}}}" = "stable" ] || [ "${FORCE_REGISTRY}" = "ghcr" ]; then
    echo "ghcr.io/centreon/centreon-${component}"
  else
    echo "docker.centreon.com/centreon/centreon-${component}-trixie"
  fi
}

function _generateDockerCompose() {
  local dir=$1
  local out="${dir}/docker-compose.yaml"
  logInfo "Generating docker-compose.yaml in ${dir} (vmware=${WITH_VMWARE}, snmptrap=${WITH_SNMPTRAP})"

  # centengine (always)
  cat > "${out}" <<'EOF'
services:
  centengine:
EOF
  printf '    image: "%s:${ENGINE_TAG:-${TAG}}"\n' "$(_pollerImageRepo engine)" >> "${out}"
  cat >> "${out}" <<'EOF'
    container_name: "${NAME}-centengine"
    hostname: centengine
    restart: unless-stopped
    environment:
      NAME: "${NAME}"
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
      ENGINE_PORT: "${ENGINE_PORT}"
      APP_SECRET: "${APP_SECRET}"
      SALT: "${SALT}"
    volumes:
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-centlog:/var/log/centreon-engine
EOF

  # Centreon Monitoring Agent (optional): TLS cert mounts + gRPC port
  if [ "${WITH_CMA}" = "1" ]; then
    cat >> "${out}" <<'EOF'
      - ./certs/poller.crt:/etc/pki/poller.crt
      - ./certs/poller.key:/etc/pki/poller.key
    ports:
      - 4317:4317
EOF
  fi

  # centengine healthcheck + dependencies (always)
  cat >> "${out}" <<'EOF'
    healthcheck:
      test: ["CMD-SHELL", "grep -q \":$$(printf '%04X' $${ENGINE_PORT:-443}) 01\" /proc/net/tcp /proc/net/tcp6 2>/dev/null"]
      interval: 30s
      timeout: 5s
      start_period: 5m
      retries: 3
    depends_on:
      gorgone:
        condition: service_healthy
EOF

  # gorgone base volumes (always)
  cat >> "${out}" <<'EOF'
  gorgone:
EOF
  printf '    image: "%s:${GORGONE_TAG:-${TAG}}"\n' "$(_pollerImageRepo gorgone)" >> "${out}"
  cat >> "${out}" <<'EOF'
    container_name: "${NAME}-gorgone"
    hostname: gorgone
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
      TYPE: poller
      GORGONE_UID: "${GORGONE_UID}"
      NAME: "${NAME}"
      GORGONE_TOKEN: "${GORGONE_TOKEN}"
      CENTRAL_HOST: "${CENTRAL_HOST}"
      CENTRAL_PORT: "${CENTRAL_PORT}"
      GORGONE__GORGONE__MODULES__PULLWSS__SSL: "${GORGONE_SSL}"
      GORGONE__GORGONE__MODULES__PULLWSS__CENTRAL_URI: "${GORGONE__GORGONE__MODULES__PULLWSS__CENTRAL_URI}"
      APP_SECRET: "${APP_SECRET}"
      SALT: "${SALT}"
    volumes:
      - poller-etc:/etc/centreon/
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-gorgone-data:/var/lib/centreon-gorgone/
EOF

  # gorgone extra volume for snmptrap
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
      - poller-snmp-traps:/etc/snmp/centreon_traps
EOF
  fi

  # gorgone healthcheck (always, after volumes)
  cat >> "${out}" <<'EOF'
    healthcheck:
      test: ["CMD-SHELL", "grep -q \":$$(printf '%04X' $${CENTRAL_PORT:-443}) 01\" /proc/net/tcp /proc/net/tcp6 2>/dev/null"]
      interval: 30s
      timeout: 5s
      start_period: 30m
      retries: 3
EOF

  printf '\n' >> "${out}"

  # centreon-vmware (optional)
  if [ "${WITH_VMWARE}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  centreon-vmware:
    image: "connector-vmware:${VMWARE_TAG:-local}"
    container_name: "${NAME}-vmware"
    hostname: centreon-vmware
    restart: unless-stopped
    pull_policy: never
    environment:
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
      APP_SECRET: "${APP_SECRET}"
      SALT: "${SALT}"
    volumes:
      - poller-etc:/etc/centreon/
    depends_on:
      gorgone:
        condition: service_healthy

EOF
  fi

  # snmptrapd + centreontrapd (optional, always together)
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  snmptrapd:
EOF
    printf '    image: "%s:${SNMPTRAPD_TAG:-${TAG}}"\n' "$(_pollerImageRepo snmptrapd)" >> "${out}"
    cat >> "${out}" <<'EOF'
    container_name: "${NAME}-snmptrap"
    hostname: snmptrapd
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
    volumes:
      - poller-snmp-spool:/var/spool/centreontrapd
    ports:
      - "162:162/udp"
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD-SHELL", "grep -q ':00A2' /proc/net/udp /proc/net/udp6 2>/dev/null"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

  centreontrapd:
EOF
    printf '    image: "%s:${CENTREONTRAPD_TAG:-${TAG}}"\n' "$(_pollerImageRepo centreontrapd)" >> "${out}"
    cat >> "${out}" <<'EOF'
    container_name: "${NAME}-centreontrap"
    hostname: centreontrapd
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      DEBUG: "${DEBUG}"
    volumes:
      - poller-snmp-spool:/var/spool/centreontrapd
      - poller-snmp-traps:/etc/snmp/centreon_traps:ro
      - poller-centcmd:/var/lib/centreon-engine/rw
    depends_on:
      snmptrapd:
        condition: service_healthy
      gorgone:
        condition: service_healthy

EOF
  fi

  # Base volumes (always)
  cat >> "${out}" <<'EOF'
volumes:
  poller-etc:
  poller-engine:
  poller-broker:
  poller-centcmd:
  poller-centlog:
  poller-gorgone-data:
EOF

  # Volumes pour snmptrap
  if [ "${WITH_SNMPTRAP}" = "1" ]; then
    cat >> "${out}" <<'EOF'
  poller-snmp-spool:
  poller-snmp-traps:
EOF
  fi

  if [ $? -ne 0 ]; then
    consoleError "Cannot write docker-compose.yaml file."
    logError "Cannot write docker-compose.yaml file."
    exit 1
  fi

  consoleInfo "docker-compose.yaml written"
  logInfo "docker-compose.yaml written"
}
