ARG VERSION

FROM almalinux:9 AS web_dependencies

ARG VERSION
ARG IS_CLOUD
ARG STABILITY

RUN --mount=type=secret,id=ARTIFACTORY_INTERNAL_REPO_USERNAME \
    --mount=type=secret,id=ARTIFACTORY_INTERNAL_REPO_PASSWORD \
    bash -e <<EOF

######################################
# install and configure repositories #
######################################

echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf

dnf install -y dnf-plugins-core

dnf config-manager --set-enabled crb

dnf install -y epel-release

if [[ "${IS_CLOUD}" == "true" ]]; then
  dnf config-manager --add-repo https://$(cat /run/secrets/ARTIFACTORY_INTERNAL_REPO_USERNAME):$(cat /run/secrets/ARTIFACTORY_INTERNAL_REPO_PASSWORD)@packages.centreon.com/rpm-standard-internal/${VERSION}/el9/centreon-${VERSION}-internal.repo
  sed -i "s#packages.centreon.com/rpm-standard-internal#$(cat /run/secrets/ARTIFACTORY_INTERNAL_REPO_USERNAME):$(cat /run/secrets/ARTIFACTORY_INTERNAL_REPO_PASSWORD)@packages.centreon.com/rpm-standard-internal#" /etc/yum.repos.d/centreon-${VERSION}-internal.repo
else
  dnf config-manager --add-repo https://packages.centreon.com/rpm-standard/${VERSION}/el9/centreon-${VERSION}.repo
fi

dnf config-manager --set-enabled 'centreon*'

if [[ "$STABILITY" == "testing" ]]; then
  dnf config-manager --set-disabled 'centreon*unstable*'
elif [[ "$STABILITY" == "stable" ]]; then
  dnf config-manager --set-disabled 'centreon*unstable*' --set-disabled 'centreon*testing*'
fi

#############################
# install base dependencies #
#############################

dnf install -y \
  bc \
  brotli \
  bzip2 \
  cronie \
  httpd \
  initscripts \
  jq \
  libsodium \
  libunwind \
  lua \
  openpgm \
  net-snmp \
  net-snmp-utils \
  openssl \
  python3 \
  rrdtool \
  rrdtool-perl \
  rsync \
  sed \
  sudo \
  zeromq

#############################
# install perl dependencies #
#############################

dnf install -y \
  perl-interpreter \
  perl-DBD-MySQL \
  perl-DBD-SQLite \
  perl-DBI \
  perl-HTML-Parser \
  perl-Net-Curl \
  perl-lib \
  perl-Env

#############################
# install test dependencies #
#############################

dnf install -y libfaketime

############################
# install php dependencies #
############################

dnf module enable -y php:8.2
dnf install -y \
  php-common \
  php-cli \
  php-pdo \
  php-mysqlnd \
  php-gd \
  php-xml \
  php-mbstring \
  php-ldap \
  php-snmp \
  php-intl \
  php-fpm \
  php-curl \
  php-zip \
  php-pear \
  php-json

###################
# install plugins #
###################

dnf install -y centreon-plugin-Operatingsystems-Linux-Snmp

######################
# SNMP configuration #
######################

sed -i '/^agentaddress/d' /etc/snmp/snmpd.conf
echo 'agentaddress  127.0.0.1' >> /etc/snmp/snmpd.conf

dnf clean all --enablerepo=*

EOF

COPY --chmod=755 ./.github/docker/centreon-web/init/systemctl /bin/systemctl

COPY --chmod=755 ./.github/docker/centreon-web/init/* /etc/init.d/

FROM web_dependencies AS web_dependencies_collect

RUN bash -e <<EOF

dnf install -y wget

mkdir -p /tmp/packages-collect
cd /tmp/packages-collect

wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-broker-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-broker-cbd-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-broker-core-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-broker-graphite-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-broker-influxdb-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-broker-selinux-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-clib-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-collect-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-collect-client-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-connector-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-connector-perl-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-connector-ssh-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-engine-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-engine-daemon-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-engine-opentelemetry-25.05.0-1746623347.286f827.el9.x86_64.rpm
wget https://centreon.jfrog.io/artifactory/installers/centreon-collect/MON-167934-module-cfg-file/centreon-engine-selinux-25.05.0-1746623347.286f827.el9.x86_64.rpm

dnf install -y ./centreon*.rpm centreon-common centreon-gorgone

# dnf install -y \
#   centreon-common \
#   centreon-gorgone \
#   centreon-engine \
#   centreon-broker-cbd \
#   centreon-connector

dnf clean all --enablerepo=*

EOF
