ARG REGISTRY_URL=docker.centreon.com/centreon
ARG FROM_IMAGE_VERSION=develop
ARG MAJOR_VERSION
ARG AWIE_MINOR_VERSION
ARG DSM_MINOR_VERSION
ARG HA_MINOR_VERSION
ARG OPEN-TICKETS_MINOR_VERSION
ARG STABILITY

FROM ${REGISTRY_URL}/centreon-web-alma9:${FROM_IMAGE_VERSION}

RUN bash -e <<EOF

if [[ "$STABILITY" == "stable" ]]; then
  dnf install -y \
    centreon-awie-${MAJOR_VERSION}.${AWIE_MINOR_VERSION} \
    centreon-dsm-${MAJOR_VERSION}.${DSM_MINOR_VERSION} \
    centreon-ha-${MAJOR_VERSION}.${HA_MINOR_VERSION} \
    centreon-open-tickets-${MAJOR_VERSION}.${OPEN-TICKETS_MINOR_VERSION}
else
  dnf install -y /tmp/packages-centreon/centreon-*.rpm
fi

cat <<EOT >> /usr/share/centreon/container.d/81-oss.sh
#!/bin/sh
for MODULE in "centreon-dsm" "centreon-awie" "centreon-open-tickets" "centreon-ha"; do
  su apache -s /bin/bash -c "/tmp/install-centreon-module.php -b /usr/share/centreon/bootstrap.php -m $MODULE"
fi
EOT

EOF
