#!/bin/bash
#
# Shared helpers for the centreon-trapd e2e test scripts. Sourced, not
# executed directly.

# Builds a minimal centreontrapd.sdb fixture and prints its path on stdout.
# Even in mode=1 (poller/SQLite), centreontrapd queries centreontrapd.sdb for
# cfg_nagios.command_file on startup and crash-loops without at least that
# table populated. In production this file is generated by
# centreon/bin/generateSqlLite from the real MySQL config - see
# fixtures/centreontrapd-sdb.sql for the seeded equivalent.
#
# Called as `var=$(build_centreontrapd_sdb_fixture ...)` by both callers -
# command substitutions run in a subshell that does NOT inherit the caller's
# `set -e` by default, so failures here are checked explicitly rather than
# relying on errexit: a path is only echoed (and thus only assigned to the
# caller's variable) once every step has succeeded. Callers must still check
# this function's own exit status (e.g. `... || exit 1`).
build_centreontrapd_sdb_fixture() {
  local prefix="$1"
  local sdb_tmp
  if ! sdb_tmp=$(mktemp "/tmp/${prefix}-XXXXXX.sdb"); then
    echo "::error::mktemp failed while creating the centreontrapd.sdb fixture" >&2
    return 1
  fi
  if ! sqlite3 "$sdb_tmp" < .github/docker/centreon-trapd/fixtures/centreontrapd-sdb.sql; then
    echo "::error::sqlite3 failed to build the centreontrapd.sdb fixture" >&2
    return 1
  fi
  # mktemp defaults to mode 600 (owner-only) - the container's "centreon"
  # user (uid 900) doesn't match the runner's uid on the bind-mounted file,
  # so it can't open it unless it's world-readable/writable.
  if ! chmod 666 "$sdb_tmp"; then
    echo "::error::chmod failed on the centreontrapd.sdb fixture" >&2
    return 1
  fi
  echo "$sdb_tmp"
}

# --- GitHub Step Summary helpers ----------------------------------------
#
# Renders the test's checks as a markdown table in the job's Step Summary
# (visible in the GitHub Actions run UI), on top of the plain-text console
# output these scripts already produce. Usage:
#
#   summary_step_start "Human-readable check name"
#   <run the check>
#   summary_step_pass
#
# Call in order, one pair per check. A check that fails (script exits before
# its matching summary_step_pass) is rendered as failed; checks after it were
# never attempted and simply don't appear in the table. Callers must render
# the table from their own EXIT trap with `_summary_render "<title>" "$rc"`,
# capturing `rc=$?` as the trap's *first* statement so it reflects the
# original exit status rather than the trap's own commands.
SUMMARY_STEP_NAMES=()
SUMMARY_STEP_STATUS=()

summary_step_start() {
  SUMMARY_STEP_NAMES+=("$1")
  SUMMARY_STEP_STATUS+=("pending")
}

summary_step_pass() {
  local last=$(( ${#SUMMARY_STEP_STATUS[@]} - 1 ))
  SUMMARY_STEP_STATUS[$last]="pass"
}

_summary_render() {
  local title="$1" exit_code="$2"
  {
    echo "### ${title}"
    echo
    echo "| Check | Result |"
    echo "| --- | --- |"
    local i icon
    for i in "${!SUMMARY_STEP_NAMES[@]}"; do
      if [ "${SUMMARY_STEP_STATUS[$i]}" = "pass" ]; then
        icon="✅"
      else
        icon="❌"
      fi
      echo "| ${SUMMARY_STEP_NAMES[$i]} | ${icon} |"
    done
    echo
    if [ "$exit_code" -eq 0 ]; then
      echo "**Result: ✅ PASSED**"
    else
      echo "**Result: ❌ FAILED** (exit code ${exit_code})"
    fi
    echo
  } >> "${GITHUB_STEP_SUMMARY:-/dev/null}"
}
