#!/bin/bash
#
# Shared helpers for the centreon-trapd e2e test scripts. Sourced, not
# executed directly.

# Builds a minimal centreontrapd.sdb fixture and prints its path on stdout.
# Even in mode=1 (poller/SQLite), centreontrapd queries centreontrapd.sdb for
# cfg_nagios.command_file on startup and crash-loops without at least that
# table populated. In production this file is generated by
# centreon/bin/generateSqlLite from the real MySQL config - see
# fixtures/centreontrapd-sdb.sql for the seeded equivalent.
build_centreontrapd_sdb_fixture() {
  local prefix="$1"
  local sdb_tmp
  sdb_tmp=$(mktemp "/tmp/${prefix}-XXXXXX.sdb")
  sqlite3 "$sdb_tmp" < .github/docker/centreon-trapd/fixtures/centreontrapd-sdb.sql
  # mktemp defaults to mode 600 (owner-only) - the container's "centreon"
  # user (uid 900) doesn't match the runner's uid on the bind-mounted file,
  # so it can't open it unless it's world-readable/writable.
  chmod 666 "$sdb_tmp"
  echo "$sdb_tmp"
}
