#!/bin/bash
#
# Shared helpers for the centreon-trapd e2e test scripts. Sourced, not
# executed directly.

# Builds a minimal centreontrapd.sdb fixture and prints its path on stdout.
# Even in mode=1 (poller/SQLite), centreontrapd queries centreontrapd.sdb for
# cfg_nagios.command_file on startup and crash-loops without at least that
# table populated. In production this file is generated by
# centreon/bin/generateSqlLite from the real MySQL config - see
# fixtures/centreontrapd-sdb.sql for the seeded equivalent.
#
# Called as `var=$(build_centreontrapd_sdb_fixture ...)` by both callers -
# command substitutions run in a subshell that does NOT inherit the caller's
# `set -e` by default, so failures here are checked explicitly rather than
# relying on errexit: a path is only echoed (and thus only assigned to the
# caller's variable) once every step has succeeded. Callers must still check
# this function's own exit status (e.g. `... || exit 1`).
build_centreontrapd_sdb_fixture() {
  local prefix="$1"
  local sdb_tmp
  if ! sdb_tmp=$(mktemp "/tmp/${prefix}-XXXXXX.sdb"); then
    echo "::error::mktemp failed while creating the centreontrapd.sdb fixture" >&2
    return 1
  fi
  if ! sqlite3 "$sdb_tmp" < .github/docker/centreon-trapd/fixtures/centreontrapd-sdb.sql; then
    echo "::error::sqlite3 failed to build the centreontrapd.sdb fixture" >&2
    return 1
  fi
  # mktemp defaults to mode 600 (owner-only) - the container's "centreon"
  # user (uid 900) doesn't match the runner's uid on the bind-mounted file,
  # so it can't open it unless it's world-readable/writable.
  if ! chmod 666 "$sdb_tmp"; then
    echo "::error::chmod failed on the centreontrapd.sdb fixture" >&2
    return 1
  fi
  echo "$sdb_tmp"
}
