ARG REGISTRY_URL=docker.centreon.com/centreon
ARG FROM_IMAGE_VERSION=develop

FROM ${REGISTRY_URL}/centreon-web-noble:${FROM_IMAGE_VERSION}

ARG MAJOR_VERSION
ARG AWIE_MINOR_VERSION
ARG DSM_MINOR_VERSION
ARG OPEN_TICKETS_MINOR_VERSION
ARG STABILITY

RUN bash -e <<EOF

if [[ "$STABILITY" == "stable" ]]; then
  apt-get install -y \
    centreon-awie=${MAJOR_VERSION}.${AWIE_MINOR_VERSION}-*+ubuntu.24.04 \
    centreon-dsm=${MAJOR_VERSION}.${DSM_MINOR_VERSION}-*+ubuntu.24.04 \
    centreon-open-tickets=${MAJOR_VERSION}.${OPEN_TICKETS_MINOR_VERSION}-*+ubuntu.24.04
else
  apt-get install -y /tmp/packages-centreon/centreon-*.deb
fi

cat <<EOT >> /usr/share/centreon/container.d/81-oss.sh
#!/bin/sh
for MODULE in "centreon-dsm" "centreon-awie" "centreon-open-tickets"; do
  su www-data -s /bin/bash -c "/tmp/install-centreon-module.php -b /usr/share/centreon/bootstrap.php -m -m \$MODULE"
done
EOT

chmod +x /usr/share/centreon/container.d/81-oss.sh
EOF
