export const labelHosts = 'Hosts';
export const labelDownStatusHosts = 'Down status hosts';
export const labelUnreachableStatusHosts = 'Unreachable status hosts';
export const labelUpStatusHosts = 'Up status hosts';
export const labelAll = 'All';
export const labelDown = 'Down';
export const labelPending = 'Pending';
export const labelUnreachable = 'Unreachable';
export const labelUp = 'Up';
