<?php
_("Top/bottom");
_("Displays the top or bottom x hosts, for a selected metric.");
_("Top Bottom Settings");
_("Value format");
_("threshold");
_("Interval");
_("Generic data for single metric (example)");
_("This is the description of the data widget");
_("Generic text");
_("Allows you to add free text to your dashboards (section titles, information, etc.).");
_("Resource table");
_("Displays data on resource status and events, centralized in a table.");
_("Display resources with this status");
_("Display resources with this state");
_("Display resources with these status types");
_("Host severities");
_("Select host severities");
_("Service severities");
_("Select service severities");
_("If ticket management is enabled, only the “by service” view is available.");
_("Enable ticket management");
_("Rule (ticket provider)");
_("Select rule (ticket provider)");
_("Display resources");
_("Hide services with Down host");
_("Hide services with Unreachable host");
_("Clock / Timer");
_("Displays the time according to the selected time zone, or a timer.");
_("Clock");
_("Timer");
_("Show time zone");
_("Show date");
_("Status chart");
_("Displays a detailed view of the current status for selected resources as a chart.");
_("Donut chart");
_("Pie chart");
_("Horizontal bar chart");
_("Vertical bar chart");
_("Display resources with this type");
_("Display resources with this unit");
_("Show value on chart");
_("Show legend");
_("Legend");
_("Status grid");
_("Displays a status overview for selected resources, grouped by hosts or by services.");
_("Display with this view");
_("Sort by");
_("Web page");
_("Displays a web page");
_("URL");
_("Please note that domains outside your organization must be authorized in your Apache configuration.");
_("Single metric");
_("Displays the value of a single metric as a text, a gauge or a bar chart.");
_("Text");
_("Gauge");
_("Bar");
_("Group monitoring");
_("Displays the distribution of current statuses on selected groups of resources, as a table.");
_("Generic data (example)");
_("Select field");
_("Radio");
_("Group");
_("Sub input 1");
_("Sub input 2");
_("Sub input 3");
_("Generic text (example)");
_("This is the description of the text widget");
_("Metrics graph");
_("Displays metrics for a given time period.");
_("Line");
_("Stacked bar");
_("Curve type");
_("Display curve points");
_("Line width");
_("Auto: Default value defined for the corresponding curve template (Monitoring > Performances > Curves).");
_("Area");
_("Fill opacity");
_("Line style");
_("Dash width");
_("Space");
_("px");
_("Orientation");
_("Bar radius");
_("Bar opacity");
_("Show axis borders");
_("Y-axis label rotation");
_("Zero-centered");
_("Show gridlines");
_("Gridline type");
_("Scale");
_("Display mode");
_("Position");
_("Display");
_("Value sort order");
_("Business Activity Diagram");
_("Displays graphically a business activity hierarchy of KPIs and lets you navigate through it.");
_("Display the diagram with this status");
_("Link types");
_("Generic input (example)");
_("This is the description of the generic input widget");
?>
