<?php
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/App/translatedLabels.ts */
_("You are disconnected");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/federatedModules/translatedLabels.ts */
_("Cannot load module");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/VaultConfiguration/translatedLabels.ts */
_("Vault configuration");
_("The address is invalid");
_("Required");
_("Vault address");
_("Port");
_("Root path");
_("Role ID");
_("Secret ID");
_("Reset");
_("Save");
_("Cancel");
_("Reset configuration");
_("The form will be cleared and all data will be lost. Do you want to proceed?");
_("Port number must be at most 65535");
_("Vault configuration updated");
_("Port number must be at least 1");
_("Migrate");
_("Migration script");
_("Execute this script as root on the central.");
_("The following script will migrate all your credentials from Centreon, Auto-discovery and the database.");
_("By executing this script, your platform will be in a locked mode and you will not be able to do <strong>anything</strong> during the migration process (example: deploying your configuration, updating administration parameters, etc...).");
_("The migration process can take several minutes depending on your configuration.");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/ApiTokens/translatedLabels.ts */
_("Search");
_("Create new token");
_("Revoked");
_("Active");
_("Filter options");
_("Delete");
_("API token");
_("Generate new token");
_("Close");
_("Name");
_("Duration");
_("User");
_("Token copied to the clipboard");
_("Token could not be copied");
_("The end date must be greater than the current date by at least one day");
_("This field is required");
_("Token");
_("Ok");
_("Cancel");
_("Token has been created");
_("For security reasons, the token can only be displayed once. Store it carefully.");
_("Creator");
_("You are about to delete the token <b> {{tokenName}}</b>. This action <br> cannot be undone. If you proceed, all requests made using this token will be <br> rejected. Do you want to delete the token?");
_("Delete token");
_("Token deleted successfully");
_("Active tokens");
_("Disabled tokens");
_("Status");
_("Creation date");
_("Expiration date");
_("Clear");
_("Until");
_("Active/Revoked");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/FallbackPages/AuthenticationDenied/translatedLabels.ts */
_("Authentication denied");
_("You are not allowed to log in");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/FallbackPages/NotAllowedPage/translatedLabels.ts */
_("You are not allowed to see this page");
_("Lost in space?");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/FallbackPages/NotFoundPage/translatedLabels.ts */
_("This page could not be found");
_("Oops");
_("Please contact your administrator.");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/ResourceAccessManagement/translatedLabels.ts */
_("Resource access rules");
_("Name");
_("Description");
_("Actions");
_("Status");
_("Search");
_("Add");
_("Create a new resource access rule");
_("Edit resource access rule");
_("Rule properties");
_("Add resource datasets");
_("Contacts");
_("Contact Groups");
_("Contacts/Contact groups");
_("The resource access rule was successfully created");
_("The resource access rule was successfully updated");
_("Required");
_("This name already exists");
_("Save");
_("Exit");
_("Add new dataset");
_("Add filter");
_("Choose at least one contact or contact group");
_("Host");
_("Host category");
_("Host group");
_("Metaservice");
_("Service");
_("Service category");
_("Service group");
_("Please select a resource");
_("Delete");
_("Select resource type");
_("Select resource");
_("Active / Inactive");
_("Enabled");
_("Disabled");
_("Delete rule");
_("Cancel");
_("is used to allow users to access resources.");
_("It will be permanently deleted and users will no longer have this permission.");
_("Failed to delete the resource access rule");
_("The resource access rule has been successfully deleted");
_("Delete multiple resource access rules");
_("Failed to delete the selected resource access rules");
_("The selected resource access rules have been deleted successfully");
_("Rules are used to allow users to access resources.");
_("They will be permanently deleted and users will no longer have these permissions.");
_("Delete rules");
_("Duplicate");
_("Failed to duplicate the resource access rule");
_("The resource access rule has been successfully duplicated");
_("Resource access rule name");
_("Please enter a name for the duplicated resource access rule");
_("All resources");
_("All resources selected");
_("All hosts selected");
_("All host groups selected");
_("All service groups selected");
_("All hosts");
_("All host groups");
_("All service groups");
_("Business view");
_("All business views");
_("All business views selected");
_("All contacts");
_("All contacts selected");
_("All contact groups");
_("All contact groups selected");
_("Do you want to quit the form without saving the changes?");
_("Your form has unsaved changes");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Resources/translatedLabels.ts */
_("Acknowledged");
_("Acknowledge");
_("Acknowledged by");
_("Acknowledge services attached to host");
_("at");
_("Active");
_("Add");
_("All");
_("Author");
_("Comment");
_("Cancel");
_("Clear");
_("Criterias");
_("Critical");
_("Check duration");
_("Command");
_("Copy");
_("Command copied to clipboard");
_("Current notification number");
_("Current status duration");
_("Details");
_("Down");
_("Downtime duration");
_("Duration");
_("Seconds");
_("Minutes");
_("Hours");
_("End time");
_("Entry time");
_("Filter");
_("No data available for this period");
_("This resource is flapping");
_("Flapping");
_("Show criterias filters");
_("From");
_("Start date");
_("End date");
_("Change start date");
_("Change start time");
_("Change end date");
_("Change end time");
_("Fixed");
_("Graph");
_("Host");
_("Host group");
_("Downtime");
_("In downtime");
_("1 day");
_("7 days");
_("31 days");
_("Last day");
_("Last 7 days");
_("Last 31 days");
_("Set downtime");
_("Set downtime on");
_("Downtime set by");
_("Set downtime on services attached to host");
_("Check");
_("Last check");
_("Last notification");
_("Last status change");
_("Latency");
_("Less");
_("Next check");
_("No");
_("Notify");
_("If checked, a notification is sent to the contacts linked to the object to warn that the incident on the resource has been acknowledged");
_("Ok");
_("Open");
_("Status change percentage");
_("Performance data");
_("Persistent");
_("Pending");
_("Monitoring server");
_("Required");
_("Resource name");
_("All alerts");
_("Resource");
_("Rows per page");
_("of");
_("Search");
_("Severity");
_("Status");
_("Sticky");
_("Sticky for any non-OK status");
_("Tries");
_("Information");
_("More");
_("Refresh");
_("Disable autorefresh");
_("Enable autorefresh");
_("Search help");
_("This search bar will search matching occurences you type, contained in: host name or alias or address or service description");
_("You can use regular expression syntax to retrieve more relevant results");
_("It's possible to specify the criteria you precisely want to search, by using the following syntax:");
_("Some examples:");
_("will display resources with host name starting by");
_("will display resources with service description finishing by");
_("will display all resources with host having alias containing");
_("will display resources having FQDN that doesn't contain");
_("and host alias containing");
_("Tips");
_("get some help while creating your regular expression query at");
_("Service");
_("Services");
_("Service group");
_("Start time");
_("State");
_("State filter");
_("Status information");
_("Timezone");
_("To");
_("Acknowledge command sent");
_("Downtime command sent");
_("Check command sent ! Please refresh the listing to update the data.");
_("Type of resource");
_("Unhandled alerts");
_("Unhandled");
_("Unreachable");
_("Unknown");
_("Up");
_("Yes");
_("Oops, something went wrong");
_("Warning");
_("Seems that your Apache configuration is not up-to-date");
_("Contact your Centreon administrator or update the following file");
_("See Documentation");
_("Services will not be affected because you don't have sufficient permission");
_("Hosts will not be affected because you don't have sufficient permission");
_("No results found");
_("Save filter");
_("Save as new");
_("Save");
_("New filter");
_("Update filter");
_("Name");
_("Filter created");
_("Filter saved");
_("My filters");
_("Manage filters");
_("Rename");
_("Delete");
_("Delete filter?");
_("Filter deleted");
_("Filter updated");
_("Name cannot be empty");
_("Timeline");
_("Event");
_("Acknowledgement");
_("by");
_("Notification sent to");
_("Notification");
_("Shortcuts");
_("Configure");
_("View logs");
_("View report");
_("Copy the link to this resource");
_("Resource link copied to the clipboard");
_("Disacknowledge");
_("More actions");
_("Disacknowledge services attached to hosts");
_("Disacknowledgement command sent");
_("Submit a status");
_("Submit");
_("Status submitted");
_("Output");
_("No resource found");
_("FQDN / Address");
_("Alias");
_("URL");
_("Switch to graph mode");
_("Switch to list mode");
_("No data for");
_("Groups");
_("Add a comment");
_("Comment added");
_("Display events");
_("Export to png");
_("Go to performance page");
_("Parent");
_("Parent name");
_("Select criterias");
_("Forward");
_("Backward");
_("The end date must be greater than the start date");
_("Graph options");
_("Min");
_("Max");
_("Avg");
_("Compact time period");
_("Action");
_("Notes");
_("All checks are disabled");
_("Only passive checks are enabled");
_("Notifications disabled");
_("Notifications enabled");
_("Metrics");
_("Meta-Service");
_("Calculation type");
_("At least one column must be selected");
_("The duration must be less than a year");
_("Filter options");
_("Display the complete graph");
_("Action not permitted");
_("Scroll to top");
_("Today");
_("Yesterday");
_("This week");
_("Last week");
_("Last month");
_("Last year");
_("Before last year");
_("Service graphs");
_("Clear filter");
_("Last check with OK status");
_("Status type");
_("Hard");
_("Soft");
_("Invalid format");
_("Type");
_("E-mail");
_("Contacts");
_("Contact groups");
_("Settings");
_("Notification status");
_("Configuration");
_("You are not authorized to access the configuration");
_("Force active checks");
_("No contacts are configured for this resource");
_("No contact groups are configured for this resource");
_("Parent alias");
_("Categories");
_("Host category");
_("Service category");
_("Export to CSV");
_("Service severity");
_("Host severity");
_("Host severity level");
_("Service severity level");
_("CSV");
_("Export");
_("Export as");
_("PNG (as displayed)");
_("PNG (medium size)");
_("PNG (small size)");
_("Edit anomaly detection data");
_("Anomaly detection");
_("Edit anomaly detection data");
_("Are you sure you want to change the size of the envelope? The new envelope size will be applied immediately.");
_("Manage envelope size");
_("Changes to the envelope size will be applied immediately");
_("Reset to default value");
_("points outside of the envelope");
_("Close");
_("Search bar");
_("Slider");
_("Close edit modal");
_("Edit modal");
_("Modal confirmation");
_("Forced check");
_("Check selected resources only within configured check period");
_("Check selected resources even outside configured check period");
_("Forced check command sent ! Please refresh the listing to update the data.");
_("Unit");
_("Need help with search bar usage?");
_("Find explanations and examples");
_("here");
_("Display view:");
_("View all resources");
_("View by host");
_("View by service");
_("Forced check command sent !");
_("Check command sent !");
_("Check this resource only within configured check period");
_("Check this resource even outside configured check period");
_("Your comment has been saved.");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Resources/Filter/criteriasNewInterface/translatedLabels.ts */
_("Show more filters");
_("Show fewer filters");
_("Update");
_("Save as");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/PollerWizard/translatedLabels.ts */
_("Export generation timeout");
_("Add advanced server configuration");
_("Create new Poller");
_("Select a Poller");
_("Select Pending Poller IP");
_("Do not check SSL certificate validation");
_("Creating Export Task");
_("Generating Export Files");
_("Add a Centreon Poller");
_("Add a Centreon Remote Server");
_("Server Configuration");
_("Choose a server type");
_("Create new Remote Server");
_("Select a Remote Server");
_("Select Pending Remote Links");
_("Server Name");
_("Server IP address");
_("Database username");
_("Database password");
_("Centreon Central IP address, as seen by this server");
_("Centreon Web Folder on Remote");
_("Attach poller to a master remote server");
_("Attach poller to additional remote servers");
_("Select pollers to be attached to this new Remote Server");
_("Advanced: reverse Centreon Broker communication flow");
_("Do not use configured proxy to connect to this server");
_("Finalizing Setup");
_("Next");
_("Previous");
_("Apply");
_("Required");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/route-components/pollerWizard/translatedLabels.ts */
_("Select a server type");
_("Configure a server");
_("Add an advanced configuration");
_("Finish the setup");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Navigation/translatedLabels.ts */
_("Centreon Logo");
_("Mini Centreon Logo");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Logout/translatedLabels.ts */
_("You will be disconnected");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/About/translatedLabels.ts */
_("Centreon");
_("Developed by");
_("and");
_("the community");
_("Project leaders");
_("Developers");
_("Contributors");
_("Security acknowledgement");
_("And many others...");
_("You can see the full list on");
_("Centreon's Github");
_("Many thanks to all the contributors to the security of Centreon");
_("Centreon website");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Extensions/translatedLabels.ts */
_("Types");
_("Uninstalled");
_("Outdated");
_("Up to date");
_("Module");
_("Install all");
_("Update all");
_("Install");
_("Update");
_("License required");
_("License end date:");
_("License expired");
_("License not valid");
_("Clear");
_("Search");
_("Filter options");
_("Status");
_("Installed");
_("Widget");
_("Clear filter");
_("Available");
_("Description");
_("Last update");
_("Delete");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/BreadcrumbTrail/translatedLabels.tsx */
_("Breadcrumb copied");
_("Failed to copy breadcrumb");
_("Copy breadcrumb");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/translatedLabels.tsx */
_("Dashboards");
_("Create a dashboard");
_("Welcome to the Dashboards interface!");
_("Cancel");
_("Create");
_("Update");
_("Delete");
_("Duplicate");
_("Name");
_("Description");
_("Create dashboard");
_("Update dashboard");
_("Delete dashboard");
_("Duplicate dashboard");
_("The {{name}} dashboard is part of one or several playlists. It will be permanently deleted from any playlists it belongs to.");
_("The {{name}} dashboard will be permanently deleted.");
_("Dashboard created");
_("Dashboard updated");
_("Dashboard deleted");
_("Dashboard duplicated");
_("Failed to create the dashboard");
_("Failed to update the dashboard");
_("Failed to delete the dashboard");
_("Failed to duplicate the dashboard");
_("Share the dashboard");
_("Manage access rights");
_("Copy link");
_("Link copied");
_("Unable to copy the link");
_("Add");
_("group");
_("No contacts found");
_("Add Contact...");
_("No access rights");
_("added");
_("removed");
_("updated");
_("added");
_("removed");
_("updated");
_("Viewer");
_("Editor");
_("Failed to copy link");
_("Copy link");
_("Link copied");
_("Save");
_("Add a contact");
_("Add a contact group");
_("Contact");
_("Contact group");
_("Share with");
_("Added");
_("Updated");
_("Removed");
_("User rights");
_("Group");
_("The share list is empty");
_("Failed to save shares");
_("Shares saved");
_("Delete user");
_("You are going to delete <strong>{{name}}</strong> from the user list. This user will no longer access the dashboard.");
_("User deleted");
_("Share with contacts");
_("Save your dashboard to generate a thumbnail");
_("Thumbnails show a snapshot of your data, taken when the dashboard is saved");
_("Expand");
_("Reduce");
_("Show only dashboards added to favorites");
_("The dashboard has been added to your favorites.");
_("The dashboard has been removed from your favorites.");
_("Remove from favorites");
_("Add to favorites");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/components/DashboardLibrary/DashboardListing/translatedLabels.ts */
_("Name");
_("Shares");
_("Role");
_("Description");
_("Creator");
_("Creation date");
_("Last update");
_("Stop sharing");
_("Viewer");
_("Editor");
_("Search");
_("Add");
_("Share");
_("Edit properties");
_("Actions");
_("View as list");
_("View as cards");
_("More actions");
_("Share with contacts");
_("Clear");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Tiles/translatedLabels.tsx */
_("Display up to");
_("tiles");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/AddEditWidget/WidgetProperties/Inputs/Checboxes/translatedLabels.ts */
_("Select all");
_("Unselect all");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/translatedLabels.ts */
_("Save");
_("Edit dashboard");
_("Add widget");
_("Edit widget");
_("Add a widget");
_("Cancel");
_("Exit {{dashboardName}}");
_("Exit edition mode");
_("If you leave the edition mode, your changes will not be saved.");
_("If you leave {{dashboardName}}, your changes will not be saved.");
_("Your dashboard has been saved");
_("Select a widget type");
_("Search");
_("No widget found");
_("Delete widget");
_("Widget type");
_("Select a widget type to activate the preview.");
_("Delete widget");
_("The {{name}} widget will be permanently deleted.");
_("The widget will be permanently deleted.");
_("Title");
_("Description");
_("Widget properties");
_("Common properties");
_("Required");
_("More actions");
_("Dataset selection");
_("Resources");
_("Host Group");
_("Host Category");
_("Service Group");
_("Service Category");
_("Host");
_("Service");
_("Meta service");
_("Delete");
_("Resource type");
_("Select resource");
_("Select type");
_("Metrics");
_("Please select a resource");
_("You have too many metrics, please filter more resources to optimize platform performance.");
_("Service name");
_("Metric");
_("Select metric");
_("Please select a metric");
_("Show description");
_("Add filter");
_("Add metric");
_("available");
_("Your widget has been modified successfully!");
_("Your widget has been created successfully!");
_("Value settings");
_("Refresh interval");
_("Dashboard global interval");
_("Custom refresh interval");
_("second");
_("Manual refresh");
_("Interval");
_("Thresholds");
_("Show thresholds");
_("Warning threshold");
_("Critical threshold");
_("Default");
_("Custom");
_("Thresholds are automatically hidden when you select several metrics with different units.");
_("Display as");
_("Text");
_("Gauge");
_("Bar chart");
_("The default value is the value defined for the first selected metric.");
_("none");
_("Value format");
_("Raw value");
_("Human readable");
_("You can choose only one resource for each resource type.");
_("View properties");
_("Your rights only allow you to view the properties of a widget.");
_("Please contact your administrator for more information.");
_("Last hour");
_("Last 3 hours");
_("Last 6 hours");
_("Last 12 hours");
_("Last 24 hours");
_("Last 7 days");
_("Last 30 days");
_("Last 3 months");
_("Last 6 months");
_("Last 12 months");
_("Time period");
_("Customize");
_("to");
_("From");
_("Start");
_("End");
_("Base color");
_("Refresh");
_("Duplicate");
_("Global refresh interval");
_("Manual refresh only");
_("manual");
_("Show value labels");
_("Display");
_("hosts");
_("Top");
_("Bottom");
_("Includes {{count}} resources");
_("Number of values");
_("View widget properties");
_("If you leave without saving your dashboard, changes will be permanently lost.");
_("is the selected metric by default. Refine filters to select another specific resource.");
_("See more on the {{ page }} page");
_("Resources Status");
_("Business Activity");
_("Discard");
_("Do you want to save the changes?");
_("If you click on Discard, your changes will not be saved.");
_("Select time zone");
_("Select time format");
_("Background color");
_("12 hours");
_("24 hours");
_("Last 14 days");
_("Last 2 months");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-resourcestable/src/Listing/translatedLabels.ts */
_("Resource");
_("Status");
_("Duration");
_("Tries");
_("State");
_("Last check");
_("Parent");
_("Severity");
_("Service");
_("Host");
_("Services");
_("In downtime");
_("Acknowledged");
_("At least three columns must be selected");
_("Information");
_("Action");
_("Author");
_("Start time");
_("Fixed");
_("End time");
_("Comment");
_("Entry time");
_("Persistent");
_("Sticky");
_("Oops, something went wrong");
_("Yes");
_("No");
_("Display view:");
_("View all resources");
_("View by host");
_("View by service");
_("All");
_("Acknowledge");
_("Action not permitted");
_("Forced check");
_("Set downtime");
_("Set downtime on");
_("Check command sent!");
_("Forced check command sent!");
_("Cancel");
_("Downtime");
_("Minutes");
_("Hours");
_("Seconds");
_("Set downtime on services attached to host");
_("To");
_("Unit");
_("Downtime command sent");
_("Downtime set by");
_("If checked, a notification is sent to the contacts linked to the object to warn that the incident on the resource has been acknowledged");
_("Acknowledge services attached to host");
_("Notify");
_("Required");
_("Acknowledge command sent");
_("Acknowledged by");
_("Services will not be affected because you don't have sufficient permission");
_("Hosts will not be affected because you don't have sufficient permission");
_("The end date must be greater than the start date");
_("Invalid format");
_("The duration must be less than a year");
_("Check selected resources even outside configured check period");
_("Check selected resources only within configured check period");
_("Check");
_("Tickets");
_("Open ticket for host");
_("Open ticket for service");
_("Close ticket");
_("Ticket ID");
_("Ticket subject");
_("Opened on");
_("Subject");
_("Create a ticket");
_("Close a ticket");
_("Confirm");
_("The ticket with ID #{{id}} will be closed for the selected ticket provider.");
_("Ticket created");
_("Ticket closed");
_("This resource is flapping");
_("FQDN / Address");
_("Parent alias");
_("Alias");
_("Monitoring server");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-clock/src/translatedLabels.ts */
_("Hour");
_("Minute");
_("Second");
_("Day");
_("Please, select a valid countdown");
_("Ends at");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statuschart/src/translatedLabels.ts */
_("Status:");
_("services");
_("hosts");
_("are working fine.");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridStandard/translatedLabels.ts */
_("Service name");
_("All services on this host are working fine.");
_("Acknowledged");
_("In downtime");
_("All metrics on this service are working fine.");
_("Metric name");
_("Value");
_("See more on the Resources Status page");
_("All KPIs on this Business Activity are working fine.");
_("are working fine.");
_("See more information in the geoview");
_("Calculation method");
_("State information");
_("Warning threshold");
_("Critical threshold");
_("Click here for details");
_("Expression in");
_("Impact applied when:");
_("Health");
_("Critical KPIs");
_("Parent");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-statusgrid/src/StatusGridCondensed/translatedLabels.ts */
_("are working fine.");
_("No {{type}} found with this status");
_("Status");
_("business activity");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-webpage/src/translatedLabels.ts */
_("Web page preview");
_("Webpage Display");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-singlemetric/src/translatedLabels.ts */
_("Warning threshold");
_("Critical threshold");
_("Value defined by the {{metric}} metric");
_("Custom value");
_("Warning");
_("Critical");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/translatedLabels.ts */
_("No data found");
_("Warning threshold");
_("Critical threshold");
_("Warning");
_("Critical");
_("Value defined by {{metric}} metric");
_("Custom value");
_("Select a dataset to display the preview.");
_("No host found");
_("No service found");
_("No KPI found");
_("No Business Activity found");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-groupmonitoring/src/translatedLabels.ts */
_("Down");
_("Up");
_("Unknown");
_("Unreachable");
_("Pending");
_("Warning");
_("Ok");
_("Critical");
_("Hosts");
_("Services");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Dashboards/SingleInstancePage/Dashboard/Widgets/centreon-widget-graph/src/translatedLabels.ts */
_("Warning threshold");
_("Critical threshold");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/ResetPassword/translatedLabels.ts */
_("Reset your password");
_("Required");
_("Current password");
_("New password");
_("New password confirmation");
_("New passwords must match");
_("The new password is the same as the old password");
_("Reset password");
_("Password renewed");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/AdditionalConnectorConfiguration/translatedLabels.ts */
_("Additional connector configurations");
_("Name");
_("Type");
_("Types");
_("Description");
_("Creator");
_("Creation date");
_("Last update");
_("Actions");
_("Updated by");
_("Delete");
_("Duplicate");
_("More actions");
_("Edit connector configuration");
_("At least one column must be selected");
_("Search");
_("Add");
_("More filters");
_("Clear");
_("Pollers");
_("Cancel");
_("Delete additional connector configuration");
_("The {{name}} additional connector configuration will be permanently deleted.");
_("The corresponding connectors will not work anymore.");
_("Additional connector configuration deleted");
_("Additional connector configuration duplicated");
_("Additional connector configuration created");
_("Additional connector configuration updated");
_("Duplicate connector configuration");
_("Save");
_("The name can be at most 50 characters long");
_("The name can be at most 50 characters long");
_("The name should be at least 3 characters long");
_("Required");
_("Create additional connector configuration");
_("Update additional connector configuration");
_("Create");
_("Update");
_("Select type");
_("Select poller(s)");
_("Port");
_("Value");
_("Password");
_("Add parameter");
_("URL");
_("Username");
_("Add vCenter/ESX");
_("Remove vCenter/ESX");
_("At least one poller is required");
_("At least one vCenter is required");
_("Please enter a valid URL or IP address");
_("Invalid port number");
_("The name of the vCenter should be unique");
_("Do you want to quit without saving the changes?");
_("Your form has unsaved changes. Do you want to quit the form without saving the changes?");
_("Confirm");
_("Parameters");
_("Parameters tooltip");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/AgentConfiguration/translatedLabels.tsx */
_("Poller/agent configuration");
_("Welcome to the poller/agent configuration page");
_("Create");
_("Name");
_("Agent type");
_("Poller");
_("Action");
_("Expand");
_("Collapse");
_("Add new agent configuration");
_("Search");
_("Filters");
_("Agent types");
_("Pollers");
_("Clear");
_("Delete poller");
_("Delete agent");
_("Cancel");
_("Delete");
_("Poller configuration");
_("Required");
_("Add poller/agent configuration");
_("Add");
_("OTLP receiver");
_("Port");
_("Save");
_("Port number must be at most 65535");
_("Port number must be at least 1");
_("Extension not allowed");
_("Public certificate file name");
_("CA file name");
_("Private key file name");
_("Certificate file name");
_("OTLP Receiver");
_("Invalid address");
_("Host configurations");
_("Add a host");
_("Parameters");
_("DNS/IP");
_("Add host");
_("Connection initiated by poller");
_("Agent");
_("Configuration provider");
_("Poller/agent configuration created");
_("Poller/agent configuration updated");
_("Update poller/agent configuration");
_("Invalid filename");
_("An agent is a piece of software you install on the host you want to monitor, that executes the checks.");
_("Centreon Monitoring Agent");
_("Poller CA certificate file name");
_("Poller CA name");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/publicPages/translatedLabels.ts */
_("Oops, something went wrong");
_("The page cannot be loaded");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/CloudNotificationsConfiguration/translatedLabels.ts */
_("Notification rules");
_("Welcome to the notifications interface");
_("Create a notification rule");
_("Add");
_("Duplicate");
_("Delete");
_("Discard");
_("Cancel");
_("Name");
_("Channels");
_("Users");
_("Resources");
_("Period");
_("Actions");
_("Status");
_("Search");
_("Save");
_("Select resources and events");
_("Search host groups");
_("Select users");
_("Notification settings");
_("Delete notification rule?");
_("This action cannot be undone.");
_("Collapse information panel");
_("Expand information panel");
_("Type your text here");
_("Active / Inactive");
_("Edit name");
_("Notification name");
_("Required");
_("The notification was successfully updated");
_("The notification was successfully added");
_("Confirm notification creation");
_("Choose at least 1 resource");
_("Choose at least 1 service group");
_("Add at least 1 contact");
_("The message field should not be empty!");
_("Close the panel");
_("Email template for the notification message");
_("Subject");
_("Notification channels");
_("Service groups");
_("Host groups");
_("Time period");
_("Select time period");
_("The time period field should not be empty!");
_("Search service groups");
_("Do you want to quit the form without saving the changes?");
_("Your form has unsaved changes");
_("This name already exists");
_("Cancel notification creation");
_("Cancel notification update");
_("Create notification for the first time");
_("Notification deleted successfully");
_("The selected notifications have been deleted successfully");
_("Failed to delete the notification");
_("Failed to delete the notifications");
_("Failed to delete the selected notifications");
_("delete multiple notifications");
_("Contacts");
_("Search contacts");
_("24h/24h - 7/7 days");
_("Include services for these hosts");
_("Notification duplicated");
_("Failed to duplicate the notification");
_("Please enter a name for the duplicated notification");
_("Notifications will only be sent during this time period");
_("Business Views");
_("Search Business Views");
_("Business Views events");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Main/translatedLabels.ts */
_("Centreon is loading...");
_("Your password will expire in");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Authentication/shared/translatedLabels.ts */
_("Authentication mode");
_("Mixed");
_("Enable auto import");
_("Contact template");
_("Enable automatic management");
_("Groups attribute path");
_("Group value");
_("Contact group");
_("Delete the relation");
_("Define the relation between groups and contact groups");
_("Roles mapping");
_("Apply only first role");
_("Roles attribute path");
_("Role value");
_("ACL access group");
_("Enable conditions on identity provider");
_("Conditions attribute path");
_("Condition value");
_("Define authorized conditions values");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Authentication/Local/translatedLabels.ts */
_("Define the password security policy");
_("Password case policy");
_("Minimum password length");
_("Minimum 8 characters");
_("Maximum 128 characters");
_("Password must contain upper case");
_("Password must contain lower case");
_("Password must contain numbers");
_("Password must contain special characters");
_("Required");
_("a-z");
_("A-Z");
_("0-9");
_("/*+&");
_("Password expires after");
_("Weak");
_("Good");
_("Strong");
_("Unknown");
_("Password expiration policy");
_("Choose a duration between 7 days and 12 months");
_("Month");
_("Months");
_("Day");
_("Days");
_("Hour");
_("Hours");
_("Minute");
_("Minutes");
_("Second");
_("Seconds");
_("Last 3 passwords can be reused");
_("Minimum time between password changes");
_("Choose a duration between 1 hour and 1 week");
_("Password blocking policy");
_("Number of attempts before user is blocked");
_("Choose a value between 1 and 10");
_("Time that must pass before new connection is allowed");
_("Blocking duration must be less than or equal to 7 days");
_("Save");
_("Saving...");
_("Saved");
_("Reset");
_("Password security policy saved");
_("Failed to save password security policy");
_("This will not be used because the number of attempts is not defined");
_("Cancel");
_("Reset the form");
_("Do you want to reset the form?");
_("Excluded users");
_("Admin");
_("Password security policy");
_("Choose letter cases");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Authentication/Openid/translatedLabels.tsx */
_("OpenID Connect Configuration");
_("Define OpenID Connect configuration");
_("Required");
_("Invalid URL");
_("Invalid IP Address");
_("Failed to save OpenID Connect configuration");
_("OpenID Connect configuration saved");
_("Enable OpenID Connect authentication");
_("Trusted client addresses");
_("Blacklist client addresses");
_("Base URL");
_("Authorization endpoint");
_("Token endpoint");
_("Introspection token endpoint");
_("User information endpoint");
_("End session endpoint");
_("Scopes");
_("Login attribute path");
_("Client ID");
_("Client secret");
_("Use basic authentication for token endpoint authentication");
_("Disable verify peer");
_("OpenID Connect only");
_("Email attribute path");
_("Fullname attribute path");
_("At least one of the two following fields must be filled");
_("At least one authorization relation is required");
_("Authorization value");
_("Access group");
_("Define the relation between authorization value and access group");
_("Authorization key");
_("This section allows you to give authorizations in order to link an imported user to an access group.");
_("`${labelContactGroup}: Define a contact group for the imported user.`");
_("`${labelAuthorizationKey}: The key`");
_("groups");
_("is defined by default. You can define another one.");
_("`${labelDefineRelationAuthorizationValueAndAccessGroup}: You can link an authorization value to an access group.`");
_("If we consider the following example in the JSON received from the authorization endpoint, a relation is defined between the value");
_("technical");
_("and an access group:");
_("Which endpoint does the conditions attribute path come from?");
_("Introspection endpoint");
_("User information");
_("Other");
_("Which endpoint does the roles attribute path come from?");
_("Define the relation between roles and ACL access groups");
_("Define your endpoint");
_("Which endpoint does the groups attribute path come from?");
_("Define the relation between groups and contact groups");
_("Group value");
_("Redirect URL");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Authentication/translatedLabels.ts */
_("Activation");
_("Identity provider");
_("Authentication conditions");
_("Auto import users");
_("Authorizations");
_("Press Enter to accept");
_("Client addresses");
_("Groups mapping");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Authentication/WebSSO/translatedLabels.tsx */
_("Web SSO configuration");
_("Define Web SSO Configuration");
_("Required");
_("Invalid IP Address");
_("Failed to save Web SSO configuration");
_("Web SSO configuration saved");
_("Enable Web SSO authentication");
_("Trusted client addresses");
_("Blacklist client addresses");
_("Web SSO only");
_("Pattern match login (regex)");
_("Pattern replace login (regex)");
_("Login header attribute name");
_("Invalid regex");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Authentication/SAML/translatedLabels.ts */
_("SAML configuration");
_("Define SAML configuration");
_("Failed to save SAML configuration");
_("SAML configuration saved");
_("Required");
_("Invalid URL");
_("Enable SAMLv2 authentication");
_("SAML only");
_("Remote login URL");
_("Issuer (Entity ID) URL");
_("Copy/paste x.509 certificate");
_("User ID (login) attribute for Centreon user");
_("Email attribute");
_("Full name attribute");
_("Define relations between roles and ACL access groups");
_("Logout from");
_("Logout URL");
_("Centreon UI only");
_("Both identity provider and Centreon UI");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Login/translatedLabels.ts */
_("Required");
_("Login succeeded");
_("Alias");
_("Password");
_("Login");
_("Centreon Logo");
_("Connect");
_("Display the password");
_("Hide the password");
_("or");
_("Login with");
_("Password has expired");
_("Centreon wallpaper");
_("Powered by Centreon");
_("An error occurred during authentication");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Header/Poller/translatedLabels.ts */
_("Export configuration");
_("Cancel");
_("Export & reload");
_("Export and reload the configuration?");
_("This will export and reload the configuration on all of your platform");
_("Exporting and reloading the configuration. Please wait...");
_("Configuration exported and reloaded");
_("Failed to export and reload the configuration");
_("Pollers");
_("Latency");
_("Database");
_("OK: no latency detected on your platform");
_("Latency detected, check configuration for better optimization");
_("OK: all database poller updates are active");
_("Some database poller updates are not active; check your configuration");
_("Database issue");
_("Pollers not running");
_("Everything is OK");
_("Configure pollers");
_("All pollers:");
_("Pollers");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Header/Resources/Host/translatedLabels.ts */
_("Hosts");
_("Down status hosts");
_("Unreachable status hosts");
_("Up status hosts");
_("All");
_("Down");
_("Pending");
_("Unreachable");
_("Up");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Header/Resources/Service/translatedLabels.ts */
_("Services");
_("Critical status services");
_("Warning status services");
_("Unknown status services");
_("OK status services");
_("All");
_("Critical");
_("Warning");
_("Pending");
_("Unknown");
_("OK");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/www/front_src/src/Header/UserMenu/translatedLabels.ts */
_("You have been logged out");
_("Profile");
_("Your password will expire in");
_("Edit profile");
_("Copy autologin link");
_("Logout");
_("Fullscreen (F)");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/Form/translatedLabels.ts */
_("Press Enter to accept");
_("Save");
_("Saving...");
_("Saved");
_("Reset");
_("Display the password");
_("Hide the password");
_("Drop or select a file");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/RichTextEditor/translatedLabels.ts */
_("Undo");
_("Redo");
_("Insert link");
_("Saved link");
_("Edit link");
_("align picker");
_("Unordered List");
_("Ordered List");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/Module/LicensedModule/LicenseCheck/translatedLabels.ts */
_("Oops !");
_("License invalid or expired !");
_("Please contact your administrator.");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/FileDropZone/translatedLabels.tsx */
_("Drop or");
_("select a file");
_("Invalid file type");
_("File too big");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/Graph/Chart/translatedLabels.ts */
_("Comment");
_("By");
_("From");
_("To");
_("Acknowledgement");
_("Downtime");
_("Min");
_("Max");
_("Avg");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/Graph/Timeline/translatedLabel.ts */
_("year");
_("month");
_("day");
_("hour");
_("minutes");
_("minute");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/TimePeriods/translatedLabels.ts */
_("1 day");
_("7 days");
_("31 days");
_("Last day");
_("Last 7 days");
_("Last 31 days");
_("From");
_("To");
_("Compact time period");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/utils/useFullscreen/translatedLabels.ts */
_("Cannot enter fullscreen mode");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/Dialog/UnsavedChanges/translatedLabels.ts */
_("Discard");
_("Save");
_("Leave");
_("Stay");
_("If you click on Discard, your changes will not be saved.");
_("Do you want to leave this page?");
_("Your changes will not be saved if you leave this page.");
_("Do you want to save the changes?");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/components/Form/Dashboard/translatedLabels.ts */
_("{{label}} can be at most {{max}} characters");
_("{{label}} should be at least {{min}} characters long");
_("Required");
_("characters");
_("Global refresh interval");
_("seconds");
_("Interval");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/components/CopyCommand/translatedLabels.ts */
_("Command copied");
_("Failed to copy command");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/components/ExpandableContainer/translatedLabels.ts */
_("Expand");
_("Reduce");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/Logo/translatedLabels.ts */
_("Centreon Logo");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/InputField/Search/index.stories.tsx */
_("(): JSX.Element => <SearchInput label="Search" />");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/InputField/translatedLabels.ts */
_("Open");
_("Clear");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/InputField/Select/Autocomplete/Connected/Multi/utils/index.ts */
_("Multi Connected Autocomplete");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/InputField/Select/IconPopover/translatedLabels.ts */
_("Reset");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/Listing/translatedLabels.ts */
_("to");
_("No result found");
_("of");
_("Rows per page");
_("First page");
_("Last page");
_("Next page");
_("Previous page");
_("Add columns");
_("Columns");
_("Predefined rows selection menu");
_("Drag handle");
/* /Users/laurentpinsivy/workspace/centreon-gha/i18n_toolkit/../centreon/packages/ui/src/LicenseMessage/translatedLabels.tsx */
_("Invalid license");
?>

