--
-- Commands and Timeperiods
--
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(1, 'check_host_alive', '$USER1$/check_icmp -H $HOSTADDRESS$ -w 3000.0,80% -c 5000.0,100% -p 1', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(2, 'check_disk_smb', '$USER1$/check_disk_smb -H $HOSTADDRESS$ -s $ARG1$ -u $ARG2$ -p $ARG3$ -w $ARG4$ -c $ARG5$', '!share!user!passwd!80!90', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(3, 'check_distant_disk_space', '$USER1$/check_distant_disk_space -H $HOSTADDRESS$ -C $ARG1$ -p $ARG2$ -w $ARG3$ -c $ARG4$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(4, 'check_centreon_dummy', '$USER1$/check_centreon_dummy -s $ARG1$ -o $ARG2$', '!0!OK', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(5, 'check_centreon_load_average', '$USER1$/check_centreon_snmp_loadaverage -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -w $ARG1$ -c $ARG2$', '!4,3,2!6,5,4', 2, 8, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(6, 'check_centreon_ping', '$USER1$/check_icmp -H $HOSTADDRESS$ -n $ARG1$ -w $ARG2$ -c $ARG3$', '!3!200,20%!400,50%', 2, 2, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(7, 'check_centreon_process', '$USER1$/check_centreon_snmp_process -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -n -p $ARG1$ -w $ARG2$ -c $ARG3$', '!httpd!warning!critical', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(8, 'check_centreon_remote_storage', '$USER1$/check_centreon_snmp_remote_storage -H $HOSTADDRESS$ -n -d $ARG1$ -w $ARG2$ -c $ARG3$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$', '!/!80!90', 2, 3, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(10, 'check_centreon_traffic_limited', '$USER1$/check_centreon_snmp_traffic -H $HOSTADDRESS$ -n -i $ARG1$ -w $ARG2$ -c $ARG3$ -T $ARG4$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$', '!eth0!80!90!2', 2, 7, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(11, 'check_hpjd', '$USER1$/check_hpjd -H $HOSTADDRESS$ -C public', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(12, 'check_http', '$USER1$/check_http -H $HOSTADDRESS$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(13, 'check_https', '$USER1$/check_http -S $HOSTADDRESS$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(14, 'check_local_swap', '$USER1$/check_swap -w $ARG1$ -c $ARG2$ -v', '!80!90', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(15, 'check_local_disk', '$USER1$/check_disk -w $ARG2$ -c $ARG3$ -p $ARG1$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(16, 'check_local_load', '$USER1$/check_load -w $ARG1$ -c $ARG2$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(17, 'check_local_procs', '$USER1$/check_procs -w $ARG1$ -c $ARG2$ -u $ARG3$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(18, 'check_local_users', '$USER1$/check_users -w $ARG1$ -c $ARG2$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(19, 'check_nt_memuse', '$USER1$/check_nt -H $HOSTADDRESS$ -v MEMUSE -p $ARG1$ -w $ARG2$ -c $ARG3$ -s $ARG4$', '!12489!80!90!public', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(20, 'check_nt_cpu', '$USER1$/check_nt -H $HOSTADDRESS$ -v CPULOAD -p $ARG1$ -l 2,90,95 -s $ARG2$', '!12489!public', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(21, 'check_nt_disk', '$USER1$/check_nt -H $HOSTADDRESS$ -v USEDDISKSPACE -p $ARG1$ -l $ARG2$ -w $ARG3$ -c $ARG4$ -s $ARG5$', '!12489!C!80!90!public', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(23, 'check_tcp', '$USER1$/check_tcp -H $HOSTADDRESS$ -p $ARG1$ -w $ARG2$ -c $ARG3$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(24, 'check_nntp', '$USER1$/check_nntp -H $HOSTADDRESS$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(25, 'check_pop', '$USER1$/check_pop -H $HOSTADDRESS$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(26, 'check_smtp', '$USER1$/check_smtp -H $HOSTADDRESS$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(27, 'check_dns', '$USER1$/check_dns -H $ARG1$ -s $HOSTADDRESS$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(28, 'check_ftp', '$USER1$/check_ftp -H $HOSTADDRESS$', '!127.0.0.1', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(29, 'check_dhcp', '$USER1$/check_dhcp -s $HOSTADDRESS$ -i $ARG1$', '!eth0', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(30, 'check_dig', '$USER1$/check_dig -H $HOSTADDRESS$ -l $ARG1$', '!www.centreon-nms.org', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(31, 'check_snmp', '$USER1$/check_snmp -H $HOSTADDRESS$ -o $ARG1$ -w $ARG2$ -c $ARG3$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(32, 'check_telnet', '$USER1$/check_tcp -H $HOSTADDRESS$ -p 23', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(33, 'check_udp', '$USER1$/check_udp -H $HOSTADDRESS$ -p $ARG1$', '', 2, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(34, 'check_centreon_nt', '$USER1$/check_nt -H $HOSTADDRESS$ -p 12489 -v $ARG1$ -l $ARG2$ -s $ARG3$ -w $ARG4$ -c $ARG5$', '', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(39, 'submit-host-check-result', '$USER1$/submit_host_check_result $HOSTNAME$ $HOSTSTATE$ &#039;$HOSTOUTPUT$&#039;', '', 3, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(40, 'submit-service-check-result', '$USER1$/submit_service_check_result $HOSTNAME$ $SERVICEDESC$ $SERVICESTATE$ &#039;$SERVICEOUTPUT$&#039;', '', 3, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(41, 'process-service-perfdata', '$USER1$/process-service-perfdata  "$LASTSERVICECHECK$" "$HOSTNAME$" "$SERVICEDESC$" "$LASTSERVICESTATE$" "$SERVICESTATE$" "$SERVICEPERFDATA$"', '', 3, NULL, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(44, 'check_centreon_uptime', '$USER1$/check_centreon_snmp_uptime -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -d', '', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(59, 'check_centreon_nb_connections', '$USER1$/check_centreon_snmp_TcpConn -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -p $ARG1$ -w $ARG2$ -c $ARG3$', '!80!70!100', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(62, 'check_centreon_traffic', '$USER1$/check_centreon_snmp_traffic -H $HOSTADDRESS$ -n -i $ARG1$ -w $ARG2$ -c $ARG3$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$', '!eth0!80!90', 2, 7, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(76, 'check_load_average', '$USER1$/check_load $HOSTADDRESS$ -w $ARG1$ -c $ARG2$', '', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(77, 'check_local_cpu_load', '$USER1$/check_nt -H $HOSTADDRESS$ -v CPULOAD -l $ARG1$ -s $ARG2$', '', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(78, 'check_local_disk_space', '$USER1$/check_nt -H $HOSTADDRESS$ -v USEDDISKSPACE -l $ARG1$ -w $ARG2$ -c $ARG3$ -s $ARG2$', '', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(79, 'check_maxq', '$USER1$/check_maxq_script_return -r $ARG1$ -P $ARG2$', '', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(94, 'check_centreon_snmp_value', '$USER1$/check_centreon_snmp_value -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -o $ARG1$ -w $ARG2$ -c $ARG53', '!1.3.6.1.4.1.705.1.8.1.0!190!210', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(95, 'check_centreon_snmp_proc_detailed', '$USER1$/check_centreon_snmp_process_detailed -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -n $ARG1$ -m $ARG2$', '!apache!20,50', 2, 0, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(96, 'check_centreon_cpu', '$USER1$/check_centreon_snmp_cpu -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -c $ARG1$ -w $ARG2$', '!80!90', 2, 5, NULL);
INSERT INTO `command` (`command_id`, `command_name`, `command_line`, `command_example`, `command_type`, `graph_id`, `cmd_cat_id`) VALUES(97, 'check_centreon_memory', '$USER1$/check_centreon_snmp_memory -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -w 80 -c 90', '', 2, 4, NULL);

--
-- table `command_arg_description`
--
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (2, "ARG1", "share");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (2, "ARG2", "user");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (2, "ARG3", "password");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (2, "ARG4", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (2, "ARG5", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (4, "ARG1", "status");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (4, "ARG2", "output");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (5, "ARG1", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (5, "ARG2", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (6, "ARG1", "count");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (6, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (6, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (7, "ARG1", "process name");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (8, "ARG1", "disk number");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (8, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (8, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (10, "ARG1", "interface");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (10, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (10, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (10, "ARG6", "Max bandwidth");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (14, "ARG1", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (14, "ARG2", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (15, "ARG1", "path");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (15, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (15, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (16, "ARG1", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (16, "ARG2", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (17, "ARG1", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (17, "ARG2", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (17, "ARG3", "process owner");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (18, "ARG1", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (18, "ARG2", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (21, "ARG1", "drive letter");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (21, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (21, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (23, "ARG1", "port");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (23, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (23, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (27, "ARG1", "hostname");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (29, "ARG1", "interface");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (30, "ARG1", "query address");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (31, "ARG1", "OID");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (31, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (31, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (33, "ARG1", "port");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (34, "ARG1", "variable");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (34, "ARG2", "params");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (34, "ARG3", "password");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (34, "ARG4", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (34, "ARG5", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (59, "ARG1", "port");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (59, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (59, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (62, "ARG1", "interface");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (62, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (62, "ARG3", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (76, "ARG1", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (76, "ARG2", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (78, "ARG1", "drive letter");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (78, "ARG2", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (78, "ARG1", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (94, "ARG2", "OID");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (94, "ARG3", "warning");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (94, "ARG4", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (95, "ARG1", "process name");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (95, "ARG2", "memory thresholds");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (96, "ARG1", "critical");
INSERT INTO `command_arg_description` (`cmd_id`, `macro_name`, `macro_description`) VALUES (96, "ARG2", "warning");

--
-- Contenu de la table `contact_hostcommands_relation`
--
INSERT INTO `contact_hostcommands_relation` (`contact_contact_id`, `command_command_id`) VALUES(1, 35);
INSERT INTO `contact_hostcommands_relation` (`contact_contact_id`, `command_command_id`) VALUES(17, 35);
INSERT INTO `contact_hostcommands_relation` (`contact_contact_id`, `command_command_id`) VALUES(18, 35);

--
-- Contenu de la table `contact_servicecommands_relation`
--
INSERT INTO `contact_servicecommands_relation` (`contact_contact_id`, `command_command_id`) VALUES(1, 36);
INSERT INTO `contact_servicecommands_relation` (`contact_contact_id`, `command_command_id`) VALUES(17, 36);
INSERT INTO `contact_servicecommands_relation` (`contact_contact_id`, `command_command_id`) VALUES(18, 36);

--
-- Contenu de la table `host`
--
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(2, NULL, 1, NULL, 1, 1, NULL, NULL, 'generic-host', 'generic-host', NULL, 5, NULL, '1', '0', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', 0, 'd,r', '0', NULL, 'public', '2c', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(3, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Servers-Linux', 'Linux Servers', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(4, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Servers-Win2K', 'Windows 2000 Servers', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(5, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Servers-Win2K3', 'Windows 2003 Servers', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(6, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Switchs-Cisco', 'Cisco Switchs', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(7, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Switchs-3Com', '3Com Switchs', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(8, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Switchs-HP', 'HP Switchs', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(9, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Switchs-NORTEL', 'NORTEL Switchs', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(10, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Router-Cisco', 'Cisco Routers', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(11, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Router-HP', 'HP Routers', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(12, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Printers', 'Printers', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(13, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'UPS', 'UPS', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '0', '1');
INSERT INTO `host` (`host_id`, `host_template_model_htm_id`, `command_command_id`, `command_command_id_arg1`, `timeperiod_tp_id`, `timeperiod_tp_id2`, `command_command_id2`, `command_command_id_arg2`, `host_name`, `host_alias`, `host_address`, `host_max_check_attempts`, `host_check_interval`, `host_active_checks_enabled`, `host_passive_checks_enabled`, `host_checks_enabled`, `host_obsess_over_host`, `host_check_freshness`, `host_freshness_threshold`, `host_event_handler_enabled`, `host_low_flap_threshold`, `host_high_flap_threshold`, `host_flap_detection_enabled`, `host_process_perf_data`, `host_retain_status_information`, `host_retain_nonstatus_information`, `host_notification_interval`, `host_notification_options`, `host_notifications_enabled`, `host_stalking_options`, `host_snmp_community`, `host_snmp_version`, `host_comment`, `host_register`, `host_activate`) VALUES(14, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'Centreon-Server', 'Monitoring Server', '127.0.0.1', NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '0', NULL, '1', '1');

--
-- Contenu de la table `host_template_relation`
--
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('3', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('4', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('5', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('6', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('7', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('8', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('9', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('10', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('11', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('12', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('13', '2', '1');
INSERT INTO `host_template_relation` (`host_host_id`, `host_tpl_id`, `order`) VALUES ('14', '2', '1');

--
-- Contenu de la table `extended_host_information`
--
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_host_information` (`host_host_id`, `ehi_notes`, `ehi_notes_url`, `ehi_action_url`, `ehi_icon_image`, `ehi_icon_image_alt`, `ehi_statusmap_image`, `ehi_2d_coords`, `ehi_3d_coords`) VALUES(14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Contenu de la table `ns_host_relation`
--
INSERT INTO `ns_host_relation` (`nagios_server_id`, `host_host_id`) VALUES(1, 14);

--
-- Contenu de la table `contactgroup_host_relation`
--
INSERT INTO `contactgroup_host_relation` (`host_host_id`, `contactgroup_cg_id`) VALUES(2, 5);

--
-- Contenu de la table `hostgroup`
--
INSERT INTO `hostgroup` (`hg_id`, `hg_name`, `hg_alias`, `hg_comment`, `hg_activate`) VALUES(53, 'Linux-Servers', 'All linux servers', NULL, '1');
INSERT INTO `hostgroup` (`hg_id`, `hg_name`, `hg_alias`, `hg_comment`, `hg_activate`) VALUES(54, 'Windows-Servers', 'All windows servers', NULL, '1');
INSERT INTO `hostgroup` (`hg_id`, `hg_name`, `hg_alias`, `hg_comment`, `hg_activate`) VALUES(55, 'Networks', 'All other equipments', NULL, '1');
INSERT INTO `hostgroup` (`hg_id`, `hg_name`, `hg_alias`, `hg_comment`, `hg_activate`) VALUES(56, 'Printers', 'All printers', NULL, '1');
INSERT INTO `hostgroup` (`hg_id`, `hg_name`, `hg_alias`, `hg_comment`, `hg_activate`) VALUES(58, 'Routers', 'All routers', NULL, '1');
INSERT INTO `hostgroup` (`hg_id`, `hg_name`, `hg_alias`, `hg_comment`, `hg_activate`) VALUES(59, 'Switchs', 'All switchs', NULL, '1');
INSERT INTO `hostgroup` (`hg_id`, `hg_name`, `hg_alias`, `hg_comment`, `hg_activate`) VALUES(60, 'Firewall', 'All firewalls', NULL, '1');
INSERT INTO `hostgroup` (`hg_id`, `hg_name`, `hg_alias`, `hg_comment`, `hg_activate`) VALUES(61, 'Unix-Servers', 'All unix servers', NULL, '1');

--
-- Contenu de la table `hostgroup_relation`
--
INSERT INTO `hostgroup_relation` (`hgr_id`, `hostgroup_hg_id`, `host_host_id`) VALUES (1250, 53, 14);

--
-- Contenu de la table `service`
--
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(1, NULL, NULL, 1, NULL, 1, 'generic-service', 'generic-service', '0', 3, 5, 1, '1', '0', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', 0, 'w,c,r', '0', NULL, NULL, NULL, NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(3, 1, 6, NULL, NULL, NULL, 'Ping-LAN', 'Ping', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!3!200,20%!400,50%', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(4, 1, 6, NULL, NULL, NULL, 'Ping-WAN', 'Ping', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!3!400,20%!600,50%', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(5, 1, 8, NULL, NULL, NULL, 'SNMP-DISK-/', 'Disk-/', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!/!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(6, 1, 8, NULL, NULL, NULL, 'SNMP-DISK-/var', 'Disk-/var', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!/var!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(7, 1, 8, NULL, NULL, NULL, 'SNMP-DISK-/usr', 'Disk-/usr', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!/usr!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(8, 1, 8, NULL, NULL, NULL, 'SNMP-DISK-/home', 'Disk-/home', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!/home!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(9, 1, 8, NULL, NULL, NULL, 'SNMP-DISK-/opt', 'Disk-/opt', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!/opt!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(10, 1, 8, NULL, NULL, NULL, 'SNMP-DISK-C:', 'Disk-C', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!C:!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(11, 1, 8, NULL, NULL, NULL, 'SNMP-DISK-E:', 'Disk-E', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!E:!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(12, 1, 5, NULL, NULL, NULL, 'SNMP-Linux-Load-Average', 'Load', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!4,3,2!6,5,4', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(13, 1, 97, NULL, NULL, NULL,'SNMP-Linux-Memory', 'Memory', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(14, 1, 8, NULL, NULL, NULL, 'SNMP-Linux-Swap', 'Swap', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!"Swap Space"!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(15, 1, 8, NULL, NULL, NULL, 'SNMP-Win2K3-Memory', 'Memory', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!"Physical Memory"!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(16, 1, 8, NULL, NULL, NULL, 'SNMP-Win2K3-Swap', 'Swap', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!"Virtual Memory"!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(17, 1, 8, NULL, NULL, NULL, 'SNMP-Win2K-memory', 'Memory', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!"Virtual Memory"!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(18, 1, 96, NULL, NULL, NULL, 'SNMP-Windows-CPU', 'CPU', '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, '!80!90', NULL, '0', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(19, 5, NULL, NULL, NULL, NULL, 'Disk-/', NULL, '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '1', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(20, 8, NULL, NULL, NULL, NULL, 'Disk-/home', NULL, '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '1', '0', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(21, 9, NULL, NULL, NULL, NULL, 'Disk-/opt', NULL, '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '1', '0', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(22, 7, NULL, NULL, NULL, NULL, 'Disk-/usr', NULL, '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '1', '0', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(23, 6, NULL, NULL, NULL, NULL, 'Disk-/var', NULL, '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '1', '0', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(24, 12, NULL, NULL, NULL, NULL, 'Load', NULL, '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '1', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(25, 13, NULL, NULL, NULL, NULL, 'Memory', NULL, '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '1', '1', '1');
INSERT INTO `service` (`service_id`, `service_template_model_stm_id`, `command_command_id`, `timeperiod_tp_id`, `command_command_id2`, `timeperiod_tp_id2`, `service_description`, `service_alias`, `service_is_volatile`, `service_max_check_attempts`, `service_normal_check_interval`, `service_retry_check_interval`, `service_active_checks_enabled`, `service_passive_checks_enabled`, `service_parallelize_check`, `service_obsess_over_service`, `service_check_freshness`, `service_freshness_threshold`, `service_event_handler_enabled`, `service_low_flap_threshold`, `service_high_flap_threshold`, `service_flap_detection_enabled`, `service_process_perf_data`, `service_retain_status_information`, `service_retain_nonstatus_information`, `service_notification_interval`, `service_notification_options`, `service_notifications_enabled`, `service_stalking_options`, `service_comment`, `command_command_id_arg`, `command_command_id_arg2`, `service_register`, `service_activate`, `service_inherit_contacts_from_host`) VALUES(26, 3, NULL, NULL, NULL, NULL, 'Ping', NULL, '2', NULL, NULL, NULL, '2', '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', '2', NULL, NULL, '2', NULL, NULL, NULL, NULL, '1', '1', '1');

--
-- Contenu de la table `extended_service_information`
--
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(3, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(4, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(5, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(6, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(7, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(8, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(9, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(10, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(11, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(12, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(13, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(14, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(15, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(16, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(17, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(18, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(19, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(20, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(21, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(22, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(23, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(24, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(25, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `extended_service_information` (`service_service_id`, `esi_notes`, `esi_notes_url`, `esi_action_url`, `esi_icon_image`, `esi_icon_image_alt`, `graph_id`) VALUES(26, NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Contenu de la table `host_service_relation`
--
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 4, NULL, 11);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 5, NULL, 11);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 5, NULL, 16);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 5, NULL, 15);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 4, NULL, 17);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 14, NULL, 19);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 14, NULL, 20);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 14, NULL, 21);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 14, NULL, 22);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 14, NULL, 23);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 14, NULL, 24);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 14, NULL, 26);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 3, NULL, 5);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 3, NULL, 12);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 3, NULL, 14);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 14, NULL, 25);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 4, NULL, 18);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 5, NULL, 18);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 3, NULL, 13);
INSERT INTO `host_service_relation` (`hostgroup_hg_id`, `host_host_id`, `servicegroup_sg_id`, `service_service_id`) VALUES(NULL, 2, NULL, 3);

--
-- Contenu de la table `contactgroup_service_relation`
--
INSERT INTO `contactgroup_service_relation` (`contactgroup_cg_id`, `service_service_id`) VALUES (5, 1);

--
-- Contenu de la table `service_categories_relation`
--
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(70, 5, 3);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(71, 8, 3);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(72, 9, 3);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(73, 7, 3);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(74, 6, 3);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(75, 10, 3);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(76, 11, 3);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(78, 14, 4);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(79, 17, 4);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(80, 15, 4);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(81, 16, 4);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(82, 3, 1);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(83, 4, 1);
INSERT INTO `service_categories_relation` (`scr_id`, `service_service_id`, `sc_id`) VALUES(84, 13, 4);

--
-- Contact template.
--
INSERT INTO `contact` (`contact_name`, `contact_alias`, `contact_activate`, `contact_auth_type`, `contact_register`)
VALUES ('contact_template', 'contact_template', '1', 'local', 0);

-- Reduce broker transaction timeout to 1s to increase monitoring performance on small container
UPDATE cfg_centreonbroker_info SET config_value = '1' WHERE config_key = 'read_timeout';
UPDATE cfg_centreonbroker_info SET config_value = '1' WHERE config_key = 'queries_per_transaction';
UPDATE cfg_centreonbroker_info SET config_value = '5' WHERE config_key = 'retry_interval';