name: centreon-ui

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "centreon/packages/ui/**"

env:
  directory: "centreon/packages/ui"

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  lint:
    needs: [dependency-scan]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/frontend-lint
        with:
          frontend_directory: ${{ env.directory }}
          module_name: centreon-ui
          dependencies_lock_file: centreon/pnpm-lock.yaml
          pat: ${{ secrets.CENTREON_TECHNIQUE_PAT }}
          lint_path: ./src/

  type-check:
    needs: [dependency-scan]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/frontend-type-check
        with:
          frontend_directory: ${{ env.directory }}
          dependencies_lock_file: centreon/pnpm-lock.yaml

  cypress-component-testing:
    needs: [dependency-scan]
    uses: ./.github/workflows/cypress-component-parallelization.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.LIGHTHOUSE_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.LIGHTHOUSE_SECRET }}
      jira_base_url: ${{ secrets.JIRA_BASE_URL }}
      jira_user_email: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
      jira_api_token: ${{ secrets.XRAY_JIRA_TOKEN }}
    with:
      name: component
      module_name: centreon/packages/ui
      specs_path: src/**
      dependencies_lock_file: centreon/pnpm-lock.yaml

  unit-test:
    needs: [dependency-scan]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10
      - name: Install Centreon dependencies
        run: |
          pnpm install \
            --frozen-lockfile \
            --config.trustPolicy=no-downgrade \
            --config.minimumReleaseAge=2880 \
            --config.blockExoticSubdeps=true
        working-directory: centreon
      - name: Unit test
        run: pnpm t
        working-directory: ${{ env.directory }}
