name: chromatic

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'MON-**'
    paths:
      - "centreon/packages/ui/**"

env:
  directory: "centreon/packages/ui"

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  chromatic:
    needs: [dependency-scan]
    if: github.repository == 'centreon/centreon' && !startsWith(github.event.head_commit.message, 'Merge branch')
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/chromatic
        with:
          frontend_directory: ${{ env.directory }}
          dependencies_lock_file: centreon/pnpm-lock.yaml
          pat: ${{ secrets.CENTREON_TECHNIQUE_PAT }}
          project_token: ${{ secrets.CHROMATIC_TOKEN }}
