name: chromatic

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'MON-**'
    paths:
      - "centreon/packages/ui/**"

env:
  directory: "centreon/packages/ui"

jobs:
  chromatic:
    if: github.repository == 'centreon/centreon' && !startsWith(github.event.head_commit.message, 'Merge branch')
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: ./.github/actions/chromatic
        with:
          frontend_directory: ${{ env.directory }}
          dependencies_lock_file: centreon/pnpm-lock.yaml
          pat: ${{ secrets.CENTREON_TECHNIQUE_PAT }}
          project_token: ${{ secrets.CHROMATIC_TOKEN }}
