name: clean-npm-tags

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5"

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  clean-npm-tags:
    needs: [dependency-scan]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10

      - name: Install action dependencies
        run: |
          pnpm install \
            --frozen-lockfile \
            --config.trustPolicy=no-downgrade \
            --config.minimumReleaseAge=2880 \
            --config.blockExoticSubdeps=true
        working-directory: ./.github/actions/clean-up-npm-tags
        shell: bash

      - uses: ./.github/actions/clean-up-npm-tags
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
