name: create-xray-test-plan-and-test-execution

on:
  workflow_call:
    inputs:
      major_version:
        required: true
        type: string
      minor_version:
        required: true
        type: string
      os:
        required: true
        type: string
      is_nightly:
        required: false
        type: string
    outputs:
      test_plan_key_alma9:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_key_alma9 }}
      test_plan_id_alma9:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_id_alma9 }}
      test_execution_key_alma9:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_key_alma9 }}
      test_execution_id_alma9:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_id_alma9 }}
      test_plan_key_bullseye:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_key_bullseye }}
      test_plan_id_bullseye:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_id_bullseye }}
      test_execution_key_bullseye:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_key_bullseye }}
      test_execution_id_bullseye:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_id_bullseye }}
      test_plan_key_bookworm:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_key_bookworm }}
      test_plan_id_bookworm:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_id_bookworm }}
      test_execution_key_bookworm:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_key_bookworm }}
      test_execution_id_bookworm:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_id_bookworm }}
    secrets:
      xray_jira_user_email:
        required: true
      xray_jira_token:
        required: true
      xray_client_id:
        required: true
      xray_client_secret:
        required: true

# NIGHTLY <OSS|MODULES|COLLECT> <MAJOR_VERSION> (e.g., NIGHTLY OSS 23.10)
jobs:
  create-xray-test-plan-and-test-execution:
    runs-on: ubuntu-24.04
    outputs:
      test_plan_key_alma9: ${{ steps.get_test_plan_key.outputs.test_plan_key_alma9 }}
      test_plan_id_alma9: ${{ steps.get_test_plan_id.outputs.test_plan_id_alma9 }}
      test_execution_key_alma9: ${{ steps.get_test_execution_key.outputs.test_execution_key_alma9 }}
      test_execution_id_alma9: ${{ steps.get_test_execution_id.outputs.test_execution_id_alma9 }}
      test_plan_key_bullseye: ${{ steps.get_test_plan_key.outputs.test_plan_key_bullseye }}
      test_plan_id_bullseye: ${{ steps.get_test_plan_id.outputs.test_plan_id_bullseye }}
      test_execution_key_bullseye: ${{ steps.get_test_execution_key.outputs.test_execution_key_bullseye }}
      test_execution_id_bullseye: ${{ steps.get_test_execution_id.outputs.test_execution_id_bullseye }}
      test_plan_key_bookworm: ${{ steps.get_test_plan_key.outputs.test_plan_key_bookworm }}
      test_plan_id_bookworm: ${{ steps.get_test_plan_id.outputs.test_plan_id_bookworm }}
      test_execution_key_bookworm: ${{ steps.get_test_execution_key.outputs.test_execution_key_bookworm }}
      test_execution_id_bookworm: ${{ steps.get_test_execution_id.outputs.test_execution_id_bookworm }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          sparse-checkout: .github/scripts/xray

      - name: Generate Xray Token
        id: generate_xray_token
        run: |
          token_response=$(curl -H "Content-Type: application/json" -X POST --data "{\"client_id\": \"${{ secrets.xray_client_id }}\", \"client_secret\": \"${{ secrets.xray_client_secret }}\"}" "https://xray.cloud.getxray.app/api/v1/authenticate")
          xray_token=$(echo "$token_response" | sed -n 's/.*"\(.*\)".*/\1/p')
          echo "xray_token=$xray_token" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create or Get the TestPlanKey
        id: get_test_plan_key
        env:
          XRAY_TOKEN: ${{ steps.generate_xray_token.outputs.xray_token }}
          IS_NIGHTLY: ${{ inputs.is_nightly || '' }}
          MAJOR_VERSION: ${{ inputs.major_version }}
          OS: ${{ inputs.os }}
        run: bash .github/scripts/xray/create-or-get-test-plan-key.sh
        shell: bash

      - name: Get TestPlanID
        id: get_test_plan_id
        run: |
          test_plan_key=$(echo '${{ toJSON(steps.get_test_plan_key.outputs) }}' | jq -r '.test_plan_key_'${{ inputs.os }})
          echo "getting the testPlanId for the testPlanKey: $test_plan_key"
          jira_url="https://centreon.atlassian.net/rest/api/2/issue/$test_plan_key"

          test_plan_id=$(curl -u "${{ secrets.xray_jira_user_email }}:${{ secrets.xray_jira_token }}" -X GET -s "$jira_url" | jq -r '.id')
          echo "this is the testPlan ID : $test_plan_id"
          echo "test_plan_id_${{ inputs.os }}=$test_plan_id" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create TestExecution and Get the TestExecutionID
        id: get_test_execution_id
        env:
          XRAY_TOKEN: ${{ steps.generate_xray_token.outputs.xray_token }}
          IS_NIGHTLY: ${{ inputs.is_nightly || '' }}
          MAJOR_VERSION: ${{ inputs.major_version }}
          MINOR_VERSION: ${{ inputs.minor_version }}
          OS: ${{ inputs.os }}
        run: bash .github/scripts/xray/create-test-execution.sh
        shell: bash

      - name: Get TestExecutionKey
        id: get_test_execution_key
        run: |
          test_execution_id=$(echo '${{ toJSON(steps.get_test_execution_id.outputs) }}' | jq -r '.test_execution_id_'${{ inputs.os }})
          jira_url="https://centreon.atlassian.net/rest/api/2/issue/$test_execution_id"

          test_execution_key=$(curl -u "${{ secrets.xray_jira_user_email }}:${{ secrets.xray_jira_token }}" -X GET -s "$jira_url" | jq -r '.key')
          echo "this is the TestExecutionKey: $test_execution_key"
          echo "test_execution_key_${{ inputs.os }}=$test_execution_key" >> $GITHUB_OUTPUT
        shell: bash

      - name: Update the status of the TestExecution Issue
        run: |
          test_execution_key=$(echo '${{ toJSON(steps.get_test_execution_key.outputs) }}' | jq -r '.test_execution_key_'${{ inputs.os }})
          curl -D- -u "${{ secrets.xray_jira_user_email }}:${{ secrets.xray_jira_token }}" -X POST --data '{"transition":{"id":"5"}}' -H "Content-Type: application/json" https://centreon.atlassian.net/rest/api/2/issue/$test_execution_key/transitions?expand=transitions.fields

      - name: Add the TestExecution Issue to the TestPlan
        run: |
          test_plan_id=$(echo '${{ toJSON(steps.get_test_plan_id.outputs) }}' | jq -r '.test_plan_id_'${{ inputs.os }})
          test_execution_id=$(echo '${{ toJSON(steps.get_test_execution_id.outputs) }}' | jq -r '.test_execution_id_'${{ inputs.os }})
          xray_graphql_mutation="{
            \"query\": \"mutation AddTestExecution(\$issueId: String!, \$testExecIssueIds: [String]!) { addTestExecutionsToTestPlan(issueId: \$issueId, testExecIssueIds: \$testExecIssueIds) { addedTestExecutions warning } }\",
            \"variables\": {
              \"issueId\": \"$test_plan_id\",
              \"testExecIssueIds\": [\"$test_execution_id\"]
            }
          }"
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate_xray_token.outputs.xray_token }}" --data "${xray_graphql_mutation}" "https://xray.cloud.getxray.app/api/v2/graphql"
