name: create-xray-test-plan-and-test-execution

on:
  workflow_call:
    inputs:
      major_version:
        required: true
        type: string
      minor_version:
        required: true
        type: string
      os:
        required: true
        type: string
      is_nightly:
        required: false
        type: string
    outputs:
      test_plan_key_alma9:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_key_alma9 }}
      test_plan_id_alma9:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_id_alma9 }}
      test_execution_key_alma9:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_key_alma9 }}
      test_execution_id_alma9:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_id_alma9 }}
      test_plan_key_alma10:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_key_alma10 }}
      test_plan_id_alma10:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_id_alma10 }}
      test_execution_key_alma10:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_key_alma10 }}
      test_execution_id_alma10:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_id_alma10 }}
      test_plan_key_bullseye:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_key_bullseye }}
      test_plan_id_bullseye:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_id_bullseye }}
      test_execution_key_bullseye:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_key_bullseye }}
      test_execution_id_bullseye:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_id_bullseye }}
      test_plan_key_trixie:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_key_trixie }}
      test_plan_id_trixie:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_plan_id_trixie }}
      test_execution_key_trixie:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_key_trixie }}
      test_execution_id_trixie:
        value: ${{ jobs.create-xray-test-plan-and-test-execution.outputs.test_execution_id_trixie }}
    secrets:
      xray_jira_user_email:
        required: true
      xray_jira_token:
        required: true
      xray_client_id:
        required: true
      xray_client_secret:
        required: true

# NIGHTLY <OSS|MODULES|COLLECT> <MAJOR_VERSION> (e.g., NIGHTLY OSS 23.10)
jobs:
  create-xray-test-plan-and-test-execution:
    runs-on: ubuntu-24.04
    outputs:
      test_plan_key_alma9: ${{ steps.get_test_plan_key.outputs.test_plan_key_alma9 }}
      test_plan_id_alma9: ${{ steps.get_test_plan_id.outputs.test_plan_id_alma9 }}
      test_execution_key_alma9: ${{ steps.get_test_execution_key.outputs.test_execution_key_alma9 }}
      test_execution_id_alma9: ${{ steps.get_test_execution_id.outputs.test_execution_id_alma9 }}
      test_plan_key_alma10: ${{ steps.get_test_plan_key.outputs.test_plan_key_alma10 }}
      test_plan_id_alma10: ${{ steps.get_test_plan_id.outputs.test_plan_id_alma10 }}
      test_execution_key_alma10: ${{ steps.get_test_execution_key.outputs.test_execution_key_alma10 }}
      test_execution_id_alma10: ${{ steps.get_test_execution_id.outputs.test_execution_id_alma10 }}
      test_plan_key_bullseye: ${{ steps.get_test_plan_key.outputs.test_plan_key_bullseye }}
      test_plan_id_bullseye: ${{ steps.get_test_plan_id.outputs.test_plan_id_bullseye }}
      test_execution_key_bullseye: ${{ steps.get_test_execution_key.outputs.test_execution_key_bullseye }}
      test_execution_id_bullseye: ${{ steps.get_test_execution_id.outputs.test_execution_id_bullseye }}
      test_plan_key_trixie: ${{ steps.get_test_plan_key.outputs.test_plan_key_trixie }}
      test_plan_id_trixie: ${{ steps.get_test_plan_id.outputs.test_plan_id_trixie }}
      test_execution_key_trixie: ${{ steps.get_test_execution_key.outputs.test_execution_key_trixie }}
      test_execution_id_trixie: ${{ steps.get_test_execution_id.outputs.test_execution_id_trixie }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: .github/scripts/xray

      - name: Generate Xray Token
        id: generate_xray_token
        env:
          XRAY_CLIENT_ID: ${{ secrets.xray_client_id }}
          XRAY_CLIENT_SECRET: ${{ secrets.xray_client_secret }}
        run: |
          payload=$(jq -nc --arg id "$XRAY_CLIENT_ID" --arg secret "$XRAY_CLIENT_SECRET" '{client_id: $id, client_secret: $secret}')
          token_response=$(curl -H "Content-Type: application/json" -X POST --data "$payload" "https://xray.cloud.getxray.app/api/v1/authenticate")
          xray_token=$(echo "$token_response" | sed -n 's/.*"\(.*\)".*/\1/p')
          echo "xray_token=$xray_token" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create or Get the TestPlanKey
        id: get_test_plan_key
        env:
          XRAY_TOKEN: ${{ steps.generate_xray_token.outputs.xray_token }}
          IS_NIGHTLY: ${{ inputs.is_nightly || '' }}
          MAJOR_VERSION: ${{ inputs.major_version }}
          OS: ${{ inputs.os }}
        run: bash .github/scripts/xray/create-or-get-test-plan-key.sh
        shell: bash

      - name: Get TestPlanID
        id: get_test_plan_id
        env:
          TEST_PLAN_KEY_OUTPUTS: ${{ toJSON(steps.get_test_plan_key.outputs) }}
          OS: ${{ inputs.os }}
          XRAY_JIRA_USER_EMAIL: ${{ secrets.xray_jira_user_email }}
          XRAY_JIRA_TOKEN: ${{ secrets.xray_jira_token }}
        run: |
          test_plan_key=$(echo "$TEST_PLAN_KEY_OUTPUTS" | jq -r --arg os "$OS" '.["test_plan_key_" + $os]')
          echo "getting the testPlanId for the testPlanKey: $test_plan_key"
          jira_url="https://centreon.atlassian.net/rest/api/2/issue/$test_plan_key"

          test_plan_id=$(curl -u "$XRAY_JIRA_USER_EMAIL:$XRAY_JIRA_TOKEN" -X GET -s "$jira_url" | jq -r '.id')
          echo "this is the testPlan ID : $test_plan_id"
          echo "test_plan_id_$OS=$test_plan_id" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create TestExecution and Get the TestExecutionID
        id: get_test_execution_id
        env:
          XRAY_TOKEN: ${{ steps.generate_xray_token.outputs.xray_token }}
          IS_NIGHTLY: ${{ inputs.is_nightly || '' }}
          MAJOR_VERSION: ${{ inputs.major_version }}
          MINOR_VERSION: ${{ inputs.minor_version }}
          OS: ${{ inputs.os }}
        run: bash .github/scripts/xray/create-test-execution.sh
        shell: bash

      - name: Get TestExecutionKey
        id: get_test_execution_key
        env:
          TEST_EXECUTION_ID_OUTPUTS: ${{ toJSON(steps.get_test_execution_id.outputs) }}
          OS: ${{ inputs.os }}
          XRAY_JIRA_USER_EMAIL: ${{ secrets.xray_jira_user_email }}
          XRAY_JIRA_TOKEN: ${{ secrets.xray_jira_token }}
        run: |
          test_execution_id=$(echo "$TEST_EXECUTION_ID_OUTPUTS" | jq -r --arg os "$OS" '.["test_execution_id_" + $os]')
          jira_url="https://centreon.atlassian.net/rest/api/2/issue/$test_execution_id"

          test_execution_key=$(curl -u "$XRAY_JIRA_USER_EMAIL:$XRAY_JIRA_TOKEN" -X GET -s "$jira_url" | jq -r '.key')
          echo "this is the TestExecutionKey: $test_execution_key"
          echo "test_execution_key_$OS=$test_execution_key" >> $GITHUB_OUTPUT
        shell: bash

      - name: Update the status of the TestExecution Issue
        env:
          TEST_EXECUTION_KEY_OUTPUTS: ${{ toJSON(steps.get_test_execution_key.outputs) }}
          OS: ${{ inputs.os }}
          XRAY_JIRA_USER_EMAIL: ${{ secrets.xray_jira_user_email }}
          XRAY_JIRA_TOKEN: ${{ secrets.xray_jira_token }}
        run: |
          test_execution_key=$(echo "$TEST_EXECUTION_KEY_OUTPUTS" | jq -r --arg os "$OS" '.["test_execution_key_" + $os]')
          curl -D- -u "$XRAY_JIRA_USER_EMAIL:$XRAY_JIRA_TOKEN" -X POST --data '{"transition":{"id":"5"}}' -H "Content-Type: application/json" "https://centreon.atlassian.net/rest/api/2/issue/$test_execution_key/transitions?expand=transitions.fields"

      - name: Add the TestExecution Issue to the TestPlan
        env:
          TEST_PLAN_ID_OUTPUTS: ${{ toJSON(steps.get_test_plan_id.outputs) }}
          TEST_EXECUTION_ID_OUTPUTS: ${{ toJSON(steps.get_test_execution_id.outputs) }}
          OS: ${{ inputs.os }}
          XRAY_TOKEN: ${{ steps.generate_xray_token.outputs.xray_token }}
        run: |
          test_plan_id=$(echo "$TEST_PLAN_ID_OUTPUTS" | jq -r --arg os "$OS" '.["test_plan_id_" + $os]')
          test_execution_id=$(echo "$TEST_EXECUTION_ID_OUTPUTS" | jq -r --arg os "$OS" '.["test_execution_id_" + $os]')
          xray_graphql_mutation=$(jq -nc --arg issueId "$test_plan_id" --arg execId "$test_execution_id" \
            '{query: "mutation AddTestExecution($issueId: String!, $testExecIssueIds: [String]!) { addTestExecutionsToTestPlan(issueId: $issueId, testExecIssueIds: $testExecIssueIds) { addedTestExecutions warning } }", variables: {issueId: $issueId, testExecIssueIds: [$execId]}}')
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $XRAY_TOKEN" --data "$xray_graphql_mutation" "https://xray.cloud.getxray.app/api/v2/graphql"
