name: cypress-e2e-test

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      module_name:
        required: true
        type: string
      database_image:
        required: true
        type: string
      image_name:
        required: true
        type: string
      os:
        required: true
        type: string
      features_path:
        required: true
        type: string
      major_version:
        required: true
        type: string
      minor_version:
        required: true
        type: string
      stability:
        required: true
        type: string
      target_stability:
        required: false
        type: string
      package_cache_key:
        required: false
        type: string
      package_directory:
        required: false
        type: string
      test_tags:
        required: false
        type: string
        default: "not @ignore"
      dependencies_lock_file:
        required: true
        type: string
        description: "The frontend dependencies lock file path"
      xray_keys_and_ids:
        description: "The test execution and the test plan keys and ids"
        required: true
        type: string
      is_cloud:
        description: "Define if the version is targeting cloud"
        required: false
        type: string # Set as string instead of boolean to avoid mixing types between workflows and actions
        default: 'false'
      is_nightly:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
      xray_client_id:
        required: true
      xray_client_secret:
        required: true
      artifactory_internal_repo_username:
        required: false
      artifactory_internal_repo_password:
        required: false
      jira_base_url:
        required: true
      jira_user_email:
        required: true
      jira_api_token:
        required: true

jobs:
  cypress-e2e-test-list:
    runs-on: ubuntu-24.04
    outputs:
      features: ${{ steps.list-features.outputs.features }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: List features
        id: list-features
        run: |
          set -o pipefail

          sudo apt-get update
          sudo apt-get install -y cucumber

          TEST_TAGS=$(echo "${{ inputs.test_tags }}" | sed -e 's#not #~#g' -e 's# and #\&\&#g')
          echo "test_tags=$TEST_TAGS" >> $GITHUB_OUTPUT

          cd ${{ inputs.module_name }}
          cucumber ${{ inputs.features_path }} --tags "$TEST_TAGS" -f json | jq -r '.[].uri' | sed -e 's#${{ inputs.features_path }}/*##g' | sort | jq -R -s -c 'split("\n")[:-1]'
          echo "features=$(cucumber ${{ inputs.features_path }} --tags "$TEST_TAGS" -f json | jq -r '.[].uri' | sed -e 's#${{ inputs.features_path }}/*##g' | sort | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  cypress-e2e-test-run:
    if: ${{ needs.cypress-e2e-test-list.outputs.features != '' && toJson(fromJson(needs.cypress-e2e-test-list.outputs.features)) != '[]' }}
    needs: [cypress-e2e-test-list]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        feature: ${{ fromJson(needs.cypress-e2e-test-list.outputs.features) }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.module_name }}/tests/e2e
    name: ${{ matrix.feature }}

    env:
      IMAGE_TAG: ${{ github.head_ref || github.ref_name }}
      SLIM_IMAGE_NAME: ${{ inputs.image_name }}-slim-${{ inputs.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Restore packages
        if: "${{ inputs.package_cache_key != '' && inputs.package_directory != '' && contains(matrix.feature, 'platform-') }}"
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ./*.${{ contains(inputs.os, 'alma') && 'rpm' || 'deb' }}
          key: ${{ inputs.package_cache_key }}
          fail-on-cache-miss: true

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ${{ inputs.dependencies_lock_file }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash
        env:
          CYPRESS_INSTALL_BINARY: "0"
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

      - name: Install Cypress binary
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_seconds: 120
          max_attempts: 10
          retry_wait_seconds: 30
          retry_on: error
          command: cd ${{ inputs.module_name }}/tests/e2e && pnpm cypress install --force

      - name: Move packages
        if: "${{ inputs.package_cache_key != '' && inputs.package_directory != '' && contains(matrix.feature, 'platform-') }}"
        run: |
          mkdir -p ${{ inputs.package_directory }}
          mv ../../../*.${{ contains(inputs.os, 'alma') && 'rpm' || 'deb' }} ${{ inputs.package_directory }}
        shell: bash

      - name: Login to Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Restore standard slim image from cache
        id: cache-docker-slim
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        continue-on-error: true
        timeout-minutes: 6
        with:
          path: ./docker-image
          key: docker-image-${{ env.SLIM_IMAGE_NAME }}-${{ env.IMAGE_TAG }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5

      - name: Load standard slim image
        if: ${{ steps.cache-docker-slim.outputs.cache-hit == 'true' }}
        run: |
          docker load --input ../../../docker-image/${{ env.SLIM_IMAGE_NAME }}.tar
          docker tag ${{ env.SLIM_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.SLIM_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        shell: bash

      - name: Get test execution Key
        id: get-test-execution-key
        run: |
          test_execution_key=$(echo '${{ inputs.xray_keys_and_ids }}' | jq -r '.test_execution_key_'${{ inputs.os }})
          echo "The Test Execution KEY: $test_execution_key"
          echo "test_execution_key=$test_execution_key" >> $GITHUB_ENV
        shell: bash

      - name: Add sso-proxy to /etc/hosts
        run: echo "127.0.0.1 sso-proxy" | sudo tee -a /etc/hosts
        shell: bash

      - name: Cypress end-to-end testing
        uses: cypress-io/github-action@b8ba51a856ba5f4c15cf39007636d4ab04f23e3c # v6.10.2
        with:
          command: pnpm run cypress:run --browser electron --spec features/**/${{ matrix.feature }} --env tags="${{ inputs.test_tags }}"
          install: false
          working-directory: ${{ inputs.module_name }}/tests/e2e
        env:
          CYPRESS_VERIFY_TIMEOUT: "60000"
          CYPRESS_DATABASE_IMAGE: ${{ inputs.database_image }}
          CYPRESS_WEB_IMAGE_OS: ${{ inputs.os }}
          CYPRESS_WEB_IMAGE_VERSION: ${{ env.IMAGE_TAG }}
          CYPRESS_OPENID_IMAGE_VERSION: ${{ inputs.major_version }}
          CYPRESS_SAML_IMAGE_VERSION: ${{ inputs.major_version }}
          CYPRESS_STABILITY: ${{ inputs.stability }}
          CYPRESS_TARGET_STABILITY: ${{ inputs.target_stability }}
          CYPRESS_IS_CLOUD: ${{ inputs.is_cloud }}
          CYPRESS_INTERNAL_REPO_USERNAME: ${{ secrets.artifactory_internal_repo_username }}
          CYPRESS_INTERNAL_REPO_PASSWORD: ${{ secrets.artifactory_internal_repo_password }}

      - name: Ensure logs directory exists
        run: mkdir -p ${{ inputs.module_name }}/tests/e2e/results/cucumber-logs/
        shell: bash

      - name: Replace / with - in the feature path
        id: feature-path
        if: ${{ ! cancelled() }}
        run: |
          feature_name="${{ matrix.feature }}"
          feature_name_with_dash="${feature_name//\//-}"
          echo "Modified Feature Name: $feature_name_with_dash"
          echo "feature_name_with_dash=$feature_name_with_dash" >> $GITHUB_OUTPUT

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: ${{ inputs.name }}-${{ inputs.os }}-test-results-${{ steps.feature-path.outputs.feature_name_with_dash }}
          path: ${{ inputs.module_name }}/tests/e2e/results/
          retention-days: 1

      - name: Move retries.json to reports directory and display warnings
        if: ${{ ! cancelled() }}
        run: |
            retriesFile="${{ inputs.module_name }}/tests/e2e/results/retries.json"
            if [ -f "$retriesFile" ]; then
              jq 'to_entries | .[].key' $retriesFile | while read -r testName; do
                echo "::warning::Following test was retried during execution: $testName (retries: $(jq ".$testName" $retriesFile))"
              done
              mv $retriesFile "${{ inputs.module_name }}/tests/e2e/results/reports/${{ steps.feature-path.outputs.feature_name_with_dash }}-retries.json"
            fi
        shell: bash

      - name: Upload test reports
        if: ${{ ! cancelled() }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: ${{ inputs.name }}-${{ inputs.os }}-test-reports-${{ steps.feature-path.outputs.feature_name_with_dash }}
          path: ${{ inputs.module_name }}/tests/e2e/results/reports/*.json
          retention-days: 1

      - name: Upload xray reports
        if: ${{ ! cancelled() }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: ${{ inputs.name }}-${{ inputs.os }}-xray-reports-${{ steps.feature-path.outputs.feature_name_with_dash }}
          path: ${{ inputs.module_name }}/tests/e2e/results/cucumber-logs/*.json
          retention-days: 1

  # This action is only for NIGHTLY and testing branches
  import-reports-to-xray:
    needs: [cypress-e2e-test-run]
    if: |
      ! cancelled() &&
      ! contains(needs.*.result, 'cancelled') &&
      (inputs.stability == 'testing' || github.event_name == 'schedule')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 10

      - name: Download Artifacts
        uses: actions/download-artifact@87c55149d96e628cc2ef7e6fc2aab372015aec85 # v4.1.3
        with:
          pattern: ${{ inputs.name }}-${{ inputs.os }}-xray-reports-*
          path: ${{ inputs.name }}-json-xray-reports
          merge-multiple: true

      - name: Generate Xray Token
        id: generate-xray-token
        run: |
          token_response=$(curl -H "Content-Type: application/json" -X POST --data "{\"client_id\": \"${{ secrets.XRAY_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.XRAY_CLIENT_SECRET }}\"}" "https://xray.cloud.getxray.app/api/v1/authenticate")
          xray_token=$(echo "$token_response" | sed -n 's/.*"\(.*\)".*/\1/p')
          echo "xray_token=$xray_token" >> $GITHUB_OUTPUT
        shell: bash

      - name: Keys
        run: |
          test_execution_key=$(echo '${{ inputs.xray_keys_and_ids }}' | jq -r '.test_execution_key_'${{ inputs.os }})
          test_plan_key=$(echo '${{ inputs.xray_keys_and_ids }}' | jq -r '.test_plan_key_'${{ inputs.os }})
          echo "The Test Execution KEY: $test_execution_key"
          echo "The Test Plan KEY: $test_plan_key"

      - name: Import results to xray
        run: |
          for file in "${{ inputs.name }}-json-xray-reports/"*.json
          do
            curl -H "Content-Type: application/json" -X POST -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token }}" --data @"$file" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber
          done

  cypress-e2e-test-report:
    needs: [cypress-e2e-test-run]
    if: |
      ! cancelled() &&
      ! contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 10

      - name: Download Artifacts
        uses: actions/download-artifact@87c55149d96e628cc2ef7e6fc2aab372015aec85 # v4.1.3
        with:
          pattern: ${{ inputs.name }}-${{ inputs.os }}-test-reports-*
          path: ${{ inputs.name }}-json-reports
          merge-multiple: true

      - name: Merge reports
        run: |
          pnpx mochawesome-merge "${{ inputs.name }}-json-reports/**/*-report.json" > mochawesome.json

          if ls ${{ inputs.name }}-json-reports/*retries.json 1> /dev/null 2>&1; then
            cat ${{ inputs.name }}-json-reports/*retries.json | jq -s add > retries.json
          else
            echo "{}" > retries.json
          fi
        shell: bash

      - name: Publish report
        if: needs.cypress-e2e-test-run.result == 'failure'
        uses: ./.github/actions/publish-report
        with:
          check_name: ${{ inputs.name }}-report
          path: mochawesome.json
          format: cypress

      - name: Display retries summary
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const fs = require('fs');
            const retriesFile = 'retries.json';
            const retries = JSON.parse(fs.readFileSync(retriesFile, 'utf8'));
            if (Object.keys(retries).length > 0) {
              const outputTable = [
                [{data: 'Feature', header: true}, {data: 'Scenario', header: true}, {data: 'Retries', header: true}],
              ];
              const warningTitle = `${Object.keys(retries).length} tests were retried during execution`;

              let warningBody = JSON.stringify(retries, null, 2);
              for (const testName in retries) {
                const featureName = testName.split('>')[0];
                const scenarioName = testName.split('>').slice(1).join('>');
                outputTable.push([featureName, scenarioName, String(retries[testName])]);
              }

              // Display json to allow collect of metrics
              core.warning(warningBody, { title: warningTitle });

              core.summary
                .addHeading(`Retries Summary`)
                .addTable(outputTable)
                .addDetails(`Content of ${retriesFile}`, fs.readFileSync(retriesFile, 'utf8'))
                .write();
            }

  regroup-artifacts:
    needs: [cypress-e2e-test-run, import-reports-to-xray, cypress-e2e-test-report]
    if: |
      ! cancelled() &&
      ! contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        type_of_report: [test-results, test-reports, xray-reports]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        if: ${{ ( contains(needs.cypress-e2e-test-run.result, 'failure') && ( matrix.type_of_report == 'test-results' || matrix.type_of_report == 'test-reports' ) ) || matrix.type_of_report == 'xray-reports' }}
        with:
          name: ${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}
          pattern: ${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}-*
          delete-merged: false # cannot be set to true due to random fails: Failed to DeleteArtifact: Unable to make request: ECONNRESET
          retention-days: 1

      - name: Delete merged artifacts
        if: |
          success() ||
          ( failure() && matrix.type_of_report == 'test-results' )
        uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        with:
          name: ${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}-*
          failOnError: false
