name: delete-feature-repositories

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - closed

jobs:
  delete-feature-repositories:
    if: |
      startsWith(github.ref_name, 'MON-')
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: jfrog/setup-jfrog-cli@88e9eba31c07e31beefa4cef5c0e93d1af9535d7 # v4.6.1
        env:
          JF_URL: https://packages.centreon.com
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Check if feature branch had associated feature repository
        id: check_feature_repository
        shell: bash
        run: |
          set -x
          feature_ticket=$(echo "${{ github.head_ref }}" | grep -oE 'MON-[0-9]+')
          if [[ -z "$feature_ticket" ]]; then
            echo "::notice::Ticket ID not found due to the branch name not corresponding to standards."
            echo "repositories_found=false" >> "$GITHUB_OUTPUT"
          elif jf rt curl -s -X GET /api/repositories | jq -r '.[].key' | grep "$feature_ticket"; then
            echo "::notice::Repositories associated with $feature_ticket found – deletion will be requested."
            echo "repositories_found=true" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::No repositories linked to $feature_ticket – workflow ends here."
            echo "repositories_found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if other feature branches/pull requests of the same ticket exist on other repositories
        id: check_other_feature_prs
        if: |
          steps.check_feature_repository.outputs.repositories_found == 'true'
        shell: bash
        run: |
          set -x
          if [[ -n $(gh pr list --repo centreon/centreon-modules --head ${{ github.head_ref }} --state open --json number | jq -r '.[].number') ]] \
          || [[ -n $(gh pr list --repo centreon/centreon-collect --head ${{ github.head_ref }} --state open --json number | jq -r '.[].number') ]]; then
            echo "::notice::Other open feature pull requests have been found on other repositories: no feature repository deletion will be requested."
            echo "feature_prs_found=true" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::Other open feature pull requests have not been found on other repositories: a feature repository deletion will be requested."
            echo "feature_prs_found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Send repository dispatch to delete feature repositories
        shell: bash
        if: |
          steps.check_feature_repository.outputs.repositories_found == 'true' &&
          steps.check_other_feature_prs.outputs.feature_prs_found == 'false'
        run: |
          set -x
          echo "Sending repository dispatch to delete feature repository workflow..."
          feature_ticket=$(echo "${{ github.head_ref }}" | grep -oE 'MON-[0-9]+')
          curl --fail-with-body -X POST \
            -H "Authorization: Bearer ${{ secrets.CENTREON_TECHNIQUE_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/centreon/delivery-tooling/dispatches \
            -d "$(jq -n \
              --arg feature_ticket "$feature_ticket" \
              '{
                event_type: "delete-feature-repositories",
                client_payload: {
                  feature_ticket: $feature_ticket
                }
              }'
            )"

          if [ $? -ne 0 ]; then
            echo "::error::Failure to send repository dispatch to delete feature repository. You may want to perform that operation manually."
            exit 1
          fi
