name: docker-translation

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
    paths:
      - ".version"
      - ".github/docker/Dockerfile.translation"
  pull_request:
    paths:
      - ".version"
      - ".github/docker/Dockerfile.translation"
      - ".github/workflows/docker-translation.yml"

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  get-environment:
    needs: [dependency-scan]
    if: github.repository == 'centreon/centreon'
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: centreon/www/install/insertBaseConf.sql

  dockerize:
    needs: [get-environment]
    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Login to registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ghcr.io/${{ github.repository }}/translation

      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: .github/docker/Dockerfile.translation
          context: .
          pull: true
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}/translation:${{ needs.get-environment.outputs.major_version }}
          labels: ${{ steps.meta.outputs.labels }}

  set-skip-label:
    needs: [get-environment, dockerize]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled')
    uses: ./.github/workflows/set-pull-request-skip-label.yml
