name: Build stable release containers

run-name: |
  ${{ format('Build stable release containers for tag {0}', inputs.release_bundle_tag) }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      release_bundle_tag:
        description: 'Release bundle tag'
        required: true
        default: ''
        type: string

env:
  GH_TOKEN: ${{ github.token }}
  JF_URL: https://centreon.jfrog.io
  JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

jobs:
  check-inputs:
    outputs:
      operating_systems: ${{ steps.check_promoted_packages.outputs.operating_systems }}
      major_version: ${{ steps.check_promoted_packages.outputs.major_version }}
      is_cloud: ${{ steps.check_promoted_packages.outputs.is_cloud }}
    runs-on: ubuntu-24.04
    steps:
      - name: Check if ${{ inputs.release_bundle_tag }} exists on onprem repositories
        shell: bash
        run: |
          for repo in "centreon" "centreon-collect"; do
            if [[ -z $(gh api repos/centreon/$repo/tags --paginate -q '[.[] | select(.name | startswith("${{ inputs.release_bundle_tag }}"))] | .[].name') ]]; then
              echo "::error::Release bundle tag ${{ inputs.release_bundle_tag }} could not be found on repository $repo."
              echo "Command: gh api repos/centreon/$repo/tags --paginate -q '[.[] | select(.name | startswith(\"${{ inputs.release_bundle_tag }}\"))] | .[].name')"
              echo "Command output: $(gh api repos/centreon/$repo/tags --paginate -q '[.[] | select(.name | startswith("${{ inputs.release_bundle_tag }}"))] | .[].name')"
              exit 1
            else
              echo "Release bundle ${{ inputs.release_bundle_tag }} was found on repository $repo."
              echo "Information fetched on the tag: $(gh api repos/centreon/centreon/tags --paginate -q '[.[] | select(.name | startswith("${{ inputs.release_bundle_tag }}"))] | .[]' )"
            fi
          done

      - name: Checkout major version on bundle tag
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.release_bundle_tag }}
          sparse-checkout: .version

      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@18e785fb220d332edbf01964f853ff0fcaa22220 # v4.4.2
        env:
          JF_URL: https://centreon.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Check if promoted packages are available for the version
        shell: bash
        id: check_promoted_packages
        run: |
          source .version
          major_version=$MAJOR
          if ! [[ ${major_version} =~ ^2[0-9]\.(04|10)$ ]]; then
            echo "is_cloud=true" >> $GITHUB_OUTPUT
            DISTRIBS=("el9")
            REPO="rpm-standard-internal"
          else
            echo "is_cloud=false" >> $GITHUB_OUTPUT
            # TODO: Variabilize distributions according to versions
            DISTRIBS=("el8" "el9")
            REPO="rpm-standard"
          fi

          for distrib in "${DISTRIBS[@]}"; do
            for arch in "noarch" "x86_64"; do
              if [[ $(jf rt s $REPO/$major_version/$distrib/stable/$arch/*.rpm | jq '. | length') -le 1 ]]; then
                echo "::warning:: Packages may not have been correctly promoted for this configuration. (Repo $REPO, distrib $distrib, arch $arch)"
              fi
            done
          done

          operating_systems=$(printf '%s\n' "${DISTRIBS[@]}" | jq -R . | jq -s -c .)
          echo $operating_systems
          echo "operating_systems=$operating_systems" >> $GITHUB_OUTPUT
          echo "major_version=$major_version" >> $GITHUB_OUTPUT

  dockerize-stable-web:
    needs: [check-inputs]
    runs-on: ubuntu-24.04
    env:
      project: centreon-web

    strategy:
      fail-fast: false
      matrix:
        distrib: ${{ fromJson(needs.check-inputs.outputs.operating_systems) }}

    name: dockerize-web ${{ matrix.distrib }}

    steps:
      - name: Generate information according to matrix os
        id: matrix_include
        run: |
          if [ "${{ matrix.distrib }}" = "el8" ]; then
            DISTRIB=alma8
            PACKAGE_EXTENSION=rpm
          elif [ "${{ matrix.distrib }}" = "el9" ]; then
            DISTRIB=alma9
            PACKAGE_EXTENSION=rpm
          elif [ "${{ matrix.distrib }}" = "bullseye" ]; then
            DISTRIB=bullseye
            PACKAGE_EXTENSION=deb
          elif [ "${{ matrix.distrib }}" = "bookworm" ]; then
            DISTRIB=bookworm
            PACKAGE_EXTENSION=deb
          elif [ "${{ matrix.distrib }}" = "jammy" ]; then
            DISTRIB=jammy
            PACKAGE_EXTENSION=deb
          elif [ "${{ matrix.distrib }}" = "noble" ]; then
            DISTRIB=jammy
            PACKAGE_EXTENSION=deb
          else
            echo "::error::${{ matrix.distrib }} is not managed"
            exit 1
          fi

          echo "distrib=$DISTRIB" >> $GITHUB_OUTPUT
          echo "package_extension=$PACKAGE_EXTENSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout dockerize and .version files on version ${{ inputs.release_bundle_tag }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # REF TO REVERT
          ref: MON-190211-25.10.x-update-dockerfiles-to-account-for-stable-releases
          sparse-checkout: |
            .github/docker/${{ env.project }}/${{ steps.matrix_include.outputs.distrib }}/
            .github/docker/${{ env.project }}/init/
            .github/docker/${{ env.project }}/scripts/
            .github/docker/${{ env.project }}/sql/
            .version.centreon-awie
            .version.centreon-dsm
            .version.centreon-ha
            .version.centreon-open-tickets
            .version.centreon-web

      - name: Login to registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.HARBOR_CENTREON_PUSH_USERNAME }}
          password: ${{ secrets.HARBOR_CENTREON_PUSH_TOKEN }}

      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Checkout collect .version files on bundle tag ${{ inputs.release_bundle_tag }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: centreon/centreon-collect
          ref: ${{ inputs.release_bundle_tag }}
          path: ./centreon-${{ inputs.release_bundle_tag }}
          sparse-checkout: |
            .version.centreon-collect
            .version.centreon-common
            .version.centreon-gorgone
          sparse-checkout-cone-mode: false

      - name: Export minor versions
        id: export-minor-versions
        shell: bash
        run: |
          mv .version.* ./centreon-${{ inputs.release_bundle_tag }}/
          echo "[DEBUG]"
          ls -lah
          echo "[DEBUG]"
          ls -lah ./centreon-${{ inputs.release_bundle_tag }}
          for package in "collect" "gorgone" "common" "awie" "dsm" "ha" "open-tickets" "web"; do
            source centreon-${{ inputs.release_bundle_tag }}/.version.centreon-${package}
            echo "${package}_minor_version: $MINOR"
            echo "${package}_minor_version=$MINOR" >> $GITHUB_OUTPUT
          done

          mkdir /tmp/packages-centreon

      - name: Build dependencies web image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        with:
          file: .github/docker/${{ env.project }}/${{ steps.matrix_include.outputs.distrib }}/Dockerfile.dependencies
          target: web_dependencies
          context: .
          build-args: |
            "MAJOR_VERSION=${{ needs.check-inputs.outputs.major_version }}"
            "IS_CLOUD=${{ needs.check-inputs.outputs.is_cloud }}"
            "STABILITY=STABLE"
          pull: false
          push: false
          load: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/centreon-web-dependencies-${{ steps.matrix_include.outputs.distrib }}:${{ inputs.release_bundle_tag }}
          secrets: |
            "ARTIFACTORY_INTERNAL_REPO_USERNAME=${{ secrets.ARTIFACTORY_INTERNAL_REPO_USERNAME }}"
            "ARTIFACTORY_INTERNAL_REPO_PASSWORD=${{ secrets.ARTIFACTORY_INTERNAL_REPO_PASSWORD }}"

      - name: Build dependencies collect image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        with:
          file: .github/docker/centreon-web/${{ steps.matrix_include.outputs.distrib }}/Dockerfile.dependencies
          target: web_dependencies_collect
          context: .
          build-args: |
            "COLLECT_MINOR_VERSION=${{ steps.export-minor-versions.outputs.collect_minor_version }}"
            "COMMON_MINOR_VERSION=${{ steps.export-minor-versions.outputs.common_minor_version }}"
            "GORGONE_MINOR_VERSION=${{ steps.export-minor-versions.outputs.gorgone_minor_version }}"
            "MAJOR_VERSION=${{ needs.check-inputs.outputs.major_version }}"
            "IS_CLOUD=${{ needs.check-inputs.outputs.is_cloud }}"
            "STABILITY=STABLE"
          pull: false
          push: false
          load: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/centreon-web-dependencies-collect-${{ steps.matrix_include.outputs.distrib }}:${{ inputs.release_bundle_tag }}
          secrets: |
            "ARTIFACTORY_INTERNAL_REPO_USERNAME=${{ secrets.ARTIFACTORY_INTERNAL_REPO_USERNAME }}"
            "ARTIFACTORY_INTERNAL_REPO_PASSWORD=${{ secrets.ARTIFACTORY_INTERNAL_REPO_PASSWORD }}"

      - name: Build and push web image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: .github/docker/${{ env.project }}/${{ steps.matrix_include.outputs.distrib }}/Dockerfile
          context: .
          build-args: |
            "WEB_MINOR_VERSION=${{ steps.export-minor-versions.outputs.web_minor_version }}"
            "REGISTRY_URL=${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}"
            "FROM_IMAGE_VERSION=${{ inputs.release_bundle_tag }}"
            "MAJOR_VERSION=${{ needs.check-inputs.outputs.major_version }}"
            "STABILITY=STABLE"
          pull: false
          push: false
          load: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.project }}-${{ steps.matrix_include.outputs.distrib }}:${{ inputs.release_bundle_tag }}
