name: get-changes-triggers

on:
  workflow_call:
    inputs:
      backend_production_paths:
        required: true
        type: string
      frontend_production_paths:
        required: true
        type: string
      backend_test_paths:
        required: false
        type: string
        default: ''
      frontend_test_paths:
        required: false
        type: string
        default: ''
      api_test_paths:
        required: false
        type: string
        default: ''
      e2e_test_paths:
        required: false
        type: string
        default: ''
      upgrade_test_paths:
        required: false
        type: string
        default: ''
      is_nightly:
        required: true
        type: string
      base_sha:
        required: false
        type: string
        default: ''
      labels:
        required: false
        type: string
        default: '[]'
    outputs:
      trigger_backend_testing:
        description: "if the backend testing job should be triggered"
        value: ${{ jobs.get-triggers.outputs.trigger_backend_testing }}
      trigger_frontend_testing:
        description: "if the frontend testing job should be triggered"
        value: ${{ jobs.get-triggers.outputs.trigger_frontend_testing }}
      trigger_packaging:
        description: "if the packaging job should be triggered"
        value: ${{ jobs.get-triggers.outputs.trigger_packaging }}
      trigger_api_testing:
        description: "if the API testing job should be triggered"
        value: ${{ jobs.get-triggers.outputs.trigger_api_testing }}
      trigger_e2e_testing:
        description: "if the E2E testing job should be triggered"
        value: ${{ jobs.get-triggers.outputs.trigger_e2e_testing }}
      trigger_upgrade_testing:
        description: "if the upgrade tests should be triggered"
        value: ${{ jobs.get-triggers.outputs.trigger_upgrade_testing }}
      trigger_delivery:
        description: "if the delivery job should be triggered"
        value: ${{ jobs.get-triggers.outputs.trigger_delivery }}

jobs:
  get-triggers:
    runs-on: ubuntu-24.04
    outputs:
      trigger_backend_testing: ${{ github.event_name == 'workflow_dispatch' && steps.get_dispatch_triggers.outputs.trigger_backend_testing || steps.get_triggers.outputs.trigger_backend_testing || 'true' }}
      trigger_frontend_testing: ${{ github.event_name == 'workflow_dispatch' && steps.get_dispatch_triggers.outputs.trigger_frontend_testing || steps.get_triggers.outputs.trigger_frontend_testing || 'true' }}
      trigger_packaging: ${{ github.event_name == 'workflow_dispatch' && steps.get_dispatch_triggers.outputs.trigger_packaging || steps.get_triggers.outputs.trigger_packaging || 'true' }}
      trigger_api_testing: ${{ github.event_name == 'workflow_dispatch' && steps.get_dispatch_triggers.outputs.trigger_api_testing || steps.get_triggers.outputs.trigger_api_testing || 'true' }}
      trigger_e2e_testing: ${{ github.event_name == 'workflow_dispatch' && steps.get_dispatch_triggers.outputs.trigger_e2e_testing || steps.get_triggers.outputs.trigger_e2e_testing || 'true' }}
      trigger_upgrade_testing: ${{ github.event_name == 'workflow_dispatch' && steps.get_dispatch_triggers.outputs.trigger_upgrade_testing || steps.get_triggers.outputs.trigger_upgrade_testing || 'true' }}
      trigger_delivery: ${{ github.event_name == 'workflow_dispatch' && steps.get_dispatch_triggers.outputs.trigger_delivery || steps.get_triggers.outputs.trigger_delivery || 'true' }}

    steps:
      - name: Checkout sources
        if: github.event_name == 'pull_request' || inputs.base_sha != ''
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Fetch tags
        if: inputs.base_sha != ''
        run: git fetch origin tag ${{ inputs.base_sha }} --no-tags || true
        shell: bash

      - name: Convert inputs to yaml list
        if: github.event_name == 'pull_request' || inputs.base_sha != ''
        id: inline_inputs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          FRONTEND_PRODUCTION_PATHS: ${{ inputs.frontend_production_paths }}
          BACKEND_PRODUCTION_PATHS: ${{ inputs.backend_production_paths }}
          BACKEND_TEST_PATHS: ${{ inputs.backend_test_paths }}
          FRONTEND_TEST_PATHS: ${{ inputs.frontend_test_paths }}
          API_TEST_PATHS: ${{ inputs.api_test_paths }}
          E2E_TEST_PATHS: ${{ inputs.e2e_test_paths }}
          UPGRADE_TEST_PATHS: ${{ inputs.upgrade_test_paths }}
        with:
          script: |
            const paths = {
              frontend_production_paths: process.env.FRONTEND_PRODUCTION_PATHS,
              backend_production_paths: process.env.BACKEND_PRODUCTION_PATHS,
              backend_test_paths: process.env.BACKEND_TEST_PATHS,
              frontend_test_paths: process.env.FRONTEND_TEST_PATHS,
              api_test_paths: process.env.API_TEST_PATHS,
              e2e_test_paths: process.env.E2E_TEST_PATHS,
              upgrade_test_paths: process.env.UPGRADE_TEST_PATHS,
            };

            for (const [key, value] of Object.entries(paths)) {
              const formattedValue = value
                .split('\n')
                .map(line => line.trim())
                .map(line => line.replace(/^("|')|("|')$/g, ''))
                .filter(line => line.length > 0)
                .map(line => `  - "${line}"`)
                .join('\n');
              console.log(`${key}:\n${formattedValue}`);
              core.setOutput(key, formattedValue);
            }

      - name: Get changed files
        if: github.event_name == 'pull_request' || inputs.base_sha != ''
        id: get_changed_files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          base_sha: ${{ github.event_name == 'pull_request' && ' ' || inputs.base_sha }}
          files_yaml: |
            frontend_production:
            ${{ steps.inline_inputs.outputs.frontend_production_paths }}
            backend_production:
            ${{ steps.inline_inputs.outputs.backend_production_paths }}
            backend_test:
            ${{ steps.inline_inputs.outputs.backend_test_paths }}
            frontend_test:
            ${{ steps.inline_inputs.outputs.frontend_test_paths }}
            api_test:
            ${{ steps.inline_inputs.outputs.api_test_paths }}
            e2e_test:
            ${{ steps.inline_inputs.outputs.e2e_test_paths }}
            upgrade_test:
            ${{ steps.inline_inputs.outputs.upgrade_test_paths }}

      - name: Determine triggers for event ${{ github.event_name }}
        if: github.event_name == 'pull_request' || inputs.base_sha != ''
        id: get_triggers
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          IS_NIGHTLY: ${{ inputs.is_nightly }}
          HAS_FRONTEND_PRODUCTION_CHANGES: ${{ steps.get_changed_files.outputs.frontend_production_any_changed }}
          HAS_BACKEND_PRODUCTION_CHANGES: ${{ steps.get_changed_files.outputs.backend_production_any_changed }}
          HAS_FRONTEND_TEST_CHANGES: ${{ steps.get_changed_files.outputs.frontend_test_any_changed }}
          HAS_BACKEND_TEST_CHANGES: ${{ steps.get_changed_files.outputs.backend_test_any_changed }}
          HAS_API_TEST_CHANGES: ${{ steps.get_changed_files.outputs.api_test_any_changed }}
          HAS_E2E_TEST_CHANGES: ${{ steps.get_changed_files.outputs.e2e_test_any_changed }}
          HAS_UPGRADE_TEST_CHANGES: ${{ steps.get_changed_files.outputs.upgrade_test_any_changed }}
          LABELS: ${{ inputs.labels }}
        with:
          script: |
            try {
              const labels = JSON.parse(process.env.LABELS);
              if (labels.includes('force-backend-tests')) {
                core.info('Label force-backend-tests found: forcing backend testing trigger to true');
                process.env.HAS_BACKEND_TEST_CHANGES = 'true';
              }
              if (labels.includes('force-frontend-tests')) {
                core.info('Label force-frontend-tests found: forcing frontend testing trigger to true');
                process.env.HAS_FRONTEND_TEST_CHANGES = 'true';
              }
              if (labels.includes('force-api-tests')) {
                core.info('Label force-api-tests found: forcing API testing trigger to true');
                process.env.HAS_API_TEST_CHANGES = 'true';
              }
              if (labels.includes('force-e2e-tests')) {
                core.info('Label force-e2e-tests found: forcing E2E testing trigger to true');
                process.env.HAS_E2E_TEST_CHANGES = 'true';
              }
              if (labels.includes('force-upgrade-tests')) {
                core.info('Label force-upgrade-tests found: forcing upgrade testing trigger to true');
                process.env.HAS_UPGRADE_TEST_CHANGES = 'true';
              }
              if (labels.includes('force-all-tests')) {
                core.info('Label force-all-tests found: forcing all testing triggers to true');
                process.env.HAS_BACKEND_TEST_CHANGES = 'true';
                process.env.HAS_FRONTEND_TEST_CHANGES = 'true';
                process.env.HAS_API_TEST_CHANGES = 'true';
                process.env.HAS_E2E_TEST_CHANGES = 'true';
                process.env.HAS_UPGRADE_TEST_CHANGES = 'true';
              }
            } catch (e) {
              core.warning(`Could not parse labels: ${e}`);
            }

            const outputs = {
              'trigger_backend_testing':
                process.env.IS_NIGHTLY === 'true'
                || process.env.HAS_BACKEND_TEST_CHANGES === 'true'
                || process.env.HAS_BACKEND_PRODUCTION_CHANGES === 'true',
              'trigger_frontend_testing':
                process.env.IS_NIGHTLY === 'true'
                || process.env.HAS_FRONTEND_TEST_CHANGES === 'true'
                || process.env.HAS_FRONTEND_PRODUCTION_CHANGES === 'true',
              'trigger_packaging':
                process.env.IS_NIGHTLY === 'true'
                || process.env.HAS_FRONTEND_PRODUCTION_CHANGES === 'true'
                || process.env.HAS_BACKEND_PRODUCTION_CHANGES === 'true'
                || process.env.HAS_API_TEST_CHANGES === 'true'
                || process.env.HAS_E2E_TEST_CHANGES === 'true',
              'trigger_api_testing':
                process.env.IS_NIGHTLY === 'true'
                || process.env.HAS_BACKEND_PRODUCTION_CHANGES === 'true'
                || process.env.HAS_API_TEST_CHANGES === 'true',
              'trigger_e2e_testing':
                process.env.IS_NIGHTLY === 'true'
                || process.env.HAS_FRONTEND_PRODUCTION_CHANGES === 'true'
                || process.env.HAS_BACKEND_PRODUCTION_CHANGES === 'true'
                || process.env.HAS_E2E_TEST_CHANGES === 'true',
              'trigger_upgrade_testing':
                process.env.IS_NIGHTLY === 'true'
                || process.env.HAS_UPGRADE_TEST_CHANGES === 'true',
              'trigger_delivery':
                process.env.IS_NIGHTLY === 'true'
                || process.env.HAS_FRONTEND_PRODUCTION_CHANGES === 'true'
                || process.env.HAS_BACKEND_PRODUCTION_CHANGES === 'true',
            };

            for (const [key, value] of Object.entries(outputs)) {
              console.log(`${key}=${value}`);
              core.setOutput(key, value ? 'true' : 'false');
            }

      - name: Determine triggers for event ${{ github.event_name }}
        if: github.event_name == 'workflow_dispatch'
        id: get_dispatch_triggers
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          LABELS: ${{ inputs.labels }}
        with:
          script: |
            let triggerBackendTesting = true;
            let triggerFrontendTesting = true;
            let triggerApiTesting = true;
            let triggerE2eTesting = true;
            let triggerUpgradeTesting = true;

            try {
              const labels = JSON.parse(process.env.LABELS);
              if (labels.includes('skip-backend-tests')) {
                core.info('Label skip-backend-tests found: forcing backend testing trigger to false');
                triggerBackendTesting = false;
              }
              if (labels.includes('skip-frontend-tests')) {
                core.info('Label skip-frontend-tests found: forcing frontend testing trigger to false');
                triggerFrontendTesting = false;
              }
              if (labels.includes('skip-api-tests')) {
                core.info('Label skip-api-tests found: forcing API testing trigger to false');
                triggerApiTesting = false;
              }
              if (labels.includes('skip-e2e-tests')) {
                core.info('Label skip-e2e-tests found: forcing E2E testing trigger to false');
                triggerE2eTesting = false;
              }
              if (labels.includes('skip-upgrade-tests')) {
                core.info('Label skip-upgrade-tests found: forcing upgrade testing trigger to false');
                triggerUpgradeTesting = false;
              }
              if (labels.includes('skip-all-tests')) {
                core.info('Label skip-all-tests found: forcing all testing triggers to false');
                triggerBackendTesting = false;
                triggerFrontendTesting = false;
                triggerApiTesting = false;
                triggerE2eTesting = false;
                triggerUpgradeTesting = false;
              }
            } catch (e) {
              core.warning(`Could not parse labels: ${e}`);
            }

            core.setOutput('trigger_backend_testing', triggerBackendTesting ? 'true' : 'false');
            core.setOutput('trigger_frontend_testing', triggerFrontendTesting ? 'true' : 'false');
            core.setOutput('trigger_packaging', 'true');
            core.setOutput('trigger_api_testing', triggerApiTesting ? 'true' : 'false');
            core.setOutput('trigger_e2e_testing', triggerE2eTesting ? 'true' : 'false');
            core.setOutput('trigger_upgrade_testing', triggerUpgradeTesting ? 'true' : 'false');
            core.setOutput('trigger_delivery', 'true');
