name: ha

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      labels:
        description: "Labels to add to the run (comma separated)"
        required: false
        default: ""
        type: string
  pull_request:
    paths:
      - ".github/workflows/ha.yml"
      - ".version"
      - ".version.centreon-ha"
      - "centreon-ha/**"
  push:
    branches:
      - dev-[2-9][0-9].[0-9][0-9].x
      - "[2-9][0-9].[0-9][0-9].x"
      - 'release-[2-9][0-9].[0-9][0-9]-next'
      - 'hotfix-[2-9][0-9].[0-9][0-9]-next'
    paths:
      - ".version"
      - ".version.centreon-ha"
      - "centreon-ha/**"
    tags:
      - "centreon-ha-*"

env:
  module: ha

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  get-environment:
    needs: [dependency-scan]
    if: github.event.pull_request.head.repo.fork != true
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: centreon-ha/.env
      labels: ${{ inputs.labels || '' }}

  changes:
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable' &&
      github.event.pull_request.head.repo.fork != true
    needs: [get-environment]
    uses: ./.github/workflows/get-changes-triggers.yml
    with:
      backend_production_paths: |
        ".version"
        ".version.centreon-ha"
        "centreon-ha/bin/**"
        "centreon-ha/etc/**"
        "centreon-ha/lib/**"
        "centreon-ha/ocf-scripts/**"
        "centreon-ha/packaging/**"
        "centreon-ha/systemd/**"
        "centreon-ha/.env"
      frontend_production_paths: |
        ""
      is_nightly: ${{ needs.get-environment.outputs.is_nightly }}
      base_sha: ${{ needs.get-environment.outputs.previous_release_bundle_tag }}
      labels: ${{ needs.get-environment.outputs.labels }}

  package:
    needs: [get-environment, changes]
    if: |
      needs.changes.outputs.trigger_packaging == 'true' &&
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable' &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled') &&
      github.event.pull_request.head.repo.fork != true

    strategy:
      fail-fast: false
      matrix:
        distrib: [el8, el9, bookworm]
        include:
          - package_extension: rpm
            tag_suffix: -alma8
            distrib: el8
          - package_extension: rpm
            tag_suffix: -alma9
            distrib: el9
          - package_extension: deb
            tag_suffix: -bookworm
            distrib: bookworm

    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/centreon/delivery-tooling/packaging:${{ needs.get-environment.outputs.major_version }}${{ matrix.tag_suffix }}

    name: package ${{ matrix.distrib }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Package
        uses: ./.github/actions/package-nfpm
        with:
          nfpm_file_pattern: "centreon-ha/packaging/*.yaml"
          module_name: centreon-ha
          distrib: ${{ matrix.distrib }}
          package_extension: ${{ matrix.package_extension }}
          major_version: ${{ needs.get-environment.outputs.major_version }}
          minor_version: ${{ needs.get-environment.outputs.minor_version }}
          release: ${{ needs.get-environment.outputs.release }}
          arch: all
          commit_hash: ${{ github.sha }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
          rpm_gpg_key: ${{ secrets.RPM_GPG_SIGNING_KEY }}
          rpm_gpg_signing_key_id: ${{ secrets.RPM_GPG_SIGNING_KEY_ID }}
          rpm_gpg_signing_passphrase: ${{ secrets.RPM_GPG_SIGNING_PASSPHRASE }}
          stability: ${{ needs.get-environment.outputs.stability }}
          upload_artifacts: ${{ needs.get-environment.outputs.is_nightly == 'true' || contains(needs.get-environment.outputs.labels, 'upload-artifacts') && 'true' || 'false' }}

  deliver-sources:
    runs-on: centreon-common
    needs: [get-environment, package]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability == 'stable' &&
      contains(fromJson('["stable"]'), needs.get-environment.outputs.stability) &&
      github.event_name != 'workflow_dispatch' &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled') &&
      github.event.pull_request.head.repo.fork != true

    steps:
      - name: Checkout sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Deliver sources
        uses: ./.github/actions/release-sources
        with:
          bucket_directory: centreon-ha
          module_directory: centreon-ha
          module_name: centreon-ha
          major_version: ${{ needs.get-environment.outputs.major_version }}
          minor_version: ${{ needs.get-environment.outputs.minor_version }}
          token_download_centreon_com: ${{ secrets.TOKEN_DOWNLOAD_CENTREON_COM }}

  deliver:
    needs: [get-environment, changes, package]
    if: |
      needs.changes.outputs.trigger_delivery == 'true' &&
      needs.get-environment.outputs.skip_workflow == 'false' &&
      contains(fromJson('["testing", "unstable"]'), needs.get-environment.outputs.stability) &&
      needs.get-environment.outputs.is_cloud == 'false' &&
      github.event.pull_request.head.repo.fork != true
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include: ${{ fromJson(needs.get-environment.outputs.package_matrix) }}

    name: deliver ${{ matrix.distrib }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Deliver RPM package
        if: matrix.package_extension == 'rpm'
        uses: ./.github/actions/rpm-delivery
        with:
          module_name: ha
          distrib: ${{ matrix.distrib }}
          version: ${{ needs.get-environment.outputs.major_version }}
          artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-rpm-${{ matrix.distrib }}
          stability: ${{ needs.get-environment.outputs.stability }}
          release_type: ${{ needs.get-environment.outputs.release_type }}
          is_cloud: ${{ needs.get-environment.outputs.is_cloud }}
          delivery_type: ${{ needs.get-environment.outputs.delivery_type }}
          centreon_technique_pat: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

      - name: Deliver DEB package
        if: matrix.package_extension == 'deb'
        uses: ./.github/actions/deb-delivery
        with:
          module_name: ha
          distrib: ${{ matrix.distrib }}
          version: ${{ needs.get-environment.outputs.major_version }}
          artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-deb-${{ matrix.distrib }}
          stability: ${{ needs.get-environment.outputs.stability }}
          release_type: ${{ needs.get-environment.outputs.release_type }}
          is_cloud: ${{ needs.get-environment.outputs.is_cloud }}

  promote:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      contains(fromJson('["stable"]'), needs.get-environment.outputs.stability) &&
      github.event_name != 'workflow_dispatch' &&
      needs.get-environment.outputs.is_cloud == 'false' &&
      github.event.pull_request.head.repo.fork != true
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-environment.outputs.package_matrix) }}

    name: promote ${{ matrix.distrib }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Promote ${{ matrix.distrib }} to stable
        uses: ./.github/actions/promote-to-stable
        with:
          artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          module_name: ha
          distrib: ${{ matrix.distrib }}
          major_version: ${{ needs.get-environment.outputs.major_version }}
          minor_version: ${{ needs.get-environment.outputs.minor_version }}
          stability: ${{ needs.get-environment.outputs.stability }}
          github_ref_name: ${{ github.ref_name }}
          release_type: ${{ needs.get-environment.outputs.release_type }}
          is_cloud: ${{ needs.get-environment.outputs.is_cloud }}
