---
name: sync-stable-to-dev

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "[2-9][0-9].[0-9][0-9].x"
  workflow_dispatch:

jobs:
  main:
    name: Sync branches
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

      - name: Sync stable branch to dev branch
        id: release
        uses: ./.github/actions/sync-branches
        with:
          src_branch: ${{ github.ref_name }}
          dest_branch: dev-${{ github.ref_name }}
          token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

