name: Integrate e2e tests to Xray

on:
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  get-environment:
    needs: [dependency-scan]
    if: github.repository == 'centreon/centreon'
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: centreon/www/install/insertBaseConf.sql

  synchronize-jira-xray:
    needs: [get-environment]
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24

      - uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4
        with:
          version: 10
          run_install: |
            cwd: ".github/scripts/xray"
            args: [--ignore-scripts, --frozen-lockfile]

      - name: Get the latest commit hash
        run: |
          latest_commit=$(git log -1 --format="%H")
          echo "LATEST_COMMIT=$latest_commit" >> $GITHUB_ENV

      - name: Find Changed Feature Files
        id: find_changed_files
        run: |
          mapfile -t CHANGED_FILES <<< "$(git show --name-only $LATEST_COMMIT | grep '\.feature$')"
          echo "CHANGED_FILES=${CHANGED_FILES[*]}" >> $GITHUB_ENV
          echo "Changed .feature files: ${CHANGED_FILES[*]}"

      - name: Run Script on Changed Feature Files
        if: env.CHANGED_FILES != ''
        run: |
          echo "The target version for this script is : $MAJOR_VERSION"
          for file in $CHANGED_FILES; do
            echo "Running script for $file on branch $REF_NAME"
            node .github/scripts/xray/synchronize_jira_xray.js "$file" "$REF_NAME" "$MAJOR_VERSION"
          done
        env:
          XRAY_JIRA_USER_EMAIL: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
          XRAY_JIRA_TOKEN: ${{ secrets.XRAY_JIRA_TOKEN }}
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
          REF_NAME: ${{ github.ref_name }}
          MAJOR_VERSION: ${{ needs.get-environment.outputs.major_version }}
