name: centreon-ui-stable

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
    paths:
      - "centreon/packages/ui/**"
      - ".github/actions/npm-publish-package-stable/**"
      - '.github/workflows/ui-stable.yml'
      - "!centreon/packages/ui/package.json"

env:
  directory: "centreon/packages/ui"
  package: "ui"

jobs:
  publish-new-npm-version:
    if: github.repository == 'centreon/centreon'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/actions/npm-publish-package-stable
        with:
          directory: ${{ env.directory }}
          pat: ${{ secrets.CENTREON_TECHNIQUE_PAT }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          release_branch: ${{ github.ref_name }}
          package: ${{ env.package }}
