name: web
run-name: ${{ (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.nightly_manual_trigger == 'true')) && format('web nightly {0}', github.ref_name) || '' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      nightly_manual_trigger:
        description: "Set to true to trigger a nightly run"
        required: true
        default: false
        type: boolean
      labels:
        description: "Labels to add to the run (comma separated)"
        required: false
        default: ""
        type: string
  schedule:
    - cron: "0 3 * * 1-5"
  push:
    branches:
      - trigger-deliver-sources

env:
  base_directory: centreon
  widgets_directory: centreon/www/widgets
  e2e_directory: centreon/tests/e2e

jobs:
  get-environment:
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: centreon/www/install/insertBaseConf.sql
      nightly_manual_trigger: ${{ inputs.nightly_manual_trigger || false }}
      labels: ${{ inputs.labels || '' }}

  frontend-web-build:
    needs: [get-environment]
    # needed to deliver sources
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: ./.github/actions/frontend-build
        with:
          base_directory: ${{ env.base_directory }}
          dependencies_lock_file: ${{ env.base_directory }}/pnpm-lock.yaml
          index_file: ${{ env.base_directory }}/www/index.html
          static_directory: ${{ env.base_directory }}/www/static
          index_cache_key: ${{ github.sha }}-${{ github.run_id }}-index
          static_cache_key: ${{ github.sha }}-${{ github.run_id }}-static
          build_command: pnpm centreon:build

  frontend-widgets-build:
    needs: [get-environment]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: ./.github/actions/frontend-build
        with:
          base_directory: ${{ env.widgets_directory }}
          dependencies_lock_file: ${{ env.base_directory }}/pnpm-lock.yaml
          static_directory: ${{ env.widgets_directory }}/src
          static_cache_key: ${{ github.sha }}-${{ github.run_id }}-widgets-static

  backend-dependencies:
    needs: [get-environment]
    # needed to deliver sources
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup PHP
        uses: shivammathur/setup-php@6d7209f44a25a59e904b1ee9f3b0c33ab2cd888d # v2.29.0
        with:
          php-version: 8.2
        env:
          runner: ubuntu-24.04

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader
        working-directory: ${{ env.base_directory }}
        shell: bash

      - name: Cache vendor directory
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ${{ env.base_directory }}/vendor
          key: ${{ github.sha }}-${{ github.run_id }}-vendor

  translation-build:
    needs: [get-environment]
    # needed to deliver sources
    runs-on: ubuntu-24.04
    container:
      image: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/translation:${{ needs.get-environment.outputs.major_version }}
      credentials:
        username: ${{ secrets.HARBOR_CENTREON_PULL_USERNAME }}
        password: ${{ secrets.HARBOR_CENTREON_PULL_TOKEN }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 10
          token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

      - name: Build translations
        id: build-translations
        env:
          IS_NIGHTLY: ${{ needs.get-environment.outputs.is_nightly }}
          STABILITY: ${{ needs.get-environment.outputs.stability }}
          EVENT_NAME: ${{ github.event_name }}
          HAS_UPDATE_TRANSLATIONS_LABEL: ${{ contains(needs.get-environment.outputs.labels, 'update-translations') }}
        run: |
          TRANSLATIONS_PATCH_FILE=""

          git config --global --add safe.directory $GITHUB_WORKSPACE

          cd centreon

          for i in lang/*.UTF-8 ; do
            localefull="$(basename "$i")"
            langName="$(echo "$localefull" | cut -d . -f 1)"
            langShortName="$(echo "$localefull" | cut -d _ -f 1)"
            mkdir -p "www/locale/$localefull/LC_MESSAGES"
            bash -e ../.github/scripts/translation/make_translation.sh centreon $langName
            msgfmt "lang/$localefull/LC_MESSAGES/messages.po" -o "www/locale/$localefull/LC_MESSAGES/messages.mo" || exit 1
            msgfmt "lang/$localefull/LC_MESSAGES/help.po" -o "www/locale/$localefull/LC_MESSAGES/help.mo" || exit 1
            php bin/centreon-translations.php "$langShortName" "lang/$localefull/LC_MESSAGES/messages.po" "www/locale/$localefull/LC_MESSAGES/messages.ser"
          done

          mkdir -p www/locale/en_US.UTF-8/LC_MESSAGES
          php bin/centreon-translations.php en lang/fr_FR.UTF-8/LC_MESSAGES/messages.po www/locale/en_US.UTF-8/LC_MESSAGES/messages.ser

          if [[ "$(git diff --ignore-matching-lines="POT-Creation-Date" | wc -l)" != "0" ]]; then
            # avoid to always update POT-Creation-Date field
            find -type f -regex '.+\.pot?' -exec sed -i -e 's/"POT-Creation-Date.*$/"POT-Creation-Date: 2025-01-01 00:00+0000\\n"/g' {} \;
            if [[ ( "$IS_NIGHTLY" == "false" && "$STABILITY" == "unstable" ) || ( "$EVENT_NAME" == 'pull_request' && "$HAS_UPDATE_TRANSLATIONS_LABEL" == "true" ) ]]; then
              if [[ "$(git log -1 --pretty=format:'%an')" != "technique-ci" ]]; then
                git config user.name "technique-ci"
                git config user.email "technique+ci@centreon.com"
                git status
                git add .
                git commit -m "chore(lang): update translations"
                git push
              else
                echo "::notice::Last commit author is technique-ci. Skipping commit to avoid infinite loop."
                cd ..
                git diff > translations.patch
                TRANSLATIONS_PATCH_FILE="translations.patch"
              fi
            else
              echo "::notice::Translations have been updated, but the workflow is a nightly run or does not have the update-translations label. Skipping commit. Git patch will be available as artifact."
              cd ..
              git diff > translations.patch
              TRANSLATIONS_PATCH_FILE="translations.patch"
            fi
          else
            echo "No changes in translations"
          fi

          echo "translations_patch_file=$TRANSLATIONS_PATCH_FILE" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload translations patch
        if: ${{ steps.build-translations.outputs.translations_patch_file != '' }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: translations-patch
          path: ${{ steps.build-translations.outputs.translations_patch_file }}
          retention-days: 1

      - uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ env.base_directory }}/www/locale
          key: ${{ github.sha }}-${{ github.run_id }}-translation
  deliver-sources:
    runs-on: centreon-common
    needs: [get-environment, frontend-web-build, frontend-widgets-build, backend-dependencies, translation-build]

    steps:
      - name: Checkout sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Deliver sources
        uses: ./.github/actions/release-sources
        with:
          bucket_directory: centreon
          module_directory: centreon
          module_name: centreon-web
          frontend_index_cache_key: ${{ github.sha }}-${{ github.run_id }}-index
          frontend_index_file: centreon/www/index.html
          frontend_static_cache_key: ${{ github.sha }}-${{ github.run_id }}-static
          frontend_static_directory: centreon/www/static
          backend_vendor_cache_key: ${{ github.sha }}-${{ github.run_id }}-vendor
          backend_vendor_directory: centreon/vendor
          translation_cache_key: ${{ github.sha }}-${{ github.run_id }}-translation
          translation_directory: centreon/www/locale
          major_version: ${{ needs.get-environment.outputs.major_version }}
          minor_version: ${{ needs.get-environment.outputs.minor_version }}
          token_download_centreon_com: ${{ secrets.TOKEN_DOWNLOAD_CENTREON_COM }}
